### ISSUE TITLE
[Bug]: StrimziPodSet ignores strimzi.io/pause-reconciliation annotation

### ISSUE THREAD

**Issue by isitinschi** [strimzi/strimzi-kafka-operator#10042]
### Bug Description

https://strimzi.io/docs/operators/0.31.0/configuring#proc-pausing-reconciliation-str suggests that one can pause the reconciliation of custom resources managed by Strimzi Operators by setting the `strimzi.io/pause-reconciliation` annotation to `true`.

StrimziPodSet controller not only ignores the annotation, but also removes the annotation on next reconciliation of Kafka CR.

### Steps to reproduce

1. Create Kafka CR
2. `kubectl annotate StrimziPodSet <name> strimzi.io/pause-reconciliation="true"`
3. Delete broker Pod or trigger a rolling update.
4. broker Pod is recreated.
5. `strimzi.io/pause-reconciliation` annotation disappears from StrimziPodSet CR.

### Expected behavior

- underlying Pod should not be recreated when owning StrimziPodSet CR is annotated with `strimzi.io/pause-reconciliation="true"`.
- `strimzi.io/pause-reconciliation` annotation should not be removed from StrimziPodSet CR.

### Strimzi version

0.40.0

### Kubernetes version

v1.29.2

**Comment by scholzj** [comment]
This is not a bug. You cannot pause StrimziPodSet reconciliation. You can only pause the reconciliation of user-facing resources such as the Kafka CR.

**Comment by isitinschi** [comment]
Will it hurt if we extend such feature to StrimziPodSet? Are you open for such contribution?

**Comment by scholzj** [comment]
To be honest, I do not see any use-case for that. Operating the StrimziPodSets is key to keeping the pods alive and running.

**Comment by isitinschi** [comment]
Well, that's exactly the use case I care about. I want Strimzi to stop manipulating Pods until I am okay with that. Only Pods, everything else is fine to be touched. 

StrimziPodSet controller is a separate component responsible for Pods only, why can't we tell it to hold on for some time?

**Comment by scholzj** [comment]
That is not how it works -> without the pods everything else will fall apart (it will actually remove your annotation, but if it didn't, it would not work anyway). Also, that is not a use-case. Use-case is explaining why is it useful.

**Comment by isitinschi** [comment]
That's useful if I want to debug/investigate issues and don't want to scale operator down to 0. Sth like stopping a single broker without moving a Pod to a different node (e.g. when I suspect node level issues and want to see if stopping a single broker improves cluster health).

K8s Deployment supports pausing: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment

Why does it sound contradictory if someone wants the same for StrimziPodSet? It will be also consistent with all other custom resources of Strimzi, so no-one need to think about such special case.

**Comment by scholzj** [comment]
> That's useful if I want to debug/investigate issues and don't want to scale operator down to 0. Sth like stopping a single broker without moving a Pod to a different node (e.g. when I suspect node level issues and want to see if stopping a single broker improves cluster health).

Like how exactly is it useful? I'm not sure what does it mean to _stop a broker without moving a pod to a different node_. But if you force-stop the pod or make it unschedulable, the Kafka reconciliation will start failing. it will not improve any cluster health. 

> K8s Deployment supports pausing: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment

I don't think this does what you suggest it does. It pauses a rollout of the Deployment. But if you for example delete the existing pod, it will still be recreated as the StrimziPodSet operator does it.

While we do not aim to mirror any specific behavior of the `Deployment` controller, I would argue that the current state is more corresponding to this:
* If you pause the reconciliation of a Kafka resource, you pause any changes to the operand (i.e. pause rolling out the changes)
* But the old stuff will be kept running by the PodSet controller

> Why does it sound contradictory if someone wants the same for StrimziPodSet? It will be also consistent with all other custom resources of Strimzi, so no-one need to think about such special case.

Because these resources are on a different level. The StrimziPodSet is an internal resource not exposed to the users used as an implementation detail of the higher-level resources. If you would _stop_ it reconciliation, you will ultimately break the upper layer reconciliations. So this is a special case and you would need to think about it very carefully is there was such option.

If you want to manipulate low-level things such as the Pods, you can:
* Pause the reconciliation of the Kafka resource
* Delete the PodSet (without cascading if you need to keep the Pods)
* Do whatever you need to do to the Pods
* And once you are done, you just unpause the reconcilaition of the Kafka resource.

**Comment by isitinschi** [comment]
> Delete the PodSet (without cascading if you need to keep the Pods)

that's a very scary part of your suggestion.

**Comment by scholzj** [comment]
> that's a very scary part of your suggestion.

Well, that is probably not bad as you should be scared if you decide to manipulate the Pods in some way and you should really know what you are doing. 

That said, technically, the result is the same but without:
* Additional code to be written, tested, and maintained
* The complicated interaction with the Kafka operator that will be paused

But it does exactly the same -> the StrimziPodSet will not be there, so the PodSet operator will not interact in any way with the Pods managed by it.

**Comment by scholzj** [comment]
Discussed on the community call on 16.5.2024: This should not be implemented. Pausing the PodSet reconciliation would break up the reconciliation if the user facing custom resource. If you for whether reason need to debug some pods, the process described above through pausing the reconciliation of the user-facing custom resource (e.g. `Kafka` or `KafkaConnect`) is the right way.
