### ISSUE TITLE
Get rid of `ReadWriteUtils.readSingleLineJsonStringFromResourceFile` and its special handling

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10556]
The `ReadWriteUtils.readSingleLineJsonStringFromResourceFile` method seems to be reading JSON files in a very specific way. It seems to be used only for mocking Cruise Control. Does Cruise Control really require the JSON file to be processed in this specific way? We should try to use the other methods for reading files to Strings such as `ReadWriteUtils.readFileFromResources(...)` as given the nature of JSON, it should work the same way.

**Comment by ppatierno** [comment]
AFAICS the `ReadWriteUtils.readSingleLineJsonStringFromResourceFile` is just concatenating each line from the JSON by building a big String as it would happen with just using `ReadWriteUtils.readFileFromResources`. I think we should try to switch to the latter.

**Comment by im-konge** [comment]
Triaged on 19.9.2024: This makes sense and should be implemented.

**Comment by MichaelMorrisEst** [comment]
I can take a look at this

**Comment by MichaelMorrisEst** [comment]
The only difference between the outputs of the two methods is the inclusion of newline chars in the output from `readSingleLineJsonStringFromResourceFile(...)`. This presence or otherwise of the newline characters does not appear to have any consequence (as one would expect with JSON) so the method can be removed as suggested. I will submit PR
