### ISSUE TITLE
[Bug]: app.kubernetes.io/version is not added for cruise-control, mirror maker, kafka pods.

### ISSUE THREAD

**Issue by nsettipa** [strimzi/strimzi-kafka-operator#10606]
### Bug Description

Hi,
we have installed kafka, cruise control and mirror maker micro-services through Operator configuration. we have defined the environment variables to add meta data label: app.kubernetes.io/version. This is not reflected for cruise-control, mirror maker, kafka pods. 

Set below environment variables:
STRIMZI_CUSTOM_<COMPONENT_NAME>_LABELS. The component name added as per strimzi documentation such as KAFKA, CRUISE_CONTROL...etc. 

added value as: app.kubernetes.io/version: version_name

This variable got added to under environment section for kubectl describe pod and also as part of environment variables. 
The expectation is that, this custom label should be parsed and add the app.kubernetes.io/version under meta data label. 

This is not working. Please provide suggestion or solution. Thank you.

### Strimzi version

latest version

### Kubernetes version

1.25

### Installation method

Through yaml files

**Comment by ppatierno** [comment]
@nsettipa because this issue was opened 2 hours ago, it's clear that "latest version" for Strimzi is 0.43.0 but it won't be clear in the future when a new version is out. Can you update the issue by specifying the release version please?

**Comment by scholzj** [comment]
The `app.kubernetes.io` labels are complete mess. They are badly specified and everyone expects something else from them. That is why they have a special "treatment". So I do not think this is a bug. Using them was IMHO one of the bigger mistakes we did in the past. But any change will break things for someone else.

If I remember correctly, you might be able to set it on the custom resource, but not 100% sure because ... as I said ... this is one big mess.

**Comment by ppatierno** [comment]
Triaged on 03.10.2024: closing this. It's not considered a bug. Not planned to be investigated.
