### ISSUE TITLE
[Bug]: MockKube3ControllersMockTest.testDeploymentController test case is flaky 

### ISSUE THREAD

**Issue by see-quick** [strimzi/strimzi-kafka-operator#10616]
### Bug Description

Recently I found out that during build the `testDeploymentController` test case failed (but after re-run it was okay). So we should investigate what might be the cause of such a race condition and solve this.
```java
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] io.strimzi.test.mockkube3.MockKube3ControllersMockTest.testDeploymentController
[ERROR]   Run 1: MockKube3ControllersMockTest.testDeploymentController:142 
Expected: is <3>
     but: was null
[ERROR]   Run 2: MockKube3ControllersMockTest.testDeploymentController:142 
Expected: is <3>
     but: was null
[ERROR]   Run 3: MockKube3ControllersMockTest.testDeploymentController:142 
Expected: is <3>
     but: was null
[ERROR]   Run 4: MockKube3ControllersMockTest.testDeploymentController:142 
Expected: is <3>
     but: was null
[ERROR]   Run 5: MockKube3ControllersMockTest.testDeploymentController:142 
Expected: is <3>
     but: was null
[ERROR]   Run 6: MockKube3ControllersMockTest.testDeploymentController:142 
Expected: is <3>
     but: was null
```
Here is full log from the fail to investigate: [1]

[1] - https://gist.github.com/see-quick/34451c82f12edf865679448355a59e67

### Steps to reproduce

1. Run the build pipeline

### Expected behavior

testDeploymentController test case should not be flaky at all

### Strimzi version

main

### Kubernetes version

1.25.0

**Comment by scholzj** [comment]
To be honest, I never saw this one fail.

**Comment by MichaelMorrisEst** [comment]
When the deployment is created a `BOOKMARK` event is generated:
`{
  "type": "BOOKMARK",
  "object": {
    "kind": "Deployment",
    "apiVersion": "apps/v1",
    "metadata": {
      "resourceVersion": "1",
      "creationTimestamp": null
    },
    "spec": {
      "replicas": 0,
      "selector": null,
      "template": {
        "metadata": {
          "creationTimestamp": null
        },
        "spec": {
          "containers": null
        }
      },
      "strategy": {}
    },
    "status": {}
  }
}`

This event results in the Deployment object (dep) being updated accordingly. In the event the status is empty, and therefore the status in dep is changed from null to an empty object.

This releases the TestUtils.waitFor() (as the status is now an empty object rather than null) even though the Deployment object has not yet been updated for the `ADDED` event.

This is intermittent as it will depend on how much time elapses between the two events relative to the polling interval of the waitFor() method.

I can submit a PR to resolve

**Comment by MichaelMorrisEst** [comment]
I think I jumped the gun in my last comment. The event status is coming back as empty initially as I thought, but the reason is not related to the BOOKMARK events. Instead I believe the following is happening:
- When the create request is sent for the deployment, it is created in the mock kubernetes server but the status is not set and responses to get() on the deployment contain status as empty (but non null)
- It is only when the MockDeploymentController receives the event that the status is updated.

The check in TestUtils.waitFor() for non-null deployment status will can pass before the setting of the status in MockDeploymentController and the test case can fail in this scenario. The timing of the polling in the check relative to the handling of the event makes it intermittent.

The check needs to wait until after the event has been processed in MockDeploymentController

**Comment by see-quick** [comment]
> I think I jumped the gun in my last comment. The event status is coming back as empty initially as I thought, but the reason is not related to the BOOKMARK events. Instead I believe the following is happening:
> 
> * When the create request is sent for the deployment, it is created in the mock kubernetes server but the status is not set and responses to get() on the deployment contain status as empty (but non null)
> * It is only when the MockDeploymentController receives the event that the status is updated.
> 
> The check in TestUtils.waitFor() for non-null deployment status will can pass before the setting of the status in MockDeploymentController and the test case can fail in this scenario. The timing of the polling in the check relative to the handling of the event makes it intermittent.
> 
> The check needs to wait until after the event has been processed in MockDeploymentController

Hi @MichaelMorrisEst, I see thanks for investigating this issue. I will take a look at the PR then.
