### ISSUE TITLE
Unit tests fail when running with JRE 11

### ISSUE THREAD

**Issue by chonton** [strimzi/strimzi-kafka-operator#1194]
AbstractConfigurationTest, KafkaConnectClusterTest, and KafkaConnectS2IClusterTest fail when running under JRE11.  The order of values when iterating through a Properties is not defined; the unit tests expect a particular order.

Following solutions are possible:
1. Add AbstractConfiguration.asMap() method and change unit tests to compare maps instead of strings.
2. Change AbstractConfiguration.getConfiguration() to return values in insertion order.
3. Change AbstractConfiguration.getConfiguration() to return values in alphabetic key sort order.

Please respond with preferences.  I'll work on a pull request.

**Comment by tombentley** [comment]
I think ideally the unit tests shouldn't be making assertions which rely on the pre Java 11 behaviour. You can probably do that by using a helper method to convert the `Properties` to a `TreeMap` in the tests before making assertions, rather than in the `AbstractConfiguration`. There's a `TestUtils` class you could add it to.

If that doesn't work for some reason then I guess using option 2 would be my preferred alternative.
