### ISSUE TITLE
Expose Zookeeper to the outside world

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#129]
It should be possible to expose Zookeeper to the outside of OpenShift / Kubernetes world.

**Comment by f1yegor** [comment]
I agree with the case. 

from the documentation it's by design `3.1.10. ZooKeeper connection`
(https://strimzi.io/docs/latest/#assembly-zookeeper-connection-deployment-configuration-kafka).

I have several cases in mind:
1. we use secor(https://github.com/pinterest/secor), and it seems to be not working without explicit zookeeper connect. (even with https://github.com/pinterest/secor/pull/450)
2. reuse of zookeeper cluster for other jobs

**Comment by f1yegor** [comment]
ok, seems to be solved with zoo-entrance deployment from https://github.com/strimzi/strimzi-kafka-operator/issues/1337

**Comment by canberkkoc** [comment]
Hi, 

I tried the zoo entrance deployment with cluster-operator, it could not find entity operator cert what should i do to bypass this problem ?

**Comment by canberkkoc** [comment]
I figure out what i've done wrong. I did not define the empty entity operator at deployment so when i make definition it solved my problem .

**Comment by scholzj** [comment]
Zookeeper is being removed from Kafka soon (work in progress in Kafka community). So this does not make any long term sense anymore and should be rejected.
