### ISSUE TITLE
It takes 5 to 10 minutes to start a new cluster

### ISSUE THREAD

**Issue by Mikedu1988** [strimzi/strimzi-kafka-operator#1325]
We are using version 0.8.2.
We have a kubernetes cluster for develop and QA team to run their test. So there are many namespaces in that cluster. We need to deploy kafka into wach namespace and after the test is done, the namespace will be destoried.

Everything is working file until recently we noticed it will took 5 to 10 minustes for a 3 node ephemeral kafka cluster to be ready in new namespces.  Kafka service usually restart 4 to 5 times before it gets ready.
![goclient](https://user-images.githubusercontent.com/24424690/52615083-d7ca2280-2ece-11e9-8bc3-37692bf869d2.png)

And we are seeing connection rest error in the container:
![image](https://user-images.githubusercontent.com/24424690/52615138-1233bf80-2ecf-11e9-8c4f-6fbc465aa511.png)

But if we check kafka status in old namespaces, the restart count of kafka service are all 0, and kafka service will be ready in less than 1 minute
![uat](https://user-images.githubusercontent.com/24424690/52615088-dd276d00-2ece-11e9-8e24-68176f4fca0d.png)

these 5 to 10 mins are very big chanllenge to our delivery & test pipeline, is this a performance issue of cluster operator or any service I could look into?

**Comment by scholzj** [comment]
The Cluster Operator really just creates the statefulsets. Afterwards the
pods start on their own. So it would be interesting to look at the logs
from the broker and zookeeper but also from their sidecars which are
handling the TLS.

If this really happens just in some namespaces, you should make sure you
have enough resources, that there are no LimitRanges which would cause
issues etc.

Sometimes it also happens that the restarts of the pod at startup are just
caused by slow pulling of the images - when one container is already pukked
and started while the sidecar is still creating because it pulls slowly.
