### ISSUE TITLE
Question: Are there any plans to manage KSQL server with the operator? 

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [strimzi/strimzi-kafka-operator#1420]
Thanks

**Comment by scholzj** [comment]
We did had it in our long term plans, but TBH I do not even know whether it's still possible given the recent license change of KSQL. I would certainly not expect anything in next few weeks

**Comment by DanielFerreiraJorge** [comment]
Thank you for the answer. I believe that license wise there would be no problem at all... The only thing that cannot be done is to offer a Kafka SaaS that uses components under the confluent community license. Managing the components with the operator is like developing a helm chart to deploy the components... it does not violate the license... For reference https://www.confluent.io/confluent-community-license-faq

I think it would be really nice to have both KSQL and Schema registry in the operator!

Thanks!

**Comment by ludusrusso** [comment]
Hi, I was also looking for an integration of strimzi with ksql! 
With a small effort I was able to manually install schema_registry and ksql on a strimzi cluster.
If you are interested on that I can work on the integration and open a WP Pull Request!

**Comment by scholzj** [comment]
@ludusrusso Thanks for the offer- But as desciebed above (and in other issues about for example the Schema Registry), we are not planning any support for KSQL due to the licensing issues:
- I do not think we can easily support KSQL given the propretary license which might not be compatible with our ASL2.0 license. This would certainly need some legal analysis. There is a big difference between using something with these two licenses together and shipping something with these twolicenses together.
- We do not want to support any components with such restrictive licenses. We want Strimzi and all of its compoenents to be usable for everyone - even if they are running SaaS.

If there is something Strimzi needs to change so that users can connect with KSQL, we can discuss it. But my understanding is that KSQL is just as another client and doesn't need anything special to connect.

**Comment by ludusrusso** [comment]
@scholzj thanks for your reply and sorry for the request.
Anyway, it's quite easy to integrate ksql from confluent helm charts with strimzi :)

**Comment by scholzj** [comment]
I read it and it looks nice. Please let me know when you publish it and we can share it also through Strimzi channels (e.g. on Twitter).

**Comment by ankit1mg** [comment]
@ludusrusso It looks great to me also. We have also done it in the same way and it is working fine in our kubernetes cluster.

Thanks 👍

**Comment by ludusrusso** [comment]
> I read it and it looks nice. Please let me know when you publish it and we can share it also through Strimzi channels (e.g. on Twitter).

Nice! You can share if you want. Note that I've changed the url, this is the new one: https://ludusrusso.space/blog/2020/08/ksql-strimzi-k8s

**Comment by sreejesh-radhakrishnan-db** [comment]
Hi, the above link is not working (https://ludusrusso.space/blog/2020/08/ksql-strimzi-k8s)  @ludusrusso   possibel to share the steps again?

**Comment by ludusrusso** [comment]
> Hi, the above link is not working (https://ludusrusso.space/blog/2020/08/ksql-strimzi-k8s)  @ludusrusso   possibel to share the steps again? 

Sorry, moved domain :)

https://www.ludusrusso.dev/2020/08/strimzi-ksql

Not sure if it is still relevant

**Comment by sreejesh-radhakrishnan-db** [comment]
Sorry still same error for https://www.ludusrusso.dev/2020/08/strimzi-ksql   ->> "The webpage at https://www.ludusrusso.dev/2020/08/strimzi-ksql might be temporarily down or it may have moved permanently to a new web address."

**Comment by sreejesh-radhakrishnan-db** [comment]
jsut wanted to get a starting point :-)

**Comment by ludusrusso** [comment]
> Sorry still same error for https://www.ludusrusso.dev/2020/08/strimzi-ksql   ->> "The webpage at https://www.ludusrusso.dev/2020/08/strimzi-ksql might be temporarily down or it may have moved permanently to a new web address."

The secondo link works for me, don't know why you can't access :(

![image](https://user-images.githubusercontent.com/8146506/195330283-0efb2c07-9f6f-4de8-b79e-614e2ff6b237.png)

**Comment by scholzj** [comment]
Yeah, the new link seems to work fine for me as well.
