### ISSUE TITLE
Overriding zookeeper and tls-sidecar images

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1444]
#1415, #1425 and #1431 mean we now only have 3 docker images, {{kafka}}, {{operator}} and {{test-client}}, but how the defaults are configured has not been changed. You can still configure the {{image}} used for the various containers directly in the CRs, and those will override the defaults specified as env vars in the CO {{Deployment}}.

For the kafka images we generate a different image (differentiated by tag) for each different Kafka version supported in a release, so the CO env var is specifying a mapping of the image to use for each supported Kafka version. But for the zookeeper and stunnel containers the CO supports configuring only a single image name, not a map-style env var. This works fine because the {{stunnel}} and ZK binaries in the image are identical between the different Kafka images. However it is confusing when inspecting pods making it look like there is a problem. It's also not clear that this ability to use different images for these containers is really of any use. If users still want to customise the tls-sidecar containers they can still do that by rolling a custom kafka image.

We can simplify this by removing support for configuring the CO with defaults for the zookeeper and stunnel images. We would instead just use whatever image was being used for the main kafka image.

We could go further and remove support for overriding the image for these things in the CR.

**Comment by scholzj** [comment]
What would you do with Connect and Mirror Maker? The logic there seems to be the same.

**Comment by tombentley** [comment]
Those don't use tls-sidecars or need zk stuff, do they? If it wasn't clear I was suggesting these changes only for those images, i.e.

* `STRIMZI_DEFAULT_ZOOKEEPER_IMAGE`, 
* `STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE`, 
* `STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE`, 
* `STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE` 

and the related things in the Kafka CR: 

* `Kafka.spec.zookeeper.image`, 
* `Kafka.spec.(zookeeper|kafka|entityOperator.topicOperator).tlsSidecar.image`

**Comment by scholzj** [comment]
Yeah, I know you were suggesting only the stunnel images and zoo. But I wonder similarly what are the use cases for using different Kafka image for Kafka Connect and Kafka Mirror Maker then for Kafka it self.

**Comment by tombentley** [comment]
Well those are defined in different CRs. You'd typically upgrade those to new version of Kafka as part of the overall Kafka upgrade process because they're effectively "just clients".

**Comment by scholzj** [comment]
Oh, sorry. I had more in mind the environment variables in CO deployment. Of course the overrides should stay there.

**Comment by scholzj** [comment]
As for the image overrides in CR ... another thing to consider would be to move it to the `template` configuration section. But that would go a bit aginst the simplification and having only one of them. So I'm fine to just remove the ones you mentioned.

**Comment by DanielShor** [comment]
Hi, I can see that this issue is still open. 
I just upgraded to operator version from 0.22.1 to  0.23.0, but still using kafka 2.7.0. 
By default, the images described above (tls_sidecar for example) are with 2.8.0 tag, where the tag isn't overridable. 
Any plans to support it? 

Thanks!

**Comment by scholzj** [comment]
@DanielShor Can you please explain your actual problem? Because I do not remember what was the original issue here and it is not clear to me what you cannot do.

**Comment by DanielShor** [comment]
Sure! First of all thanks for replying :) 

The issue is that you cannot override the image tag of several images, and the default ones are being used (as defined in [here](https://github.com/strimzi/strimzi-kafka-operator/blob/d7161c6db23d384a4e8f5ec810dbc53418ed4122/packaging/helm-charts/helm3/strimzi-kafka-operator/templates/_kafka_image_map.tpl#L8-L15). 
In our scenario, we just upgraded to operator version to 0.23.0, however we are still using kafka version 2.7.0. Using the new chart, the tls sidecars images being used are with 2.8.0 tag, and we cannot override the value.

**Comment by scholzj** [comment]
So, first of all, you can still override the image in the environment variable. You should be also able to do it in the custom resource. It just does not change the tag based on Kafka version. However, the containers where you cannot do it, they do not use anything from Kafka. The Cruise Control, `stunnel` and Kafka Exporter are exactly the same in all versions of Kafka. So it does not really matter if you use the 2.8.0 or 2.7.0 tag for it. It will always use the same software. These should be ideally a separate images without the Kafka tag - it just saves quite a lot of effort to not have 15 different images as we had in the past but only 5. So that is why it combines several things into one image. But in the case of these, you would get exactly the same quality (for good or bad) with any Kafka tag.

**Comment by DanielShor** [comment]
Thanks for the detailed response! 
We will choose from one of the solutions you have proposed. 

Thanks again.
