### ISSUE TITLE
Adding support for ephemeral storage size

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1505]
In newer Kubernetes versions it is possible to limit the size of the ephemeral storage. As ephemeral storage is one of the things we support currently, we should consider this as an enhancement.

**Comment by katheris** [comment]
Outline of feature request:
When you use Strimzi with Storage type: `ephemeral`, it is using the `emptyDir` volumes. Now `emptyDir` volumes have the option of `sizeLimit` which can define the size of the `emptyDir`.

Idea behind this issue is to add this option to the EphemeralStorage class in the api module and use it when configuring the corresponding emptyDir volume in the cluster operator.

In terms of validation, from the Kubernetes docs: `quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'`, but since a negative sizeLimit would not make sense just match against `^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$` for the new sizeLimit option.

**Comment by katheris** [comment]
This can now be closed

**Comment by ppatierno** [comment]
@katheris I am going to close this one. In general, when I open a PR I use GitHub keywords summarized here https://help.github.com/en/articles/closing-issues-using-keywords so that the related issue is closed "automagically" :-) At least this is my way to avoid to forget to close issues :-P

**Comment by tombentley** [comment]
@ppatierno well if doing a squash merge in github you get to rewrite the commit message yourself which means we as maintainers should be taking responsibility for mentioning there the issues which a PR is fixing.

**Comment by ppatierno** [comment]
@tombentley I am not talking about using keywords in the commit message. It's just about the description in the PR, here on GitHub.

**Comment by tombentley** [comment]
@ppatierno my broader point was that our commit messages are crap, and maintainers should try to make them better. Adding `fixes #nnnn` is just one part of that. Relying on on the PRs for history is problematic because:

1. It's a PITA to have to look up `#nnnn` when doing a `git log` in order to find out what a commit was about.
2. What if github were to disappear?

**Comment by ppatierno** [comment]
@tombentley comments on commit are different things, I was just suggesting to rely on a feature that the current repo system, GitHub, is providing to us. I didn't want to open a broader but valuable discussion here about commit messages. :-)

**Comment by tombentley** [comment]
No, but I did :slightly_smiling_face:. Sorry it's been bothering me for a while, but you're right that this isn't the best forum for this discussion.
