### ISSUE TITLE
Idea: able to configure cluster storage size base on sum of topics retention.bytes 

### ISSUE THREAD

**Issue by dmvolod** [strimzi/strimzi-kafka-operator#1519]
It's an idea to (re)calculate cluster storage size base on sum of topics retention.bytes if this paramater is defined. But default it -1, that means "Unlimited" and could be ignored.

**Comment by scholzj** [comment]
Could you elaborate on it a bit more how would you imagine this to work? The Kafka resource and the topic resources are currently separate - would you just count the size from the KafkaTopic resources?

**Comment by dmvolod** [comment]
Thanks for feedback, @scholzj 
Yes, I know that cluster and topic resources are currently separated, but idea is
1. Have a special property on cluster operator to activate this function or not
2. Trigger a create or appear a new topic with non-default retention.bytes parameters
3. Update Kafka cluster entity with a new storage size in case of extension in current time

**Comment by scholzj** [comment]
Honestly, I think this could work, but I'm not sure whether this would be worth the effort for implementation and maintenance. Especially since the things like storage resizing are AFAIK supported just on few storage providers.

**Comment by scholzj** [comment]
Triaged on 3.3.2022: The idea is not bad. But the implementation would be non-trivial:
* The actual topic can be bigger than the retention.bytes due to the indexes and how the segments are cleaned
* Storage capacity cannot be always increased when new topics are added and shrinking of volumes is not supported
* The storage is split accross the brokers and the disctirbution of partition-replicas is not always uniform accross the cluster
* etc.

So I do not think twe plan to support this doe to the complexity.
