### ISSUE TITLE
intermediate certificate is not in path

### ISSUE THREAD

**Issue by arnitolog** [strimzi/strimzi-kafka-operator#1549]
**Describe the bug**
I created Kafka cluster which uses custom CA (Vault CA). all servers are up and running. However, when I checked servers certificated I found that intermediate certificate is not included as part of the chain. Here is an output of the 
`openssl s_client -showcerts -connect localhost:9093` on any broker pod:

```
---
Certificate chain
 0 s:/O=io.strimzi/CN=kafka-cluster-kafka
   i:/CN=Adhoc Kafka Intermediate
-----BEGIN CERTIFICATE-----
MIIEeTCCA2GgAwIBAgIJAL2OVcwL/qavMA0GCSqGSIb3DQEBCwUAMCMxITAfBgNV
........
2BfhiWMQi5kz1Y7sDgToJmceWFqL7JoQzcEzCqrgbapWCb/coL4M3+PIHv3+
-----END CERTIFICATE-----
---
Server certificate
subject=/O=io.strimzi/CN=kafka-cluster-kafka
issuer=/CN=Adhoc Kafka Intermediate
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1633 bytes and written 415 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 5CB5F649C0B97A20C7C0A8C9ADC89B841AB0B5093F2512C62A20EA4D3262BA76
    Session-ID-ctx:
    Master-Key: 9F160C28338425211BA0D1CB63C19BB63676D33B5D7A0FBBA8211F8F595C07131914F88141D1F5CC3558239BD3BFEBE3
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1555428937
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
```
As a result, the client need to have both root and intermediate certificates in their trust store in order to be able to connect to brokers

**To Reproduce**
1. create a cluster with custom CA
2. exec to any broker pod 
3. execute the command `openssl s_client -showcerts -connect localhost:9093`

**Expected behavior**
Certificate chain contains both server and intermediate certificates. So clients need to have only the root certificate in their trust store.

**Comment by scholzj** [comment]
Yeah, I can confirm this behavior. I will have a look at it.

**Comment by commanderdishwasher** [comment]
+1
Bumped the same.

Issue due to removal of `-chain -CAfile $5` in PR #806 

Now it just creates a keystore with only the cert and no CA.
https://github.com/strimzi/strimzi-kafka-operator/blob/ed3d85c83fa5b8671c0dbf5fc11d096b2adca42a/topic-operator/scripts/tls_prepare_certificates.sh#L21-L23

This is actually a show stopper for integrating Strimzi for our use case (not related to OP).

Patched the image in our repository by reverting the change to above code section and stuff works.

**Comment by commanderdishwasher** [comment]
For truststores, ca.crt should include the chain in the secret according to documentation.
```
kubectl create secret generic kafka-cluster-ca-cert -n d1-infra \
	--from-file=ca.crt=./pki/ca/certs/kafka-chain.pem \
	--dry-run=true -o yaml | kubectl apply -f -
```
But the keytool command in `create_truststore` effectively takes only the first CA in the chain.
The code invoking the function is:
https://github.com/strimzi/strimzi-kafka-operator/blob/ed3d85c83fa5b8671c0dbf5fc11d096b2adca42a/docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh#L26-L30

And it seems for it to behave we need to create several `*.crt` files in the secret for all of them to be loaded to the truststore

**Comment by scholzj** [comment]
I still keep this in mind, just didn't got time to look at it. 

However, I'm not sure whether the broker can handle this also in the truststore or only in the keystore. Is the truststore able to distinguish which certificates are part of the chain and which are the ones who need to sign the client certificates? Because normally you do not want accept clients with the certificates signed by the certificates higher in the chain but just by the last one in the chain.

**Comment by scholzj** [comment]
Looking a bit deeper into this issue:
* When using Strimzi CA, this is not needed since we anyway don't use any intermediate certificates etc.
* However, this can be obviously a problem when using your own CA which might have many levels of different CAs

The problem is that during the replacement of the StrimziCA, at one point there are two CAs:
* The old CA
* The new CA
and the replacement of the old CA for the new CA has to be done in two steps:
1) Add trust to the new CA while still using the old CA singed keys
2) Move to the keys used by the new CA and remove the old CA
and during the step 1 we need to properly identify which CA has to be used as the chain. This was apparently solved by removing the chain from the command which is the easiest solution but causes the problems above.

I think there could be several different solutions:
* We distinguish between the Strimzi CA and custom certificates inside the container and use the `-chain -CAfile $5` option only when custom CA is used
* We improve the handling inside the containers so that we actually know which CA should be used during the first and second restart either by matching subjects or by better naming the certificates etc.

@tombentley You are the expert on the renewal and replacement process - which option do you think is better?

**Comment by tombentley** [comment]
The first option doubles the testing effort, as we have to test both Strimzi CAs and customer CAs, since they behaviour is now different. I think testing this stuff is already quite difficult. So the second option seems to me like it is preferable, depending on how difficult it is to match the subjects. 

I think this issue also highlights that we need ST for the customer CA case if we're to avoid regressing again in the future.

**Comment by scholzj** [comment]
FYI: I finally got to this and opened a PR which should hopefully solve it. Sorry it took so long.
