### ISSUE TITLE
SCRAM-SHA configuration issues

### ISSUE THREAD

**Issue by anu-kr** [strimzi/strimzi-kafka-operator#1571]
I have deployed Strimzi Kafka version on Azure Cloud on Ubuntu VM , runing Openshift Origin (oc v3.9.0+191fece).
While trying to connect to the Kafka borkers via SSL / SCRA-SHA-512 and plaintext  / SCRA-SHA-512 am having issues.

NB : [With Pure TLS based authentication , data could be injected/received from the brokers/topics with the same configuration files]
The POC set up is basic Strimzi cluster (0.11.2) based on the steps provided in https://strimzi.io/quickstarts/okd/. 

Only differece is  we have created an external loadbalancer service, and also set authentication type as scram-sha-512

apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.1.0
    replicas: 1
    listeners:
       external:
        type: loadbalancer
        **tls: true** 
        authentication:
         **type: scram-sha-512**

 and a user type Kafkauser is created
 
 apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  **name: my-user**
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    **type: scram-sha-512**
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: collectd
          patternType: literal
        operation: Read

Inorder to set up the JAAS configuration for SCRA-SHA-512 and am follwing the steps as mentioed in - https://github.com/strimzi/strimzi-kafka-operator/issues/1525
 
Login to the zoo-keeper cluster,  create the jaas.conf with the user name , passwd of the my-user  created (secret revealed) 
 
 tee ./jaas.conf <<EOF
KafkaClient {
org.apache.common.security.scram.ScramLoginModule required
username=**"my-user"**
password="*****";
};
EOF

tee ./jaas1.conf <<EOF
KafkaClient {
org.apache.kafka.common.security.plain.PlainLoginModule  required
    username="my-user"
    password="*******";
};
EOF
tee ./test.properties <<EOF
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
ssl.truststore.location=/tmp/test/truststore.jks
EOF

export KAFKA_OPTS="-Djava.security.auth.login.config=/tmp/test/jaas.conf" 

Q1 , These configuration (/tmp/test/jaas.conf, /tmp/test/test.properties , /tmp/test/truststore.jks) get only temporarily stored in the zoo-keeper-clutser pod. and the pod is remvoing these configuration files after a while .. not sure what exactly is happening  ? 

Q2 , With the  configurations done in above step ,  if i try to write onto the broker - using collectd the follwing error is reported "write_kafka plugin: cannot create kafka handle." The following configuation are used for the producer 

        #Property "security.protocol" "SASL_SSL"  (first attempt)
        #Property "security.protocol" "SASL_PLAINTEXT" (second attempt)
        #Property "sasl.mechanisms" "SCRAM-SHA-512"

Q3 , There was on option specified to directly push the JAAS configuration directly onto the properties file 
(Tried to add these properties onto the server.properterties of kafka broker) . Am unable to do this since the file is protected.

	security.protocol=SASL_SSL
	sasl.mechanism=SCRAM-SHA-512
	ssl.truststore.location=/tmp/test/truststore.jks
	ssl.truststore.password=123456
	sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=my-user password=*****;

Is there any specific user that needs to be logged on as to the  pods  for doing these steps ?Am not sure what is that am missing ? is there any documents or examples for the SASL_SSL broker configuration  ? Could you please help / comment ?

**Comment by scholzj** [comment]
Q1: You should not be doing this in the Zookeeper pod. You should do it locally if you want to use the SCRAM-SHA-512 authentication over load-balancers. The only thing done in the Zookeeper pod in #1525 was the `./kafka-configs.sh` command. And you should not really need this command anyway. The user in Zookeeper should be created by the User Operator from the `KAfkaUser` resource.

Q2: I have no experience with collectd. I do not think I can help with that. We should get this working with the Kafka console clients to confirm it works. Then you can maybe replicate the configuration in collectd.

Q3: This is a configuration you should use with the Kafka clients (the Java ones). Not with Kafka broker. You can take this file and use it with the `bin/kafka-console-consumer.sh` or `bin/kafka-console-producer.sh` scripts which are part of the Kafka ZIP/TAR.GZ file which you can download from Apache Kafka website.

**Comment by shilpa2788** [comment]
hi, As per the reply i have tried implementing the same. Following are tried
1.  Created a user  "my-user" as entity-user and could see the secret got generated under resources 
2. then created a load balancer service using listner as external, tls to false and authentication type as scram-sha-512. I was planning to implement SASL_PLAINTEXT without SSL
    listeners:
       external:
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512

3. As per Strimzi documentation we dont need to explicitly mention to create jaas or server (zookeper, kafka broker) properties as strimzi does it all.

4. With the point 3 ,  started with the creation of a client producer using bin/kafka-console-consumer.sh , by trying to provide the producer.config as the file created in my local
** producer.properties as below **

security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=my-user password=**********;

the command tried from my prompt as follows 

"oc run kafka-producer -ti --image=strimzi/kafka:0.11.2-kafka-2.1.0 --rm=true --restart=Never -- bin/kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap:9092 --topic test --producer.config=/home/kafkauser/producer.properties"

am getting the filenotfound
  java.nio.file.NoSuchFileException: producer.properties
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)

Please let me know if i miss any steps and if it is the way in which a client can be invoked?

**Comment by tombentley** [comment]
From your description it seems that your `producer.properties` is not present in the image you use with `oc run`. The `--producer.config=/home/kafkauser/producer.properties` is referring to a file within the container, not your local filesystem.

**Comment by shilpa2788** [comment]
In that case, is there any recommendations for the same to be applied to producer running outside the cluster ? any steps to be followed?

**Comment by tombentley** [comment]
I guess you can either use your own docker image (possibly based on `strimzi/kafka:0.11.2-kafka-2.1.0`), or write the `producer.properties` within the container by doing something like: 

```
oc run kafka-producer -ti --image=strimzi/kafka:0.11.2-kafka-2.1.0 --rm=true --restart=Never -- /bin/bash -c "cat >/tmp/producer.properties <<EOF 
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=my-user password=**********;
EOF
bin/kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap:9092 --topic test --producer.config=/tmp/producer.properties
"
```

Note the file is written in `/tmp` in this case because the uid running inside the container can't write to `/home/kafkauser`

**Comment by shilpa2788** [comment]
Yes, thanks for that, have tried the same. Have few doubts here with respect to strimzi specific implementation
1. while we do a login directly inside the pod, under tmp there are strimzi properties, there i could see ssl as well enabled, i guess its for replication. PFB the snapshot of listeners and advertised listeners

# Listeners
listeners=REPLICATION://0.0.0.0:9091,EXTERNAL://0.0.0.0:9094
advertised.listeners=REPLICATION://my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc.cluster.local:9091,EXTERNAL://172.29.107.87:9094
listener.security.protocol.map=REPLICATION:SSL,EXTERNAL:SASL_PLAINTEXT
inter.broker.listener.name=REPLICATION
hence while i create a producer or consumer client , should i use the IP and hostname of external service?
Here is the snapshot of services of the cluster
root@kafkavm:/home/kafkauser# oc get services
NAME                                  TYPE           CLUSTER-IP       EXTERNAL-IP                     PORT(S)                      AGE
my-cluster-kafka-0                    LoadBalancer   172.30.42.199    172.29.107.87,172.29.107.87     9094:31188/TCP               5h
my-cluster-kafka-bootstrap            ClusterIP      172.30.25.8      <none>                          9091/TCP                     6h
my-cluster-kafka-brokers              ClusterIP      None             <none>                          9091/TCP                     6h
my-cluster-kafka-external-bootstrap   LoadBalancer   172.30.10.49     172.29.170.132,172.29.170.132   9094:31252/TCP               5h
my-cluster-zookeeper-client           ClusterIP      172.30.159.108   <none>                          2181/TCP                     6h
my-cluster-zookeeper-nodes            ClusterIP      None             <none>                          2181/TCP,2888/TCP,3888/TCP

i tried the above with external loadbalancer ip as well but am getting a different error
[2019-05-14 09:41:37,019] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 8 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

please let me know if i miss any steps

**Comment by scholzj** [comment]
You should share the whole commands / logs of what you are doing. `Error while fetching metadata with correlation id 8 : {test=LEADER_NOT_AVAILABLE}` can mean a lot of things - for example that the topic is still creating or cannot be created because of replication settings etc.

**Comment by shilpa2788** [comment]
Yes now i manually created a topic using topic.sh with replication factor and partitions as 1 and then gave used that topic in producer and consumer, that worked 

One quick question here , i tried all these manually on a command line. Is there any yaml configurations available so that we can automate the consumer addition(we are planning this for many consumer clients and one producer client)

**Comment by scholzj** [comment]
You can use YAMLs to create the topics and users (including ACLs), but not much else what would be related to the consumers/producers. Could you clarify a bit more what exactly do you mean? It is not completely clear to me.

**Comment by shilpa2788** [comment]
Yes sure.
Now i have created a producer and a consumer client using properties of jaas and security via command line. If this can go inside a yaml it would be great. I have deployment yaml for producer and consumer client for TLS, similarly if we have any thing available for SCRAM-SHA-512, where instead of TLS certificates we have options to provide the producer / consumer properties

**Comment by scholzj** [comment]
I'm still not sure I fully understand what exactly do you have in mind - you mean to have the JAAS configuration file generated in the secret with the password?

**Comment by shilpa2788** [comment]
Yes to provide the jaas config and properties in a yaml

**Comment by scholzj** [comment]
The properties file does IMHO not make sense. Because everyone will want to use different properties file. So I do not think that would be any useful. 

The JAAS config file should be more feasible since that is pretty much the same for everyone and nobody has any reasons to change it.

**Comment by shilpa2788** [comment]
Ok. Sorry if confused. Need a bit more clarification please. Hence elaborating a bit. 

For TLS encryption Strimzi provides an option to get the certificates in yaml using the "env" struct 
For instance i have created a producer pod using kind _Deployment_ which gets the certificate using the below constructs
    spec:
     ####
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
######

Similarly could you please suggest for SCRAM-SHA-512, if strimzi kafka accepts the below config under env construct of yaml rather than providing it on command line via bin/bash (as shared by tombentley)
Here we are planning to create many producers and consumers. Hence this would be of great help.

_security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=my-user password=**********;_

**Comment by scholzj** [comment]
The TLS certificate doesn't correspond to the config file but just to the password. 

When you use the TLS certificate with a Java client, you can mount it from the secret, but you still have to create your own properties file with something like this:

```ini
security.protocol=SSL
ssl.truststore.location=/tmp/truststore
ssl.truststore.password=123456
```

When you use SCRAM-SHA, you can mount the password from the secret into the pod and generate a config like this:

```ini
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=my-user password=**********;
```

So that is similar in both cases. Normally, generating the configuration is not complicated because most applications are not using the console consumer or produce. They are written directly in Java where you do not use some file but instead you generate the configuration in the properties object. See [this class](https://github.com/strimzi/client-examples/blob/master/hello-world-producer/src/main/java/KafkaProducerConfig.java) as example.

Moreover, the file would anyway often need to be change afterwards because you might need to configure additional things such as reliability, (de)serializers etc.

**Comment by shilpa2788** [comment]
Ok.. Thanks alot for the reference . Instead of writing Java client class i was planning to do it via  Deployment yaml.  In our case we have collectd as a producer and we need to configure collectd to fetch jaas properties while publishing the data.

1. I hope i can enable TLS + SCRAM as two listeners and as a client we can either use TLS or SCRAM-SHA-512. eg (one producer ( _collectd_ ) using TLS encryption and another producer (Java Client or a Nifi producer )using SCRAM-SHA-512?

2. Also can we enable topic level security in strimzi?- where one topic can only be used by one user (eg: **_topic1_** for enity-user **_user1_** and topic2 for entity-user **_user2_**.
So that **_user2_** cannot write/read from **_topic1_**

**Comment by scholzj** [comment]
I'm not completely sure how does Collectd integrate with Kafka. Since it is AFAIK not written in Java it sounds strange that it would use the Java console producer which takes the properties file. But I do not really have any experience with Collectd. Most applications using Kafka will end up either having custom code or will have some proprietary configuration. 

The easiest way to handle this for you is to have some simple shell script which will be started when your container starts which will generate the configuration which corresponds to whatever you use.

**Comment by shilpa2788** [comment]
ok .. Fine wll try that. 
Also could you please confirm if i can enable TLS + SCRAM as two external listeners and one client using TLS and another using SCRAM-SHA-512

**Comment by scholzj** [comment]
There is currently only one external listener - you can enable there TLS encryption and SCRAM together as they do each a bit different task. But you cannot have two external listeners. I think there is already some issue for it.

**Comment by shilpa2788** [comment]
Ok Sure. Thank you. I have also requested with collectd team on SCRAM.
