### ISSUE TITLE
[Question] Several listerners

### ISSUE THREAD

**Issue by AldusLorde** [strimzi/strimzi-kafka-operator#1614]
Hi, can Strimzi support several external listeners(I need to use both TLS and no-TLS connections)?

**Comment by scholzj** [comment]
Hi @AldusLorde ... this is unfortunately not possible right now. There is always only one. But this is not the first time this was raised, so we can keep this issue open to track it.

**Comment by denniseffing** [comment]
@scholzj Are there any updates regarding this issue? We also have the need to configure multiple external listeners.

**Comment by scholzj** [comment]
I'm still planning it, but still didn't got to it. Sorry.

**Comment by denniseffing** [comment]
Is there more to it than changing the CRD and adjusting the code in the link below so that it iterates over the external listener array, adding each entry to `listeners`?

https://github.com/strimzi/strimzi-kafka-operator/blob/5f0bc11037c56a84fe421ccb60156443663c9213/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java#L189-L248

**Comment by scholzj** [comment]
I think there is more to it because right now there are three different listeners which different configuration each. To make this feature work, you need to have some generic listener configuration and you need to treat it accordingly in the code. Currently, since we have 3 listeners with their own unique configuration, they have each their own code paths. 

But the CRD change on its own is unique and non-trivial as well since you need to think about the back-wards compatibility, migration etc.

**Comment by pantaoran** [comment]
I'm running Strimzi 0.22 right now and have two external listeners running with no problem (one TLS auth, one Scram-Sha auth).
Is it possible that this is now solved and could be closed?
