### ISSUE TITLE
[Question] Deploy kafka connect in environment external to k8s cluster?

### ISSUE THREAD

**Issue by snimmagadda1** [strimzi/strimzi-kafka-operator#1705]
Does strimzi support an architecture in which a kafka connect source is deployed outside of the k8s cluster that kafka is deployed in? 

I.E if I have a database external to my cluster, can I deploy a connector that will send CDC (change data capture) to the kafka cluster?

**Comment by scholzj** [comment]
I think that in most cases this should be possible. Most of the connectors are AFAIK connecting to the source over TCP. So they can connect everywhere as long as the TCP address is reachable. There is a minority of connectors which might work differently and where this might not work. But for most of them this should.

**Comment by snimmagadda1** [comment]
Cool! thanks for the speedy reply that was along the lines of my thinking ... specifically we're looking into Debezium. It would be slick if you could run the [Debezium docker image](https://github.com/debezium/docker-images/tree/master/connect/0.10) in a docker runtime alongside, for example, a MySQL server for cases where the MySQL DB is deployed externally and not available to connect to via the web.... Any ideas if something like this has been done?

**Comment by scholzj** [comment]
Debezium should AFAIK connect over TCP. So the database server can be everywhere. Hoeever, you cannot use the Debezium images in Strimzi, since Strimzi requires its own images with its own startup scripts etc. Please have a look [here](https://strimzi.io/docs/latest/full.html#using-kafka-connect-with-plug-ins-str) at how to add plugins such as Debezium to the Strimzi images.
