### ISSUE TITLE
Are there any Documentation to Install Kafka on Kubernetes with Strimzi that is more beginner friendly?

### ISSUE THREAD

**Issue by oawties0412** [strimzi/strimzi-kafka-operator#2012]
Hello, 

We have here our kubernetes cluster with 40 microservices running inside one namespace, I was assigned to do installations on Kafka and I saw this strimzi project but as I wandered around the documentation in the official site, I can't seem to understand where to start. On what command should I run first.... stuff like that. 

Can you share me guys a more beginner friendly installation using Strimzi? 

Thank you so much!

**Comment by oawties0412** [comment]
Should I install the Cluster Operator inside the namespace where the microservices are or inside another namespace?

**Comment by scholzj** [comment]
Hi,

We have several resources which should hopefully get you started:
* Quick start guide with Minikube (should work fine in regular Kubernetes clusters as well): https://strimzi.io/quickstarts/minikube/
* The slightly more details getting started guide: https://strimzi.io/docs/latest/#getting-started-str

With Strimzi, you can install the operator and the Kafka cluster into different namespaces. I think that most users decide that mostly based on security considerations. Having the operator in different namespace can make it easy for you to separate access tot he operator (which needs a lot of different RBAC proviledges) and to the Kafka cluster which it self is lot less proviledged. The same can be applied to the Kafka cluster it self and the clients connecting to it.

However, assuming you first start playing with it in some development environment and not in production, it might be easier to start with just everything in the single namespace since that means less configuration.

Hope this helps a bit.

**Comment by oawties0412** [comment]
Hi @scholzj 

Thank you for giving me a path to follow. I do have one more question. 

Will there be a problem if I install within my existing Kubernetes cluster? And how can my microservices communicate with Kafka? 

Thank you so much.

**Comment by scholzj** [comment]
No, installing into an existing cluster is of course fine.

The microservices should normally use some (depending on their programming language) Kafka client to connect. Depending on your security requirements you will then point the Kafka client to one of the services created by the operator (the one called `<cluster-name>-kafka-bootstrap`) either on port 9092 for plaintext unencrypted connections or 9093 for TLS encrypted connections.

**Comment by oawties0412** [comment]
I see, are there any tutorials on how to connect a microservice to kafka?

**Comment by oawties0412** [comment]
Thank you so much @scholzj. Hope our team here can set this up with no problem.

**Comment by scholzj** [comment]
> I see, are there any tutorials on how to connect a microservice to kafka?

I guess it depends on the language and client you use. In Java you could start with the [Consumer, Producer or Streams APIs](http://kafka.apache.org/documentation/#api). Other languages would have different APIs.

Strimzi has also a [HTTP Bridge](https://strimzi.io/docs/master/full.html#assembly-kafka-bridge-quickstart-str), but normally using the Kafka protocol directly is much better.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
