### ISSUE TITLE
[Bug] Can't create custom configuration ConfigMaps with the same name as default ConfigMaps

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#2029]
**Describe the bug**
When creating a custom configuration ConfigMap for Kafka or Zookeeper with the same name as the default configuration ConfigMap for Kafka or Zookeeper, the Cluster Operator will overwrite the custom configuration ConfigMap with the default.

**To Reproduce**
1. `oc apply -f install/cluster-operator/`
2. `oc apply -f examples/kafka/kafka-ephemeral`
3.  Create a custom configuration ConfigMap:
`oc apply -f custom-config-map.yaml`
```
# custom-config-map.yaml
apiVersion: v1
data:
  log4j.properties: >
    corresponding kubernetes/openshift resource.
   log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
   log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
   log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} %p %m (%c) [%t]%n
   zookeeper.root.logger=OFF
   log4j.rootLogger=${zookeeper.root.logger}, CONSOLE
kind: ConfigMap
metadata:
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
  name: my-cluster-zookeeper-config
  namespace: myproject
```
Update Kafka custom resource with logging field, pointing to custom configuration ConfigMap
`oc edit Kafka my-cluster`
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
...
spec:
...
  zookeeper:
    logging:
      name: my-cluster-zookeeper-config
      type: external

```
4. Wait for rolling update ( or kill CO pod to trigger the update)
3. View Zookeeper logs and custom configuration ConfigMap for Zookeeper
`oc logs  my-cluster-zookeeper-0 -c zookeeper -f` will show the logging level as `INFO` even though we set it as `OFF`.
`oc get cm my-cluster-zookeeper-config -o yaml` will show the default configuration ConfigMap instead of the new custom configuration ConfigMap.

**Expected behavior**
After updating the Kafka or Zookeeper configuration ConfigMap with a custom configuration ConfigMap, the custom configuration ConfigMap persists after rolling restart.

**Environment (please complete the following information):**
 - Strimzi version: 0.13.0
 - Installation method: YAML files
 - Kubernetes cluster: OpenShift 3.9
 - Infrastructure: oc cluster up

**Comment by stanlyDoge** [comment]
I think the issue is in the `io.strimzi.operator.common.operator.resource.ConfigMapOperator#internalPatch`. What is happening there:
1. We have a CM
2. We change it
3. CO starts rolling update and starts comparing of `current` and `desired` CM's
4. Because we manually overwrite the "current" it says it is the same as the `desired` and the rolling update is not started

I am not sure we can fix it by looking at `resourceVersion` bc this map is recreated every reconciliation when using `inline` logging. Any idea?

**Comment by scholzj** [comment]
I think the main issue is that we should either not overwrite it if it is
user supplied config map, (but since we use it also for metrics I guess
that is not an option). Or we should make it clear in docs that users
should use different name.

**Comment by stanlyDoge** [comment]
I cannot see (that does not mean there is not) a way how to check whether we are overwriting a _custom_ config map. Yes, we can use `configMapOperations.get(...)` to check whether it is already present. 
But when this CM is created by CO, the same check will say it is already created and thus it will be never updated :( From my POV documenting that `$cluster-$resource-config` names for the CM should not be used because its content is going to be overwritten is a reasonable way how to "fix" this.

**Comment by scholzj** [comment]
The labels should determine that. A CM created without the labels should be user suplied the CM with the labels should be ours.

However the initial problem remains ... if the CM is not used by the CO exclusively for the log configuration, you cannot do this because it would block the metrics etc.

**Comment by jrivers96** [comment]
1. kubectl -n strimzi-cluster replace -f brokenconfigmap.yaml
2. Execute Roll the cluster
3. The broker doesn't start because of "brokenconfigmal.yaml"
4. kubectl -n strimzi-cluster replace -f fixedconfigmap.yaml
5. The broker still doesn't start because of "brokenconfigmal.yaml" after manual restart 

Steps that resolved the issue. 
1. Canceled the roll of the cluster. `kubectl  annotate statefulset kafka-cluster-kafka strimzi.io/manual-rolling-update=true`
2. Renamed name within fixedconfigmap.yaml to `metrics-v2`
3. Changed name of configmap in kafka configuration to `metrics-v2`

**Comment by scholzj** [comment]
Well, if you think it is a bug, you should start a new issue since this is not related to it for sure. The changes to the metrics configuration  In the CM do not roll the pods, so I'm not sure I understand how does it break.

**Comment by scholzj** [comment]
Triaged on 21st June: The original issue seems to be caused by the user by using a wrong config map. I do not think there is much we can do about it. @PaulRMellor will double check the docs if it is sufficiently described there.

The second part referenced by @jrivers96 seems like a different bug to me. If that is still a problem today, we should fix it. Please open a separate issue for it in that case. Thanks.

**Comment by PaulRMellor** [comment]
We don't say anything in the docs about custom configmaps requiring unique names. We can update the docs to make this clear.

**Comment by scholzj** [comment]
Yeah, sure. Why not.
