### ISSUE TITLE
[Enhancement] Being able to limit the scope of the operator to a single namespace

### ISSUE THREAD

**Issue by Smana** [strimzi/strimzi-kafka-operator#2046]
**Is your feature request related to a problem? Please describe.**
Currently the helm chart deploys "clusterroles" with wide permissions on all the namespaces.
For security reasons we may want to bound the operator to a single namespace.

**Describe the solution you'd like**
Instead of deploying clusterroles would that be possible to create roles that limit the permissions to the namespace where the operator is installed ?

**Describe alternatives you've considered**
For instance we could use a boolean value `clusterScoped`, the same as the [NATS Operator](https://github.com/nats-io/nats-operator/blob/master/helm/nats-operator/values.yaml#L10)

**Comment by scholzj** [comment]
Strimzi doesn't use Cluster Roles because of cluster-wide access. In order to run Kafka reliably, some features such as rackawareness require us to read AZs from node labels. Since nodes are cluster wide resource, we need ClusterRole and ClusterRoleBinding to be able to use it. Similarly, for exosing Kafka cluster using node ports, we need to be able to read the nodes as well.

So basically, the default installation of Strimzi is limited to only single namespace. The CLusterRoles and ClusterRoleBindings are needed for actual features which NATS probably does not have. You can manually change these and it should work fine as long as you don't trigger the affected functionality. But since these features ar eimportant, we do not plan to implement such changes to the official Helm Chart.
