### ISSUE TITLE
KafkaTopic CR does not get ownerReference to Kafka CR

### ISSUE THREAD

**Issue by aceeric** [strimzi/strimzi-kafka-operator#2074]
We are deploying Strimzi as part of our application - and when our app comes up it creates numerous Kafka Topics. The Kafka operator creates KafkaTopic CRs for each topic as expected. When we tear down the environment, we delete the Kafka CR, but since the KafkaTopic CRs don't have their ownerReference set, the KafkaTopic CRs hang around. KafkaTopic  is a light weight CR so it doesn't appear to cause any problems but I think it would be nice if the KafkaTopics were children of the Kafka CR so removal of the Kafka CR also caused removal of the KafkaTopic CRs.

**Comment by scholzj** [comment]
I think this is an interesting question. I can see how the Kafka Topic created by the TO should have the owner reference to the Kafka CR. However:
* The KafkaTopics created by users should not have the owner reference set by the TO. User should set it to whatever they think the topic belongs to (and there are users using this to delete the topics witht heir applications). This makes it a bit hard in reconciliation to not override the user provided owner reference since over the time it might get a bit blury who created what.
* TO can watch for KafkaTopics accross namespaces. But AFAIK owner references do not work accross namespaces. So we would need to handle this special case.

**Comment by aceeric** [comment]
I agree: if a person creates a KafkaTopic CR with the intent that the TO will create the topic in Kafka - it is up to the user to assign ownership. This particular example (cited) is a backend service creating topics directly in Kafka, and the TO performing the reconciliation into OpenShift.

**Comment by scholzj** [comment]
Triaged on 7th July 2022: Should be closed. The owner reference is supproted only within the same namespace. It might be also hard to deal with existing topci where it is not clear who created them.
