### ISSUE TITLE
[Question] Why are JDK 11 flavoured Docker images published to Docker Hub?

### ISSUE THREAD

**Issue by carlosjgp** [strimzi/strimzi-kafka-operator#2102]
I can see in one of the readme files on this that you mention that users can [customise their Strimzi Docker images to use JDK 11](https://github.com/strimzi/strimzi-kafka-operator/blob/master/HACKING.md) and I was wondering if is there is a reason for not publishing them yourselves

I'm asking this from my Kubernetes developer point of view since it's a little bit more difficult to manage the memory resources from JDK 8 apps and will not allow using some new Kubernetes features las Vertical Pod Autoscaler

Thanks

**Comment by carlosjgp** [comment]
Will you accept a PR to publish the JDK 11 images?

**Comment by scholzj** [comment]
We use currently Travis as the CI and building the Java 11 images would not fit into the Travis time limits. I'm also reluctant to build two sets of images -> two sets of images means twice much testing to ensure the quality.But maybe it is the time to have a discussion about moving from Java 8 to Java 11.

I'm not sure I understand the details about JDK8 and scaling images - could you share more details about the differences and how does it (or doesn't) work with the vertical pod autoscaler? I'm not sure Vertical pod autoscaler would deal well with Strimzi ragardless the Java, but I never played with it TBH.

**Comment by carlosjgp** [comment]
In the particular case when using JDK 8 you have to specify a value minimum and maximum amount of memory which is normally the same (or the same proportion) as the Kubernetes resource memory limits
https://strimzi.io/docs/latest/#type-JvmOptions-reference

After some reading looks like the ported back the new flags for container compatibility from JDK 11 to JDK 8 
https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html
https://blog.softwaremill.com/docker-support-in-new-java-8-finally-fd595df0ca54

But to be fair it seems like CentOS 7, Strimzi base image is using a quite up to date version of the JDK so the mentioned patch is already included the new "RAM percentage" flags allows an easier configuration and the usage of the Vertical Pod Autoscaler
http://mirror.centos.org/centos/7/os/x86_64/Packages/?C=S;O=D
https://adoptopenjdk.net/upstream.html

I haven't tried the VPA on a java app either so I'm not sure how happy it will be

Thanks for the quick response

**Comment by scholzj** [comment]
Well, one thing special about Kafka is that its performance depend a lot on the disk page cache. So actually what I normally recommend is to configure the JVM `-Xmx` option in a way that it doesn't take the whole memory request and leaves some memeory reserved for the disk cache (e.g. you reserve 32GB of RAM in Kubernetes request, but configure the -Xmx to use only 8GB out of it). So I guess in these cases you will still need to set it anyway.

The other reason why I think Java 11 might help would be TLS performance. AFAIK there are a lot of improvements with 11 compared to 8 and while some part of Strimzi TLS is done by Stunnel sidecars, lot of it is in Java as well. So that might be another reason to move to 11.
