### ISSUE TITLE
When using Node Ports for external access the InternalIP is used over the Hostname

### ISSUE THREAD

**Issue by chrispatmore** [strimzi/strimzi-kafka-operator#2109]
**Describe the bug**
When you enable external access through Node Ports the address of the node is supposed to be used in the following documented priority:
1. ExternalDNS
2. ExternalIP
3. Hostname
4. InternalDNS
5. InternalIP

However the InternalIP address is used over the Hostname when no other addresses are present

**To Reproduce**
Install strimzi with the external address type of nodeport with kafka on nodes which only have InternalIP and Hostname set. Do not override the advertisedHosts, an example configuration would be:
```
listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
```

The advertised listeners for the brokers will use the InternalIP address not the Hostname

**Expected behavior**
The advertised listener address would be the hostname of the node

**Environment (please complete the following information):**
 - Strimzi version: master
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.14.6
 - Infrastructure: Minikube

**Additional context**
The problem code is here https://github.com/strimzi/strimzi-kafka-operator/blob/0d1f23ffa3d2801f536b6b1b3f44554f3763a536/kafka-init/src/main/java/io/strimzi/kafka/init/InitWriter.java#L155

**Comment by scholzj** [comment]
I think this is intentional and from my experience hostname is too often something like `localhost` while the internalIP / DNS is often valid. So my guess is this change breaks it for someone else. What we should do is to let the user select which of these should be used with a priority so that this can work for everyone.

**Comment by chrispatmore** [comment]
That makes sense. Would the intention be to allow the user to specify their order preference for the five address types in the kafka CR? Additionally is it worth updating the documentation to reflect the actual ordering in the meantime?

**Comment by scholzj** [comment]
If the otder is wrong there, we should definitely update it. 

I didn't thought about it in detail - providing your own priority list will be a bit more complicated and I'm not sure it has a value because when you configure it, you probably already know which one you migth want to use, right? E.g. you already know that your ExternalIP and ExternalDNS do not work or are not set and you want to use the hostname. So for me it seemed like specifying the one which should be used should be OK. But what do you think? Would the priority list be useful for you?

Also, if you want to work on a PR to implement this, I can help you and guide to where what needs to be changed etc. ;-)

**Comment by scholzj** [comment]
> use Hostname from the node

Well, for me, this would be sufficient ... as long as it gives the offer to also select from all the options and not just select the `Hostname` since there will be obviously other users with preference for other address ;-).
