### ISSUE TITLE
Kafka Topic is stated in namespace "A", how can i reach that topic from namespace "B" [Question] ...

### ISSUE THREAD

**Issue by bakihyt** [strimzi/strimzi-kafka-operator#2142]
Hi All,

In our private openshift environment, we are using strimzi kafka distribution but it is getting hard to manage day by day because of we have setup strimzi kafka  in each individual project namespaces

Our plan is setup kafka strimzi in one namespace and also there may be different topics for different purposes then provide access for different projects under different namespaces. Our goal is providing kafka as a service for other projects in our openshift platform.

Could you please tell me how we can do it ? Is there any instruction set to do it step by step ?

According to my research kafka can not be reachable from different or outside of that namespaces... ıs that right ?

**Comment by scholzj** [comment]
It depends on how is your OpenShift cluster configured. If you are using the multitenant SDN, you would need to set the namespace where you have the Kafka cluster as global so that it is shared and can be accessed from all other projects. You can also use the network policies SDN which leaves it up to you to configure the network policies to (not) isolate the namespaces. Once you enable the network traffic, you can easily access it across namespaces by just using the long DNS name (e.g. `my-cluster-kafka-bootstrap.kafka-namespace.svc`). If you cannot do that on the OpenShift level with the SDN, you can connect to Kafka through the _outside_ (e.g. through node ports, loadbalancers or routes). But that is normally slower (and can increase costs significantly for example if you run in AWS).

Once you address that, you migth need to deal with how to manage the users and topics. The user and topic operators watch only one namespace for the custom resources. So you will need to have an workflow to deal with that. So far I heard users dealing with it using custom operators, scripts or GitHub PRs and GitOps. I think this is a bit dependent organization by organization.

**Comment by bakihyt** [comment]
Hi @scholzj ,

Thank you for your quick response.

As you mentioned, we changed our configuration and disable isolation for some specific namespaces. After this change, it seems that clients can reach bootstrap server on 9092 port but also i have seen some logs in client log files.

Here are some example ;

`2019-10-31 15:40:09.780 WARN 1 --- [ntainer#3-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator : [Consumer clientId=XXXXMessageCommands-0, groupId=group-XXXXX-message-commands-b97f7ea3-cb71-4cc0-8895-930dc7035c74] Asynchronous auto-commit of offsets {simulator-XXXXXX-commands-1=OffsetAndMetadata{offset=5, metadata=''}, XXXXX-message-commands-2=OffsetAndMetadata{offset=4, metadata=''}, simulator-message-commands-0=OffsetAndMetadata{offset=6, metadata=''}} failed: Unexpected error in commit: The server experienced an unexpected error when processing the request 
2019-10-31 15:40:10.391 ERROR 1 --- [ntainer#2-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator : [Consumer clientId=XXXXXXManagementEvents-0, groupId=group-simulator-management-events-7c550149-ef07-4dee-91c8-1c9e432258d9] Offset commit failed on partition simulator-management-events-1 at offset 11: The server experienced an unexpected error when processing the request `

ı checked from google but i could not address exact reason.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
