### ISSUE TITLE
[Doc] Issue with default files for alert manager configuration

### ISSUE THREAD

**Issue by agrajm** [strimzi/strimzi-kafka-operator#2291]
**Suggestion / Problem**
The alert manager configuration example suggest to use `alert-manager-config.yaml` to create a `secret` for alertmanager. Unfortunately that will not work and the config file that is used to create a secret must always be named as `alertmanager.yaml` 

**Documentation Link**
The current doc link - https://strimzi.io/docs/master/#proc-metrics-deploying-prometheus-alertmanager-str that uses the `alert-manager-config.yaml` and the command to create secret should change to
```
kubectl create secret generic alertmanager-alertmanager --from-file=alertmanager.yaml
```
Please see https://github.com/coreos/prometheus-operator/issues/2902 for details

**Comment by scholzj** [comment]
Thanks for raising this. I will get someone to take a look at this.

**Comment by ppatierno** [comment]
I don't think we need to rename the YAML file containing the configuration even because `alert-manager-config.yaml` is more understandable than just `alertmanager.yaml`.
I think that the best option could be using the creation with:

```
--from-file=alertmanager.yaml=alert-manager-config.yaml
```
so specifying the key as `alertmanager.yaml` in the Secret and it should work.
I will give it a try.

**Comment by ppatierno** [comment]
@agrajm I opened a PR for that
