### ISSUE TITLE
When upgrading the version of  strimzi, how to prevent the restart of the cluster?

### ISSUE THREAD

**Issue by EresZX** [strimzi/strimzi-kafka-operator#2307]
I need to upgrade the version of strimzi from 0.12.0 to 0.14.0, but I must update the STRIMZI_DEFAULT_KAFKA_INIT_IMAGE. 

I read the document, some image properties such as Kafka.spec.kafka, Kafka.spec.kafka.tlsSidecar are provided to configure the container image. Howerver, there is no property to override STRIMZI_DEFAULT_KAFKA_INIT_IMAGE. I think if I want to prevent the restart of the kafka pod, I have to use the image properties to override the container image instaed of updating in the deployment yaml of operation. Then, how could I solve the problem of   STRIMZI_DEFAULT_KAFKA_INIT_IMAGE override?

**Comment by scholzj** [comment]
In the Kafka CR, there should a field `brokerRackInitImage` (https://strimzi.io/docs/latest/full.html#type-KafkaClusterSpec-reference) which should do it. It should be in `Kafka.spec.kafka`. TBH, it is a long time since I used it, but I would expect it to work. You can also override it in the cluster operator in the `STRIMZI_DEFAULT_KAFKA_INIT_IMAGE` environment variable which would overwrite it for all Kafka clusters (you need to change it before applying the 0.14.0 installation files). Hope this helps.

Out of curiosity, why do you need your custom init image?

**Comment by EresZX** [comment]
I'v mistaken the version. I want to upgrade the version of strimzi from 0.11.0 to 0.14.0. However, in 0.11.0 verision, STRIMZI_DEFAULT_KAFKA_INIT_IMAGE is set to hub.oa.com/tendata/kafka-init:0.11.1. Then, in 0.14.0 version, STRIMZI_DEFAULT_KAFKA_INIT_IMAGE is set to strimzi/kafka:0.14.0-kafka-2.3.0. If I use the previous image in 0.11.0 version, the pods of kafka cluster would fail to run. Besides，I modify the source code and build the new images of kafka and operator. I have to use the new images.

**Comment by scholzj** [comment]
TBH I do not know out of my head the changes to the init image between 0.11 and 0.14. So I'm not sure if there were any changes and if the older image would still work or not. In this I think you will have to, because it looks like we did some changes to the images between these releases. But you upgrade the operator by applying the files of the new one - so you can edit the files before the upgrade and change the `STRIMZI_DEFAULT_KAFKA_INIT_IMAGE` variable according to your needs(I think the default there should be `strimzi/operator:0.14.0`).

**Comment by EresZX** [comment]
It's right. However, there are some clusters deployed by 0.11.0. When I upgrade, I can't use the whole configuration in strimzi 0.14.0. If I use the STRIMZI_DEFAULT_KAFKA_INIT_IMAGE:strimzi/operator:0.14.0, the pod of old kafka cluster will reastart when I upgrade, this may affect the online business. Then I use the strimzi 0.14.0 to deploy the new cluster. I hope that the upgrade would not affect the old cluster.

**Comment by scholzj** [comment]
Sorry, I'm not sure I understand the last part. If you have multiple clusters managed by the same operator they will be anyway updated at the same time.

**Comment by EresZX** [comment]
The old cluster was deployed by the 0.11.0. I only change the image in `strimzi-cluster-operator` 
[configuration.txt](https://github.com/strimzi/strimzi-kafka-operator/files/3955726/configuration.txt)
and use the image of the modified operator. Using the strimzi/operator:0.14.0 directly , the old cluster will restart, Then, I modify the source code of operator and let it to ignore the change between two versions. I modify  `StatefulSetDiff.java` 
(`cluster-operator/src/main/java/io/strimzi/operator/cluster/resource`). I add the path which will change bettween upgrade to `IGNORABLE_PATHS`. Then, I upgrade strimzi version and it will not affect the old cluster.

**Comment by scholzj** [comment]
I'm not sure you can do this easily just by the StatefulSetDiff. That could work for few minutes. But it will still update the stateful set and any pod failure could introduce problems. So I'm not sure this is so easy. I think you should make sure to test this properly before you try it in production.

**Comment by EresZX** [comment]
Thank you very much. Could you give me some suggestions to prevent the restart of the old cluster or reduce the affect to the old cluster?

**Comment by scholzj** [comment]
I do not think that is possible. If both Kafka Clusters live in the same namespace they will have to be managed by the same cluster operator and they will have to roll after the upgrade. If you use different namespaces, in theory you could use different COs which might make this a bit easier. Alfthough I do not think we ever tested how 0.11 behaves with CRDs from 0.14.

**Comment by EresZX** [comment]
Thank you very much. When I use the operator, I meet a problem that I can't create or update the kafka cluster. The error messages in the operator log is:
[log_errors.txt](https://github.com/strimzi/strimzi-kafka-operator/files/3965964/log_errors.txt)
I don't know why this would happen. It seems that the operator could not patch Secret my-cluster-entity-operator-certs. However, everything is ok and this secret could be patched at first.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
