### ISSUE TITLE
Cluster operator crashes with some data in matchLabels (Cannot deserialize)

### ISSUE THREAD

**Issue by Radionz** [strimzi/strimzi-kafka-operator#2314]
**Describe the bug**
Key-value inside matchLabels are causing the Cluster Operator to crash.

**To Reproduce**
Inside kafka and zookeeper configuration I am using some key/value items that are causing the issue
```yaml
selector:
        matchLabels:
          alicloud-pvname: kafka-pv
```

**Expected behavior**
Should create the expected PVC with added key/value in selector.

**Environment (please complete the following information):**
 - Strimzi version: 0.14.0
 - Installation method: YAML
 - Kubernetes cluster: K8S Serverless 1.12
 - Infrastructure: Alibaba Cloud

Error is
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"]->io.strimzi.api.kafka.model.Kafka["spec"]->io.strimzi.api.kafka.model.KafkaSpec["kafka"]->io.strimzi.api.kafka.model.KafkaClusterSpec["storage"]->io.strimzi.api.kafka.model.storage.PersistentClaimStorage["selector"]->java.util.LinkedHashMap["matchLabels"])
```

**Comment by Radionz** [comment]
Same error in 0.15.0

**Comment by scholzj** [comment]
@Radionz I had a look into the code and I think in Strimzi case the selector should look like this:

```yaml
selector:
  alicloud-pvname: kafka-pv
```

I gave it really only quick try locally, but it seems to work fine for me that way. I guess this might be confusing since it doesn't match the structure in Kubernetes APIs. But please give it a try.

**Comment by Radionz** [comment]
Hi @scholzj,
Work great, thanks :)

**Comment by iagotomas** [comment]
We have experienced the same issue leading to the cluster's operator crash with 0.31.1. We have a setup in which multiple teams collaborate employing Strimzi cluster operator as a shared service, therefore watching on any broken resource is not ideal for us. Couldn't the operator simply ignore deserialization exceptions and omit the reconciliation only logging the message?

**Comment by iagotomas** [comment]
Thanks for your insights @scholzj , I agree ignoring it might not be the best option but crashing the operator because a deserialization exception raises not sure should be the way for handling it. This mainly prevents us from using Strimzi at scale by allowing different teams to use Strimzi CRD's for defining the resources in their own namespaces. Operating the operator becomes very tricky if any team can break it and stop the service for other teams.

**Comment by scholzj** [comment]
I don't think it crashes the operator. But you have an invalid resource there whihc is fed to the operator again and again. And TBH I do not know how to do it differently if you feed it some invalid data.

**Comment by scholzj** [comment]
If you have any improvements, PRs are always welcomed. But this has to be treated as error one way or another.

**Comment by iagotomas** [comment]
Again, thanks for your quick answer :) it indeed crashed the operator, restarted seamlessly ... but after your comment I can imagined our CD tool is trying also to reconcile the resources, as you point, leading to this infinite crashing loop we observed.
We are currently using ArgoCD will check with the experts see if we can mitigate the issue.

Thanks for pointing!

**Comment by iagotomas** [comment]
Will try to reproduce locally for better observing, it happened in one of our development clusters and wasn't able to investigate too much yet.
