### ISSUE TITLE
Kafka brokers shutting down with "ECDSA KeyFactory not available" error

### ISSUE THREAD

**Issue by torwolf** [strimzi/strimzi-kafka-operator#2327]
I have configured strimzi Kafka for oauth authentication using following configuration:-

external:
        type: nodeport
        tls: false
        authentication: 
          type: oauth
          clientId: rd-kafka-poc
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          validIssuerUri: https://federation-qa.xxx.com
          jwksEndpointUri: https://federation-qa.xxx.com/pf/JWKS
          userNameClaim: sub
          tlsTrustedCertificates:
          - secretName: oauth-ca-truststore
            certificate: xxx
          - secretName: oauth-ca-truststore
            certificate: xxx
          - secretName: oauth-ca-truststore
            certificate: xxx
 
However when I apply the yaml file, my Kafka brokers crash with "ECDSA KeyFactory not available" error.  I am using 0.14 version of Srimzi. File with error stack trace is attached. I am not sure what is causing this as configuration looks right to me? 
[Kafka broker error.txt](https://github.com/strimzi/strimzi-kafka-operator/files/3981039/Kafka.broker.error.txt)

**Comment by ppatierno** [comment]
@mstruk can you help on this please?

**Comment by mstruk** [comment]
What's your OAuth2 authorization server?

The expected 'kty' returned by JWKS endpoint is 'EC' in this case, not
'ECDSA'.

Maybe you can change the configuration on your authorization server, and
see if that helps.

**Comment by torwolf** [comment]
@mstruk , we are using pingfederate. Also I checked 'kty' returned is either 'EC' or 'RSA' from authorization server. I also downloaded the strimzi oauth code and tried to run it independently (not sure that is good way to check) but that also failed with same error message and the 'kty' returned was 'EC'.

It fails in following function (bolded line):- 

private PublicKey createECPublicKey() {
        String crv = (String) jwk.getOtherClaims().get(ECPublicJWK.CRV);
        BigInteger x = new BigInteger(1, Base64Url.decode((String) jwk.getOtherClaims().get(ECPublicJWK.X)));
        BigInteger y = new BigInteger(1, Base64Url.decode((String) jwk.getOtherClaims().get(ECPublicJWK.Y)));

        String name;
        switch (crv) {
            case "P-256" :
                name = "secp256r1";
                break;
            case "P-384" :
                name = "secp384r1";
                break;
            case "P-521" :
                name = "secp521r1";
                break;
            default :
                throw new RuntimeException("Unsupported curve");
        }

        try {
            ECNamedCurveParameterSpec spec = ECNamedCurveTable.getParameterSpec(name);
            ECNamedCurveSpec params = new ECNamedCurveSpec("prime256v1", spec.getCurve(), spec.getG(), spec.getN());
            ECPoint point = new ECPoint(x, y);
            ECPublicKeySpec pubKeySpec = new ECPublicKeySpec(point, params);

            **KeyFactory kf = KeyFactory.getInstance("ECDSA");**
            return kf.generatePublic(pubKeySpec);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

**Comment by mstruk** [comment]
That's a keycloak-core helper library. It looks like the string should be
"EC" rather than "ECDSA" in this line:

https://github.com/keycloak/keycloak/blob/master/core/src/main/java/org/keycloak/jose/jwk/JWKParser.java#L107

You could try clone keycloak repository, and build a modified version of
keycloak-core, slip it into your container and see if that fixes it for you.

It should go something like this:

git clone https://github.com/keycloak/keycloak.git
cd keycloak
git checkout 7.0.0

# Edit the file: core/src/main/java/org/keycloak/jose/jwk/JWKParser.java
sed -i '' 's/ECDSA/EC/g'
core/src/main/java/org/keycloak/jose/jwk/JWKParser.java

mvn install -DskipTests

# Now, to get this version of library into Strimzi image you can build a
new image based on strimzi/kafka:latest-kafka-2.3.1 for example:

cd ..
mkdir custom-kafka
cd custom-kafka
cp ../core/target/keycloak-core-7.0.0.jar .

cat > Dockerfile << EOF
FROM strimzi/kafka:latest-kafka-2.3.1
COPY keycloak-core-7.0.0.jar /opt/kafka/libs/strimzi/
ENV CLASSPATH="/opt/kafka/libs/strimzi/*:$CLASSPATH"
EOF

# Make sure to properly set up ENV vars, for example:

# eval $(minishift docker-env)
docker build . -t strimzi/kafka:2.3.1-fix


# Push to docker registry (assuming here current project is 'myproject'
running on openshift / minishift)
export DOCKER_REG=$(oc get services -n default | grep 5000 | awk '{print
$3}'):5000
docker login -u developer -p $(oc whoami -t) $DOCKER_REG
docker tag strimzi/kafka:2.3.1-fix $DOCKER_REG/myproject/kafka:2.3.1-fix
docker push $DOCKER_REG/myproject/kafka:2.3.1-fix

# Now reconfigure Strimzi Kafka Operator to use our modified image
# Assuming you're in the root of strimzi-kafka-operator project:
sed -i ''
"s%strimzi/kafka:latest-kafka-2.3.1%$DOCKER_REG/myproject/kafka:2.3.1-fix%g"
install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml

# Apply changes
oc apply -f install/cluster-operator



# Alternatively you can start with already deployed strimzi cluster operator
oc get deployment strimzi-cluster-operator -o yaml --export >
deployment-strimzi-cluster-operator.yaml
sed -i ''
"s%strimzi/kafka:latest-kafka-2.3.1%$DOCKER_REG/myproject/kafka:2.3.1-fix%g"
deployment-strimzi-cluster-operator.yaml

# And apply changes
oc apply deployment-strimzi-cluster-operator.yaml

**Comment by torwolf** [comment]
@mstruk we will try this out, however is there any plan that this will be incorporated in future Strimzi release?

**Comment by mstruk** [comment]
We'll have to suggest a fix to the Keycloak project, and see what they have
to say about this. If they accept the patch, then as soon as it's released
we can incorporate it into our release.

**Comment by mstruk** [comment]
FYI: https://issues.redhat.com/browse/KEYCLOAK-12624

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
