### ISSUE TITLE
[Doc] COnnectors doesnt work 'error create/find connect-cluster-offfsets'

### ISSUE THREAD

**Issue by patsadow2** [strimzi/strimzi-kafka-operator#2346]
**Suggestion / Problem**
Hello, i've got problem with some kind of auth, i've started with exmaples from srtimzi-0.14.0

**Documentation Link**
Provide a link to the documentation where the bug / suggestion should be applied
![image](https://user-images.githubusercontent.com/19226186/71524028-ea253300-28cb-11ea-8233-301e0bec8e59.png)

i used kubectl apply -f examples/kafka-connect/kafka-connect.yaml

**Comment by scholzj** [comment]
It looks like you are trying to connect Kafka connect with default settings to Kafka broker which has only one node. Kafka Connect will by default try to create some topics for storing its own data and configuration with replication factor 3. But since it seems your Kafka cluster has only one broker, it cannot create it.

You will have to configure Connect to create the topics only with replication factor 1. You can have a look here on how to do it: https://github.com/strimzi/strimzi-kafka-operator/blob/0.15.0/examples/kafka-connect/kafka-connect-single-node-kafka.yaml (check the `config` section)

**Comment by patsadow2** [comment]
@scholzj Great that was a issue. But i've encounter a werid behaviour since i've added mssql and elastic sink and it only sync (mysql data to kafka once when i post connector) later it doesnt observe changes on mysql database and it doesnt pass data from kafka to elastic search, it creat only index with no data.

I'm trying to do last steps from https://medium.com/@sincysebastian/setup-kafka-with-debezium-using-strimzi-in-kubernetes-efd494642585

**Comment by scholzj** [comment]
TBH, that sounds more like an issue with the connector it self whcih I don't know much about. Traing the Debezium mailing list might be better to get some help abotu it.
