### ISSUE TITLE
[Question] Expose kafka via load balancer on local k3s cluster

### ISSUE THREAD

**Issue by mariusstaicu** [strimzi/strimzi-kafka-operator#2381]
Hi,

I've been using strimzi kafka cluster with k3s with success for some time now for local development. However, currently I've been running into an issue when I try to expose kafka via load-balancers on my local machine. The problem is that exposing via lb creates two load balancers on same port 9094 on local machine ip (k3s only binds load balancers to local machine ip). So, the result is that one of the load balancers (either bootstrap or broker one) always remains in pending state.

Is there a way to get around this ? Can I make strimzi to use different ports for load balancers ?

**Comment by scholzj** [comment]
I do not think you can work around it in any way. This is caused by how k3s implements the load balancers which is not how they really for example in public clouds. I think that for the local development, you should maybe try to use node ports. That will in this case work more or less the same way - by using the node IP address - just by using different port numbers.

**Comment by mariusstaicu** [comment]
Thanks, this is what I did in the end. It's not as nice as using port 9094, but that will have to do for now.

**Comment by scholzj** [comment]
Why is it not so nice? Because the port numbers are changing? Or because they are longer?

**Comment by mariusstaicu** [comment]
because i wanna use default ports for kafka for example, it doesn't really matter.

**Comment by davesargrad** [comment]
This issue was closed long ago. We have seen a similar issue, now 4 years later. I fully understand that this is really about how K3S implements load balancers, and to the point made by @scholzj  k3s is not doing it the way it is done in public clouds. 

I'm looking for guidance in terms of how to name that problem, since I want to search for any similar issues written on K3S load balancers (within the K3S issue database). I really think that if Jakub is correct and this is a limitation in K3S, that the K3S team should be looking at an appropriate issue. 

@scholzj Could you please help me articulate the shortcoming in K3S. Thanks for any guidance.

**Comment by scholzj** [comment]
I don't really have any experience with how K3S load balancers work. So all my knowledge is based on what was shared here at the beginning. But in general, the way how Strimzi works is that it uses a load balancer per Kafka broker (+1 for bootstrap service, but that can be disabled). Each of these load balancers will have its own unique address but the same port.

The load balancers in tools such as Minikube - and based on the initial description also K3S - have only one load balancer address (IP) and therefore every service needs to use different port number to avoid a conflict. This is not supported by Strimzi. I'm not sure this problem has any real name. TBH, I'm not even sure whether this could be called a technical limitation or whether this is just a different design.

I think that unlike in 2020, you might be now able to workaround this manually by having a `type: internal` or `type: cluster-ip` listener, creating your own Loadbalancer type services that would each use a different port and redirect to the original target port, and overriding the advertised hostnames. But I do not have any step-by-step guide as I have never done it, I just expect that it can be done.

You should be able to use other methods for exposing the Kafka cluster if needed, e.g. the node ports I suggested above.

**Comment by davesargrad** [comment]
You are great @scholzj . Ty for your understanding.. I'll search into K3S, and see what I can learn.

**Comment by davesargrad** [comment]
@scholzj looks like Sutton is ahead of me with tracing this to K3S.. so ty again for your insights.
