### ISSUE TITLE
[Bug] Remove the myproject namespace

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#2503]
The strimzi yamls are installing bits to the `myproject` namespace, which was an Openshift 3.x thing

Openshift 4.x does not have that anymore, and does, like kubernetes, use the `default` namespace (which is just empty in newer k8s or Openshift 4.x).

Now, we could either move the namespace to `strimzi` or `kafka` instead of `myproject`, which seems artificially to me, especially looking at Openshift 4.x

**Comment by matzew** [comment]
this would also eliminate the need for doing a `sed` exec. in the quickstart guide

**Comment by scholzj** [comment]
I'm not sure `myproject` is necessarily an OpenShift 3.11 thing and I'm not sure installing in `default` is a good idea. I can live with `strimzi` or `kafka`.

> this would also eliminate the need for doing a sed exec. in the quickstart guide

I do not think this is possible. But if you know how to do it it would be great. The problem is that the ClusterRoleBindings have a namespace of the service account to which theey bind the role. And this namespace ignores the `--namespace` and `-n` options in `kubectl`.

**Comment by matzew** [comment]
`myproject` is kinda the `default` NS on Openshift 3.x   

But, I agree, that `strimzi` is the best install.

and if all `CluterRoleBindings` are than _hammered_ to `strimzi` namespace.  For most users the `sed` is gone, no ?

**Comment by scholzj** [comment]
That doesn't solve the problem. Regardless which namespace you add there you will need to use the `sed` when you use different namespace.

**Comment by matzew** [comment]
@rhuss here is the ticket w/ hard-coded namespaces ...

**Comment by scholzj** [comment]
Triaged on 7th July 2022: Should be closed. We need to use some namespace => and `myproject` seems as good as any other. Changing it will also affect existing users possibly already used to `myproject` from all the previous releases. Users can anyway change the myproject namespace to anything else, they do not need to skip with it.
