### ISSUE TITLE
[Enhancement] Strimzi-admin API

### ISSUE THREAD

**Issue by gmcrobert** [strimzi/strimzi-kafka-operator#2540]
Hi Strimzi Team,

The new strimzi-admin repository has been created so I thought I would kick off a discussion on the shape of the API. If we use the Kafka AdminClient from vertx-kafka-client then we can start by offering  an API that looks like this:

`GET /topics` (List the topics) 
`POST /topics` (Create a new topic)
`GET /topics/{topic-name}` (Describe a topic - including the topic configs)
`PATCH /topics/{topic-name}` (Update a topic - essentially the topic configs)
`DELETE /topics/{topic-name}` (Delete a topic)

`GET /consumergroups` (List consumer groups)
`GET /consumergroups/{group-id}` (Describe a consumer group)

The questions I have is whether that is the right set set to start with which will give a useful REST interface and whether we want to base this on the vertx KafkaAdminClient and augment that API to increase the set of endpoints that we can provide in the future?

I am happy to create an openapi spec to define the shape of the requests and responses.

**Comment by ppatierno** [comment]
Hi @gmcrobert it really depends on what's the initial purpose of this admin API for setting a starting point.
With the `/topics` endpoint you described above there are most of the admin operations allowed on topic. 
Regarding the `/consumergroups` endpoint, which kind of information you would expect to have?

If you need to handle ACLs, then a dedicated endpoint for it is also needed.

Anyway, if something is missing we can work on the Vertx Kafka Admin client adding the methods we need from the native Kafka Admin API (https://kafka.apache.org/24/javadoc/org/apache/kafka/clients/admin/Admin.html).

**Comment by gmcrobert** [comment]
Actually - you make a valid point @ppatierno. It is not clear from the description of the strimzi-admin repository exactly what it would contain. From the description in the repository it `provides a way for managing Strimzi and Kafka clusters (+ other components) deployed by it`. That could potentially include an API on top of the Kafka AdminClient for managing the Kafka resources itself and it would be interesting to see if others would see this as valuable or not. If not, I would be interested in seeing what people think should be included.

**Comment by scholzj** [comment]
I wonder how problemativ it will be to base this directly on the Vert.x client. Last time I checked it offers only limited functionality. While we can add more features to the Vert.x API, it might complicate the process with waiting for VErt.x releases etc. SO we need to think through whether it offers enough agility.

**Comment by ppatierno** [comment]
It could be tricky but I think we should follow that way. The Vert.x Kafka client should be improved anyway time by time so it's a good reason for doing that. The Admin API is fairly stable now, so we can start to implement more than we need right now so that we already have them for the future.

**Comment by gmcrobert** [comment]
@scholzj @ppatierno I would like to progress this issue as I have the time to do so now. I believe that what we are trying to create in the strimzi-admin repository is a server with a web callable API which could be used by external clients to talk to Strimzi components, the type of clients being graphical user interfaces as well as command line interfaces. The sensible protocols to use for these would be REST and GraphQL. As Strimzi uses Vertx and Vertx has strong support for both REST and GraphQL interfaces, it would make sense to build a server using Vertx. 

I would like to propose that such a server would be built in a modular way using the Java Service Provider Interface allowing all the API endpoints related to a particular component to be isolated in a jar file that is then loaded from the classpath. This would allow you to run a system that only contains the components that are supported by the backend system so, for example, you could create a Kafka Admin api separate from a Mirror Maker api and when you run the server, you can choose which component API you want available by simply making sure the jar file is on the classpath. 

I can create a draft PR demonstrating what I am referring to so that people have something tangible to comment on and if people like the idea then we can start to figure out how to incorporate it into Strimzi and start to define the components and their APIs.

**Comment by gmcrobert** [comment]
One more question - do we want to move this discussion over to the strimzi-admin repo or keep the discussion in this repo?

**Comment by gmcrobert** [comment]
I have push a draft PR up to the `strimzi-admin` repo to demonstrate what I was trying to describe in the comments yesterday. The PR is https://github.com/strimzi/strimzi-admin/pull/4

**Comment by ppatierno** [comment]
@gmcrobert maybe it's something new that was added in the latest release, but are you aware of the Strimzi Kafka bridge? [1]
It's a component that exposes Kafka with two protocols: AMQP 1.0 (POC) and HTTP 1.1.
It is mostly used for HTTP clients in order to produce/consume messages to/from Kafka on HTTP 1.1 but with the latest release we added an admin endpoint with first operation about listing topics and getting information about a topic.
It sounds like kind of what you are trying to achieve but maybe you have more good reasons for developing another component instead of improving the bridge.

[1] https://github.com/strimzi/strimzi-kafka-bridge

**Comment by gmcrobert** [comment]
@ppatierno we are looking for a base to build user interfaces on top of, like a browser based UI and possibly a CLI. Assuming that we are looking at a client-server architecture for the UI, I am trying to get a common server in place that could be used by any client. If we think about the resources that a UI may want to have access to, it is a lot wider than simply Kafka. You may want to access the Kubernetes API to show health for example, or Prometheus for metrics or Kafka for any Kafka operations. I had a quick look at the Strimzi Kafka Bridge and it could be the server if the plan is to widen it to more components within the cluster. I would also be interested in knowing what the possibilities would be of adding a GraphQL api in addition to the REST as GraphQL is a better API for graphical UI's as REST apis tend to be too granular if architected as pure REST.

**Comment by ppatierno** [comment]
@gmcrobert the bridge purpose it's actually "bridging" other protocols like HTTP and AMQP to the native Kafka one (for producing/consuming and administration as well) but it doesn't expose other resources that are not Kafka related. I think that adding more on the bridge (Kubernetes resources, GraphQL API, ...) is not part of its purpose; other protocols could be added in the future like MQTT but mostly related to exchanging messages and not doing administration related operations.

Regarding what you want to achieve, I don't know GraphQL so well in order to give an opinion so I will dig into it.
Regarding accessing Kubernetes API, do you see this admin server as a simpler way to get Kubernetes resources to avoid the UI or CLI have to interact with Kubernetes API server directly due to potential problems with RBAC and so on?
Finally, about Prometheus metrics, consider that every Strimzi related component like Kafka brokers, ZooKeeper, operators, and even the bridge, already expose metrics in Prometheus format on a plain HTTP endpoint so it could be already reachable by the UI or CLI without the need of an admin server in the middle unless the purpose of this admin server is also handling a kind of authentication and authorization for accessing such information.

**Comment by gmcrobert** [comment]
@ppatierno if we are in a position to expand the bridge to a bigger subset of the Kafka admin client interface then it may satisfy everything that we need. I suggest we park this discussion for now while we bootstrap the conversation on creating the UI. Issue #3287 has been created to start that conversation so, as soon as we have an acknowledgement that a UI is of interest to the community then we can start to figure out some of the details. If you think we should be building a UI, please comment so in that issue and we will start to work on a proposal / prototype. I am guessing that we may be able to access everything we need through HTTP with the current environment assuming we can add some missing Kafka admin endpoints to the bridge.

**Comment by ppatierno** [comment]
@gmcrobert I am just opened to any kind of solution in order to find the best one.
I took a look at GraphQL (as I already mentioned I had never used it) and it sounds to be pretty good for a UI interacting with an API in order to avoid the burden of calling different REST endpoints for gathering the data. If we want to use it, I don't think that adding it to the bridge is the right way to go.
Of course, we can expand the bridge admin endpoint in order to add what's missing for the UI.

**Comment by scholzj** [comment]
I think that assuming we all agree that this should be in the `strimzi-admin` repo, the detailed discussion about the implementation really move into the issues / PR in the `strimzi-admin` repo or into proposals.

In general, I think Vert.x + GraphQL is a good solution. One thing to note is that we should from the beginning think about things such as metrics etc.

I do not see this as conflict with the Kafka Bridge - I think over the time the Admin API might have lot of features which would not belong there. Any any applications needing them can at the end use both services.

**Comment by scholzj** [comment]
Triaged on 17.3.2022: The work on the Strimzi Admin API has been archived and this is not needed anymore.
