### ISSUE TITLE
[Question] Configure similar Authentication across multiple servers

### ISSUE THREAD

**Issue by venkatvghub** [strimzi/strimzi-kafka-operator#2547]
Hi,
I need some clarification on setting up similar strimzi clusters on multiple kubernetes clusters. In essence, assume i have 2 k8s clusters(ClusterA and ClusterB). I have a running strimzi cluster on ClusterA, where i have enabled users using TLS Client Authentication and workload is happening. I now need to bring up another strimzi kafka cluster on Cluster B, with exactly the same credentials, certs, secrets etc. I tried to copy over all the secrets from Cluster A and tried applying on Cluster B, but things don't seem to work. Is there some recommended practice for doing this? Am i missing something? Please guide?
Thanks

**Comment by scholzj** [comment]
TBH, I think nobody raised this before. So I'm not sure. I would expect that if the clusters are identical and the Kafka CR is identical and same namespace is used, the CA certificates, user secrets and maybe server certificates should be reused. For server certificates it depedns on a specific configuration. For example when using external access  via load balancers, Ingress, or OpenShfit routes, the addresses of the brokers would differ and that will mean that Kafka certificates will need to be regenrated. 

Also, how did you copied the secrets? You need to also keep the labels etc. as in the original cluster.

**Comment by venkatvghub** [comment]
Which then brings me to the next question. How do you do a rolling update of an expiring certificate? For instance, look at the following:
```
kubectl get secret kafka-cluster-ca-cert -n kafka -o jsonpath='{.data.ca\.crt}'|base64 -d > cluster-ca.crt
openssl x509 -enddate -noout -in cluster-ca.crt
notAfter=Jan 22 09:03:25 2021 GMT
```
So, after this time above, how do i update my cluster and clients gracefully with strimzi?

**Comment by scholzj** [comment]
> The above automatically has the labels etc. Modified the above to remove the k8s generation assets and tried applying on Cluster B. But that doesn't seem to work.

So what exactly doesn't work? What are the symptoms?

> The above then brings me to the next question. How do you do a rolling update of an expiring certificate?

Please see https://strimzi.io/docs/latest/full.html#con-certificate-renewal-str - it is done automatically, by default 30 days before expiration.

> So, after this time above, how do i update my cluster and clients gracefully with strimzi?

To be honest, nobody so far wanted to run two clusters in parallel with the same certificates. So I do not know. Witgh a single cluster, you just distribute the new certs / have the apps reload it from the secrets.

**Comment by venkatvghub** [comment]
@scholzj , so here is my problem. On my production environments, we are having multiple k8s clusters(e.g.: say a blue cluster and a green cluster), following blue/green deployments. So, i have the application(kafka client) and kafka running on a single cluster(say blue). I want to do a traffic shift to the other kafka cluster(say green). Which means, now my application needs to have support for multiple kafka secrets(one for blue cluster and one for green cluster). As i mentioned, i might want to take down the entire cluster for maintenance(e.g. say kubernetes version upgrade or security patching among other things). In addtion, my consumers also needs to support the same. This does look a bit complex and terrible to manage at the moment and hence my question. 

We thought of lets say setting up kafka on a separate cluster. So, that leads to 1. Single point of failure and 2. That separate cluster also needs to the same set of migration challenges.

In essence, how do i share certificates across multiple kafka clusters?

Thoughts/Suggestions?

**Comment by scholzj** [comment]
I think you are asking me for a solution which definitely works, but I do not have one because I never tried it. I think users running two clusters simply use different certificates. So I think I can only give you some tips which you can try out. Normally, it is only the CAs which matter. If you provide your own CA cert/key (https://strimzi.io/docs/latest/full.html#installing-your-own-ca-certificates-str), it will generate its own server / user certifictes out of it. But since they share the same CA, it should be fine for the clients as the trust will be handled through the same CA public key. With custom CAs, you handle the renewal, so when the time comes, you have to renew them manually (by essentially replacing them with new public key or possible even private key). That would of course refresh all the signed certificates, but since you do the renewal, the CA will be the same.  

> I did come across something like https://strimzi.io/2018/11/16/using-vault-with-strimzi.html. Is this the only recommended way?

The Vault blog post is from a user, I cannot help with it. I never tried it and I don't know anything about it. Sorry.
