### ISSUE TITLE
Openshift deployment with one script (helm or yaml)

### ISSUE THREAD

**Issue by samyan123** [strimzi/strimzi-kafka-operator#2559]
Hi 

Thanks for the operator, it's working fine on openshift however I need to do with two steps process
1) install operator (CRD)
2) install kafka deployment 

is there any way we can do this using one script

basically create openshift template with all in one it (CRD and kafka )

Thanks
Saneera

**Comment by scholzj** [comment]
I guess that when using Helm based on the title of the issue? You can maybe write your own Helm Chart with your own `Kafka` custom resource which will install the Strimzi operator as a dependency? That should get you the CRDs and operator installed in single command with your Kafka CR.

**Comment by saneerayapa** [comment]
Thanks @scholzj do you have any idea how to do this without helm 
create one yaml file with all in one kafka and operator inside it and deployed on openshift as template 
then anyone can click on the template and select zookeeper count, kafka broker count and spring up the project ??

**Comment by scholzj** [comment]
You can give it a try. When everything is in a single file, it sometimes happens that the installation fails because there is too little delay between the CRDs being created and the CR being created (basically, the CRD does not exist yet, do the Kafka CR will be rejected). That depends a lot on environment whether it will work for you or not (how fast the connectivity to the API server etc.). So maybe it works for you, maybe it doesn't. There is not other idea which would come to my mind. You can of course always write some basic shell script which will do it in two commands but you run only one.

**Comment by saneerayapa** [comment]
I have sample shell script to spin up the environment 

`
#!/bin/bash

## Default variables to use
export PROJECT_NAME=${PROJECT_NAME:="sample"}

read -rp "project to use: ($PROJECT_NAME): " choice;
        if [ "$choice" != "" ] ; then
                export PROJECT_NAME="$choice";
        fi

echo "******"
echo "* Your project is $PROJECT_NAME "

oc new-project $PROJECT_NAME
oc project $PROJECT_NAME
oc apply -f strimzi-cluster-operator-0.16.2.yaml -n $PROJECT_NAME
oc adm policy add-cluster-role-to-user strimzi-cluster-operator-namespaced --serviceaccount strimzi-cluster-operator -n $PROJECT_NAME
oc apply -f examples/kafka/kafka-ephemeral-loadbalancer.yaml -n $PROJECT_NAME
`
it's working fine as expected with default configuration . by the way I will try to all in one in one 
openshift template 

Thanks @scholzj

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
