### ISSUE TITLE
[Question] ...Installing your own CA certificates

### ISSUE THREAD

**Issue by ami11singh** [strimzi/strimzi-kafka-operator#2561]

**Comment by ami11singh** [comment]
We have a centralized certificate authority and we have the CA cert to generate new cluster cert but we can't get private CA key to generate cluster key. Is there any other way to install CA key in this scenario?

**Comment by scholzj** [comment]
With _we can't get private CA key to generate cluster key_ you mean that you are getting some error? Or that you do not want to do it?

In general, you can probably generate all theserver certificates manually without providing the private key, but it is fairly clumsy approach and you will not be able to scale easily etc. Or maybe you can try this - https://strimzi.io/docs/master/full.html#kafka-listener-certificates-str - and provide only server certificates for the TLS listeners instead of the whole CA.

**Comment by ami11singh** [comment]
We won't be provided with the private key by the authority. 
I will look into the options provided by you. Thanks!!

**Comment by ami11singh** [comment]
With this methid -https://strimzi.io/docs/master/full.html#kafka-listener-certificates-str - and provide only server certificates for the TLS listeners instead of the whole CA, **we are authenticating the brokers but TLS client authentication isn't happening I believe.**

**Comment by scholzj** [comment]
Not sure I understand what do you mean. You can combine it with TLs client authentication of course.

**Comment by ami11singh** [comment]
So you mean that for authenticating the brokers it will be using our provided cert in config part of the yaml file, and for client authentication we will use the user.crt and user.key pair to create keystore at client side?

**Comment by scholzj** [comment]
If you wanna use the TLS client authentication with your own cert, you need to replace the client CA. If you want to use the user operator, you actually need to provide an CA. If you want to sign the user certificates your self, you can provide only the public key there + some dummy private key as the custom CA. The private key wil never be used unless you use the USer Operator.

**Comment by ami11singh** [comment]
Thanks for the detailed information! I will try this out.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
