### ISSUE TITLE
Operator deployement on openshift master node

### ISSUE THREAD

**Issue by saneera** [strimzi/strimzi-kafka-operator#2627]
Hi 

Is there anyway to configure operator to deploy on openshift master node

**Comment by scholzj** [comment]
I'm not sure I would recommend it. But you can just edit the deployment and add affinity / tollerations to get it running anywhere you want including master nodes.

**Comment by samyan123** [comment]
is there any example document, please

**Comment by scholzj** [comment]
To be honest, it is hard to have an example because every cluster has different labels and taints on the master nodes. So without knowing the details of your cluster, I cannot give you the YAMLs.

Taints are used to make the master nodes _tainted_ and not schedulable for regular workloads. The Pods which should run on master node need to have a toleration for given taint to be allowed to be scheduled there. So you will need to find the taint which your master node has (e.g. using `kubectl get node -o yaml`) and configure the toleration in the Cluster Operator accordingly.  You can find more infor about this here: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

However, the tolerations will make it schedulable on the master, but will not ensure it will be scheduled there if there are also other nodes where it can be scheduled. So you will need to add affinity to tell Kubernetes that you want to run exactly on the master nodes. For that you will need to check the labels your master nodes have and use the affinity to describe that the pod should schedule only on nodes with these labels. Some examples can be found here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity

The Helm Chart in Strimzi does not support configuring tolerations and affinity. And unless Helm has some tricks how to do it, you will need to use the YAML files for installation or you will need to extend the Helm Chart (contributions are always welcomed).

**Comment by samyan123** [comment]
Thanks @scholzj that make sense
actually I need to run Strimzi operator only in helm chard there is a configuration 

```
tolerations: []
affinity: {}
nodeSelector: {}
```
and 050-Deployment-strimzi-cluster-operator.yaml

```
resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

```

**Comment by samyan123** [comment]
> I'm not sure I would recommend it. But you can just edit the deployment and add affinity / tollerations to get it running anywhere you want including master nodes.

Hi @scholzj  
as you above mentioned that "I'm not sure I would recommend it" 
whats is the best practices for operator installation and why do you think master node is not recommended

and one more clarification, 
based on my use case Openshift may have multiple Kafka clusters in different namespaces,
currently ( currently  each namespace have the operator itself)
- when the operator installs globally on the Openshift environment, do you think the one operator can manage all the Kafka clusters without a problem?
-  what are the best practices

**Comment by scholzj** [comment]
Well, there is a reason why the master nodes are protected and should run only Kubernetes / OPenShift compoenents. You can have the operator run o the worker nodes while watching multiple namespaces. You do not need it on the master node just because of that. But of course it is up to you to decide how do you want to have it installed.

**Comment by samyan123** [comment]
Thanks @scholzj 
It’s means that one operator can handle the all the Kafka clusters running on openshift without any problem isn’t it

**Comment by scholzj** [comment]
Well, it depends how many clusters are we talking about and how many resources do you give it. But in general yes, it can.

**Comment by saneera** [comment]
@scholzj Thanks for your reply 

my openshift cluster nodes are looks like below, would you able to provide me an example yaml configuration for the strimzi operator to run on master node 

```
 oc get nodes
NAME                  STATUS    ROLES     AGE       VERSION
ocpcluster-infra01    Ready     infra     8d        v1.11.0+d4cacc0
ocpcluster-master01   Ready     master    8d        v1.11.0+d4cacc0
ocpcluster-node01     Ready     compute   8d        v1.11.0+d4cacc0
```

**Comment by scholzj** [comment]
Your master you described above does for whatever reason not have any taints which is weird and non-standard. So all you need to do is to configure the node affinity for one of the labels on the node: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
