### ISSUE TITLE
[Question] How to use Kafka 2.1 after I had installed strimzi 0.16.2 all namespaces?

### ISSUE THREAD

**Issue by east4ming** [strimzi/strimzi-kafka-operator#2631]
My strimzi version is 0.16.2, but I want to use Kafka 2.1 in one namespace. 
At the same time, another namespce is using kafka 2.3 cluster.
What should I do so I can use Kafka 2.1? 
Can I install strimzi 0.14.0 but don't uninstall strimzi 0.16.2?
Thanks!

**Comment by scholzj** [comment]
Each Strimzi versio supports only selected Kafka versions. This is because supporting the older versions would make it very hard to ensure everything is working, but it would also pull us back in further development as we would be unable to use new APIs and features from newer Kafka versions.

Running mmultiple Strimzi versions in the same cluster is complicated, because lot of the resources the operator uses are shared. For example the Cluster Roles or Custom Resource definitions. You can do it, but you need to be careful and make sure that:
* You install only the CRDs and ClusterRoles of the newer version
* You change the name of the ClusterRoleBindings for one of the versions to make sure they do not conflict with the original names and both operators get the rights they need.

So it can be done, but you should be careful to not break something.

**Comment by east4ming** [comment]
> Each Strimzi versio supports only selected Kafka versions. This is because supporting the older versions would make it very hard to ensure everything is working, but it would also pull us back in further development as we would be unable to use new APIs and features from newer Kafka versions.
> 
> Running mmultiple Strimzi versions in the same cluster is complicated, because lot of the resources the operator uses are shared. For example the Cluster Roles or Custom Resource definitions. You can do it, but you need to be careful and make sure that:
> 
> * You install only the CRDs and ClusterRoles of the newer version
> * You change the name of the ClusterRoleBindings for one of the versions to make sure they do not conflict with the original names and both operators get the rights they need.
> 
> So it can be done, but you should be careful to not break something.

Thanks!
