### ISSUE TITLE
kafka-cluster with volume claim

### ISSUE THREAD

**Issue by saneera** [strimzi/strimzi-kafka-operator#2646]
Hi 
I need to attached persistent volume claim for kafka cluster and attached to the kafka yaml 
is there any way to do this

Thanks

**Comment by scholzj** [comment]
Storage for the KAfka brokers is configured in the KAfka CR: https://strimzi.io/docs/latest/full.html#considerations-for-data-storage-deployment-configuration-kafka

You cannot attach a random PVC to it. It creates its own PVCs based on the specified configuration.

**Comment by rprin** [comment]
Hi,
in the same idea, in order to provide storage for our pods we usually manually create a RBD with CEPH, then we create a persistent volume in k8s, and we reference this PV when creating a PVC with the property "volumeName": 
```
spec:
apiVersion: v1
kind: PersistentVolumeClaim
spec:
  ...
  volumeName: my-persistent-volume
  ...
```

Is there a way to achieve this with Strimzi-Operator ? I tried with selectors but it doesn't seem to work. 
Otherwise do you think you could add support of "volumeName" in the "storage" section ?
Thanks

**Comment by scholzj** [comment]
@rprin All of these overrides are fairly complicaed and expensive to maintain. So I do not think we want to implement everything there. There is IMHO an easy workaround for you ... you can create your own PVCs before deploying the Kafka cluster and use the volumes you want to use in them. All you need to do is to keep the names of the PVCs (as described here: https://strimzi.io/docs/latest/full.html#persistent_volume_claim_naming and here: https://strimzi.io/docs/latest/full.html#jbod_and_persistent_volume_claims). After you prepare the PVCs, you can just deploy the KAfka cluster and it should re-use the PVCs.

Also, AFAIK Ceph RDB storage works fine as a regular StorageClass. So none of this should be needed.

**Comment by rprin** [comment]
Thanks for answering, I already tried the workaround you propose with no success but I'll give it another try.
You're right, we could use a storageclass with ceph rbd but we never figured out how reusing a previously created dynamic volume, that's why we create them manually, but that's another story ;)

**Comment by scholzj** [comment]
I do not have much experience with Ceph RDB - I pretty much just know that it works with Strimzi. But why do you want/need to reuse the volumes? Is it just to make sure the old PVs are not pilling up? Or does it have some business use case?

Normally, this should work fine ... by default, when you delete the Kafka CR, the PVCs should remain on the system and the PVs should be still mapped to them. So if you deploy the KAfka CR again, it should just remount the old volumes (including the data which is often not desired).

**Comment by rprin** [comment]
We are pretty new to kubernetes and one of our concern is the certainty to not loose data  (in case of a cluster crash for instance), or at least be able to easily retrieve it. 
So a PV manually bounded to a manually created CEPH volume is the solution we found so far to be "confident". 
With dynamic provisioning, if a PVC is deleted, we didn't figured out how we coud re-bound the existing ceph RBD. While testing, kubernetes used to create un new pvc, a new PV et a new RBD. Maybe we missed something though...

**Comment by scholzj** [comment]
Ok. This might be something to look at: https://strimzi.io/docs/master/full.html#cluster-recovery_str ... it describes how to recover the cluster when all oyu have are the PVs. Maybe that can help. I do not think the storage class is in any conflict with it. You just need to make sure it is configured to retain the PVs after the PVC is deleted. Have a look at the docs section and maybe it helps to clarify some of the details.

**Comment by rprin** [comment]
Thank you for the link, I missed this chapter in the doc. We should manage to find a solution, one way or another.

**Comment by scholzj** [comment]
I think the chapter is brand new ... it is only in the master docs so far. But it is just new docs, it does not rely on any new features so it should work fine even with older versions of Strimzi.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.

**Comment by akshayparjapati465-lab** [comment]
Reading through this issue, it really hits that familiar ops pain point — everything is configured “by the book,” yet behavior in production doesn’t line up with expectations. Kafka setups especially have that way of appearing stable until one assumption breaks and suddenly you’re chasing side effects across the stack.

I’ve run into that same pattern outside engineering. With health insurance, I used to assume that if the policy structure looked right, it would behave fine when needed. That assumption didn’t hold. What helped was stepping away from surface-level checks and actually analyzing how things perform under real conditions. I tried BimaScore and their Bima Analyze flow, which evaluates policies using a lot of practical, real-world factors instead of just brochure features. Seeing a clear score made gaps obvious that I’d missed earlier.

Different domains, same lesson: systems are only reliable when you understand how they behave, not just how they’re configured. For anyone curious, this is what I used: https://bimascore.com/vox2f8
