### ISSUE TITLE
[Bug] Using the non-default image pull secret does not work

### ISSUE THREAD

**Issue by katheris** [strimzi/strimzi-kafka-operator#2683]
**Describe the bug**
There is a mechanism to set a default image pull secret for all of the components Strimzi creates, like the Kafka and Zookeeper using the EnvVar in the operator deployment.

If I want to use a different image pulls secret for one of the components e.g. KafkaConnect there is no way to opt-out of that default. Setting imagePullSecrets to an empty array in the KafkaConnect CR still results in the default secret being in the KafkaConnect deployment.

Providing an alternative secret in the KafkaConnect CR still results in the default secret being in the deployment.

It would also be useful to be able to use the default service account so that secrets auto created by OpenShift could be used.

**To Reproduce**
1. Deploy the operator setting the env var STRIMZI_IMAGE_PULL_SECRETS
2. Push a KafkaConnect docker image to the OpenShift registry
3. Create KafkaConnect Custom Resource without an image pull secret
4. See the KafkaConnect pod get image pull secret

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.11.1]
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io]
 - Kubernetes cluster: [e.g. Kubernetes 1.14, OpenShift 3.9]
 - Infrastructure: [e.g. Amazon EKS, Minikube]

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

**Comment by scholzj** [comment]
@katheris I was looking into this today but I cannot see the issue.

* If you do not configure anything, the pod will be automatically assigned its service account secret by Kubernetes
* If you configure `STRIMZI_IMAGE_PULL_SECRETS`, it will be used for all images deployed by the operator.
* if you configure `template.pod.imagePullSecrets` in the custom resource for one of the pods, it will be used only for that pod. 
* if both `STRIMZI_IMAGE_PULL_SECRETS` and `template.pod.imagePullSecrets` are configured at the same time, the one from `template.pod.imagePullSecrets` is prefered because it was configured specifically for given pod.
* If you set `STRIMZI_IMAGE_PULL_SECRETS` and at the same time `template.pod.imagePullSecrets` to empty array (`imagePullSecrets: []`), it will not set any secrets for the pod (however, Kubernetes will configure the pull secret from the service account)

This work as I would expect it.

**Comment by katheris** [comment]
Ah it was option 5 that I was missing! Setting `template.pod.imagePullSecrets` to an empty array does the trick. I'll close the bug.
