### ISSUE TITLE
[Enhancement] Don't disable Kafka Connect REST API when using connector CRs

### ISSUE THREAD

**Issue by gunnarmorling** [strimzi/strimzi-kafka-operator#2757]
It seems the REST API of KC isn't exposed when setting `strimzi.io/use-connector-resources: "true"`. Is there an option to still get it for read requests? I suppose people would still like to use it for getting a connector's state, verifying which connector plug-ins exist etc. Also, how can I restart a single connector without the API? Thanks for clarifying.

**Comment by scholzj** [comment]
The APi is not disabled yet because the connector operator is still missing some features such as restarting connectors. But we need to secure the REST API which is currently exposed to anyone so we will probably close it down after it is not needed. Most probably you will have a choice to use the REST APi or the connector operator. Depending on the implementation, maybe it would be possible to disable the security even with the operator. Remains to be seen depending on how we implement it I guess.

What you are seeing right now is probably just effect of the network policies as mentioned in the release notes. We need to create network policies to ensure we can connect from the connector operator to the REST API. But that might result in blocking the access for you. If you need the access today, you should just add your own network policy to give your application access as well and you should be fine. Let me know if you need some more help with the network policy.

**Comment by gunnarmorling** [comment]
Ok, thanks for clarifying. It's no urgent need for me personally; but I'd expect users to come up with these questions if they cannot use the REST API:

* How to list all available connector plug-ins?
* How to pause/resume/restart a connector or task?
* How to get the current connector status?

**Comment by scholzj** [comment]
> Ok, thanks for clarifying. It's no urgent need for me personally; but I'd expect users to come up with these questions if they cannot use the REST API.

Operators are always a bit opinionated. In the same way we offer limited options in some areas when deploying Kafka clusters in order to make it easy and reliable. So at some points the users might need to make some choices whether they want more freedom (and will use Connect rhough the REST API) or whether they want to use the Connector Operator.

But as I said, right now we really just needed to add a network policy to make sure the Connector operator works eevrywhere. You can just add your own to give access to other applications.

> How to list all available connector plug-ins?

When Connector Operator is enabled, you can see the list of connectors in the status of KafkaConnect or KafkaConnectS2I resources

> How to pause/resume/restart a connector or task?

You can pause/resume the connector using the `pause` option in the KafkaConnector resource (https://strimzi.io/docs/latest/full.html#type-KafkaConnectorSpec-reference). 

As I said above, restart is currently not supported (as I said, that is also one fo the reasons why we didn't do anything about locking down the REST API since you need it for restart). It seems users in general want to have the container restarted by the operator automatically and not by some user action. But I guess there might be some need for restarting the connector by user action as well. 

> How to get the current connector status?

You can get it in the status of the KafkaConnector resource

**Comment by gunnarmorling** [comment]
Thanks for the pointer ot the status and options of the resource. Seems like almost everything is covered there.

It might be nice perhaps to have some sort of cheat sheet which gives an overview of the mapping of REST API calls to corresponding status/option of CRs. This would be useful for users migrating from API to Strimzi CRs.

On restarting, so it seems we're converging on a connector per KC instance then. I don't see any general issue with that.

**Comment by ppatierno** [comment]
@gunnarmorling maybe not the pause/resume feature but a good example on how using the connectors is in the blog post https://strimzi.io/2020/01/27/deploying-debezium-with-kafkaconnector-resource.html
