### ISSUE TITLE
[Enhancement] CrdGenerator validate @JsonPropertyOrder

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#2779]
Can we improve the `CrdGenerator` to:

1. validate that the `@JsonPropertyOrder` is present 
2. validate that the properties given are all properties of the class
3. validate that no properties of the class (including inherited properties) are missing

**Comment by samuel-hawker** [comment]
@tombentley this is a great idea.

A question of implementation, would you want this to fail a build if any of the above validations fail, or print them out as warnings?
I am guessing the prior, but just thought it might be useful to clarify in this issue.

**Comment by tombentley** [comment]
Fail the build. People usually overlook warnings.

**Comment by samuel-hawker** [comment]
I haven't had time to finish this.
The core new logic for validating the order property is present was added here:
https://github.com/strimzi/strimzi-kafka-operator/pull/2820/files#diff-52292ed5de154b1a03087dc5c1d64bceR447-R458
However in a larger test restructure I got pretty lost and a lot of the tests no longer work due to the complications that errors collect in an array and many pre-existing tests actually print out many errors, meaning it fairly difficult or unreliable to test.

If someone wants to pick this up, feel free to look at my above closed PR #2820

**Comment by scholzj** [comment]
Where does the property order actually matter? When working on the `api-conversion`, it in theory should be used. But in practice, for example when using `kubectl`, it anyway reorders them. So the question is ... does this really matter?

**Comment by tombentley** [comment]
It _mostly_ doesn't matter, because whatever order we use it's only honoured when it's _us_ serializing the JSON. That's why `kubectl` reorders them. But for things like our tests it allows us to compare strings, which can be useful. It is also be useful for any tooling we (or others, since this is part of the `api` module) might write that displays YAMLs (e.g. `strimzictl`). I think this is worth keeping.

**Comment by scholzj** [comment]
Triaged on 21st June: We should validate that all fields are present at build time.

**Comment by steffen-karlsson** [comment]
Hello @scholzj 

Is this still relevant? If so, I'd like to give it a go.
If possible can you list expected outcome after the solution is successfully implemented? 
Is it still expected to be implemented in the `CrdGenerator`?

**Comment by scholzj** [comment]
I think the expectation is that it will check if:
* The `JsonPropertyOrder` annotation is set
* If it has all the relevant fields (not sure how easy or hard the definition of relevant field is -> we want those generated into the CRD spec to be included. But not the additionalProperties, constants etc.)

If the annotation or some fields is missing, it should raise the error and fail. The PR adding this feature should also update any of the missing fields so that we can merge it without failing the main build.

And then once it is merged, when new field is added tot he API but not to the property order or when a new class is added without the property order, it would simply fail the build and force the user to fix it.

**Comment by steffen-karlsson** [comment]
Sounds good.

Just to clarify, when you say `all the relevant fields`, you mean the ones represented in `JsonPropertyOrder`?
And they all need to have a value and default is acceptable as well?

Ill take a look at this one :)

**Comment by scholzj** [comment]
No, what the check should do is:
* Get all the fields from the class that will be added to the custom resource definition (I think it identifies them through the `get` methods)
* Validate that all of them are listed in the `JsonPropertyOrder` annotation

it would apply to all the POJO classes in the `api` module basically. The whole `https://github.com/strimzi/strimzi-kafka-operator/tree/main/api/src/main/java/io/strimzi/api/kafka/model` tree. But as you would validate it in the CRD Generator, it basically goes through these classes from the Custom Resource implementations, so you do not need to browse the tree, you can just follow the classes as processed in the CRD Generator.

**Comment by steffen-karlsson** [comment]
Makes sense, thanks :)

This is already what I did, so makes sense.
All left is to do the comparison of the fields with the `JsonPropertyOrder ` and fix all the classes.
