### ISSUE TITLE
[Enhancement] Add support for AclAuthorizer class for authorization

### ISSUE THREAD

**Issue by roland-haeusler** [strimzi/strimzi-kafka-operator#2880]
**Is your feature request related to a problem? Please describe.**
Kafka 2.4.0 contains [KIP-504](https://cwiki.apache.org/confluence/display/KAFKA/KIP-504+-+Add+new+Java+Authorizer+Interface#KIP-504-AddnewJavaAuthorizerInterface-AclAuthorizer) which contains a new class AclAuthorizer to replace the SimpleAclAuthorizer class. Strimzi is currently using the [SimpleAclAuthorizer](https://strimzi.io/docs/0.17.0/#simple_authorization) class for authorization.

The new AclAuthorizer contains new and important features (such as the ability to control the amount of authorization logs in the broker logs) and the SimpleAclAuthorizer will be deprecated. 

**Describe the solution you'd like**
Therefore, I would like to raise this feature request to add support for the new AclAuthorizer class for authorization in Strimzi.

Thanks & Kind Regards

Roland

**Comment by scholzj** [comment]
#2891 will remove support for KAfka 2.3.1. Afterwards, this can be done. It sounds like a good stating task.

**Comment by AndrewJSchofield** [comment]
I'm happy to take this one on if no one else is working on it. I understand Kafka ACLs already which will be a help.

**Comment by scholzj** [comment]
Go for it - I assigned the issue to you.

**Comment by AndrewJSchofield** [comment]
Looking more into this issue, it seems to me that the new AclAuthorizer is intended to be compatible with the previous SimpleAclAuthorizer, just using a new Java API rather than the previous Scala trait.

It would be possible to introduce a third type of authorisation to go alongside `simple` and `keycloak`, but I think that this new Authorizer is intended as the replacement of the SimpleAclAuthorizer. So, I propose to try using AclAuthorizer when `simple` is configured and see how that works. The bulk of the work then is to move over to the KafkaAdminClient API to manipulate the ACLs.

I think I will create new clusters with AclAuthorizer, and to permit existing ones to be modified from SimpleAclAuthorizer to AclAuthorizer. For clusters still using SimpleAclAuthorizer, I think it's appropriate to set a condition about a deprecated Authorizer. I could auto-migrate the Kafka cluster's configured Authorizer class over to AclAuthorizer, but that seems a little risky.

**Comment by scholzj** [comment]
That is my understanding as well. It should be just rewritte to Java. So TBH the Pr should basically by just changing the class and testing that everything still works.

**Comment by AndrewJSchofield** [comment]
Works nicely just replacing the old Authorizer with the new one. Of course there's the upgrade path to consider and I'm new to this so I'll proceed carefully. My guess is that I'll target 0.19 with this rather than try to rush it in to 0.18.

**Comment by scholzj** [comment]
Yeah, I think that is totally fine.It will also give us more time to test and catch any issues.
