### ISSUE TITLE
Modify certificate default time

### ISSUE THREAD

**Issue by enunio** [strimzi/strimzi-kafka-operator#2898]
When I modify the validitydays in clusterca, I find it doesn't work. What do I need to do to change the default validity period of the certificate to 10 years.

**Comment by scholzj** [comment]
That is intentional. The new value will be used only when the new certificate is being generated. You can trigger that manully using an annotation: https://strimzi.io/docs/latest/full.html#proc-renewing-ca-certs-manually-deployment-configuration-kafka

**Comment by enunio** [comment]
`clusterCa:
      generateCertificateAuthority: false
      validityDays: 3650
      renewalDays: 3650
    clientsCa:
      generateCertificateAuthority: false
      validityDays: 3650
      renewalDays: 3650`
I have set the above parameters and used the 
kubectl annotate secret <cluster-name>-cluster-ca-cert strimzi.io/force-renew=true
to update the certificate，but it doesn't seem to work. The renewal certificate is still valid for one year

**Comment by scholzj** [comment]
That does not look like the right configuration:
* `generateCertificateAuthority: false` tells the operator that it should not generate the certificate authority. When you set it, you have to provide the certificate authority your self.
* `validityDays: 3650` is ok, that say the certificate should be valid for 10 years. However, since you also said that you willbring your own certificate authority, this will be ignored.
* `renewalDays: 3650` is wrong. It says that the certificate authority should be renewed 3650 days before the expiration. That means almost immediately after it is generated.

The right setting if you want Strimzi to generate the CA would be something like this:
```yaml
clusterCa:
  validityDays: 3650
  renewalDays: 30 
clientsCa:
  validityDays: 3650
  renewalDays: 30
```

To generate certificate valid for 10 years and renew it 30 days before it expires.

**Comment by enunio** [comment]
Thank you very much. It's been a big help

**Comment by enunio** [comment]
Thank you very much. It's been a big help. @scholzj
