### ISSUE TITLE
[Question] Kafka and Zookeeper without tls sidecar

### ISSUE THREAD

**Issue by ananthk01** [strimzi/strimzi-kafka-operator#2922]
Hi,

I am using an istio sidecar in our pods along side our application containers in our cluster. I am looking to do the same with kafka and zookeeper pods. Using the strimzi operator, the sidecars are deployed by default. I read through the documentation and it offers me the ability to define some properties using tlsSidecar but there isn't one where I can prevent the sidecar from deploying at all. I would like to use the istio sidecar that we use currently to be deployed in the kafka and zookeeper pods as well to have it be consistent with other pods. Is this something that's possible today or being considered as an open item?

Thank you.

**Comment by scholzj** [comment]
I do not think this is possible at the moment. I think that most users who use also Istio run the Kafka cluster outside of Istio and just connect to it from apps running in Istio.

**Comment by ananthk01** [comment]
Hi Jakub,

Thank you for your response. Is this a feature that is being considered in the near future? 

If it's not in the plan, perhaps you can provide some guidance regarding the possibility of forking and modifying the code to achieve what I am hoping to do. Kafka is not going to be in a separate cluster. The plan now is running kafka in the same cluster as the application pods, just in a different namespace. Leveraging istio capabilities is the main motive here. Any pointers regarding code changes will help a lot. Please advise.

Thank you.

**Comment by scholzj** [comment]
I do not think this is planned for the near future. Istio is not widespread enough so that we can rely only on Istio. And I do not think we have enough regular contributors to be able to maintain it as an alternative. 

TBH I'm not sure what kind of guidance you are expecting. In the root of this repository, you can find some general files about building Strimzi. If you want, you can also join the CNCF Slack and ask questions. But since this is not something we are working on right now, we do not have a blueprint which we can give you. Perhaps you can start by explaining what is needed, but I'm not sure how much will that help if we have no Istio experiece.

**Comment by ananthk01** [comment]
I see.

I saw the files about building Strimzi. That is clear. 

Now that it's clear that it's not possible as is. I'm looking for guidance to use the operator without the tls sidecar - with code changes and attempting to run locally. All this without istio in the picture. Being able to inject istio is secondary and would not need help with that at this time. 

I'm trying to understand if the tls sidecar implementation is tightly linked to the strimzi operator code? Or will I, after some changes to the code (this is where I'm looking for guidance) be able to use the operator without deploying the tls sidecar. I am hoping that someone involved in this directly would be able to give me some inputs on whether it's worth attempting to do this before going on a wild goose chase.

**Comment by scholzj** [comment]
The TLS sidecars are there for some reason - they help to secure the whole cluster. Removing them should be easy. But you will need to reconfigure lot of different things because because they would need to connect differently. So you will need to figure out how to configure the Zookeeper cluster to bootstrap without them, how to link Kafka with Zookeeper without them. 

You have to keep in mind that the sidecars we have work very differently from Istio sidecars. The do not hijack the traffic to reroute it and secure it as Envoy does in Istio. They work as proxies configured for a specific tasks. So their configuration is coupled with the configuration of the Kafka brokers and Zookeeper cluster.

Also, the sidecars are not used for everything. They are really used just to secure Zookeeper. So there will be additional work to deal with making the Kafka replication work for example.

FYI: Not sure whether it makes it easier or harder, but in #2915 we are removing the Zookeeper pod sidecars because newer versions of Zookeeper now support TLS.

**Comment by ananthk01** [comment]
With 2915, it solves my issue half-way. Although, there are some things that are not clear to me. Please engage me.

I thought, from the information provided, tls sidecar was for secure kafka <-> zookeeper communication. What exactly is the purpose of keeping the kafka sidecar, with the zookeeper sidecar out of the picture? Does the tls sidecar in kafka enable secure communication from external sources to kafka broker and broker to broker communication? Basically, what is the kafka sidecar's role here?

**Comment by scholzj** [comment]
Zookeeper 3.4 had no support for TLS. It has native support for TLS only since 3.5. Because Zookeeper didn't had the support, so doesn't have Kafka support for TLS in communication with Zookeeper (until 2.5.0). So the sidecar needs to be used on both places. The Zookeeper one can be already remvoed, the Kafka one not yet.

I run into some upgrade issues  in #2915 - I have to see how to deal with them and wheter I will make it into the 0.18.

**Comment by ananthk01** [comment]
Sure. Makes sense that it needed to be there in both places when it was there. Doesn't really explain the role of kafka's sidecar to still exist to me though. With kafka supporting tls for inter-broker communication, is that what is being used for currently and the sidecar for taking care of communication with external sources? This clarification should be good enough to bring this discussion to a close for now.

I am looking forward to the 0.18 release. If it makes it in, I can give it a go with that and revisit this topic. I appreciate your time and effort to respond to my queries, Jakub. Have a good weekend.

**Comment by scholzj** [comment]
Strimzi 0.18 will support Kafka 2.4.0, 2.4.1 and 2.5.0. The Zookeeper versions included in these now include the TLS support. But the Kafka brokers them self do not support TLS when connecting to Zookeeper. So that still needs to be done with the sidecar until all KAfka versions we support can do Zookeeper with TLS natively.

**Comment by ananthk01** [comment]
Thank you for the clarification, Jakub. I will explore some options and come back if I have further questions after 0.18 is released. I will close this for now. I appreciate your comments.
