### ISSUE TITLE
[Question] How can I increase throughput of Mirror Maker 2

### ISSUE THREAD

**Issue by zzztimbo** [strimzi/strimzi-kafka-operator#2937]
I have a source cluster that is 1 node with a topic with 3 partitions. 

The target cluster is 3 nodes. I've increased the number of replicas in my KMM2 config to be varying values, even as high as 10 or 20 and this does not seem to increase the messages/sec throughput of about 900 messages/sec. My calculations tell me that it will take 18 days before I'm caught up to current. 

Also, is there a way to configure KMM2 to replicate messages starting with the latest offset and not from the beginning?

**Comment by scholzj** [comment]
I guess you can configure it to start from latest in the `sourceConnector` config section. But that applies only if there is no offset. When there is an offset. So IMHO the best would be if you set the consumer offset on the source cluster. Also if you have 3 partitions, there will be only maximum of 3 active consumers. So it makes no sense to have more than 3 Mirror Maker replicas since the others will not do anything. Not sure why your throughput is so slow - without actually having a cluste about the environment, configurations etc., I cannot help with that.

**Comment by zzztimbo** [comment]
@scholzj I tried my best to Google, but how do I set the consumer offset for Mirror Maker 2 on the source cluster? I see a `mm2-offset-syncs.kafka-cluster-dev-1.internal` topic on the source cluster but I am not quite sure how to manipulate it.

**Comment by scholzj** [comment]
AFAIK, the offset mirroring is done by the `checkpointConnector`: https://github.com/strimzi/strimzi-kafka-operator/blob/4374ba545435e54fde2bc63718f2ded574d0f90b/examples/kafka-mirror-maker-2/kafka-mirror-maker-2.yaml#L29

But you need to do some additional work to recover the offsets in your consumers. You need to use the connect-mirror-client (https://strimzi.io/blog/2020/03/30/introducing-mirrormaker2/). I have one example of it here: https://github.com/scholzj/kafka-enablement-2020/blob/master/mirror-maker/offset-recovery/src/main/java/cz/scholz/kafka/Consumer.java

**Comment by scholzj** [comment]
@zzztimbo Did this helped? Can we close this issue?

**Comment by zzztimbo** [comment]
Yes. @scholzj thank you again for your help.

**Comment by burkass** [comment]
@zzztimbo may i know what's your throughput now? because even after do above suggestion i'm still got 700 messages per seconds. Please let me know about your solution. 

Thank you
