### ISSUE TITLE
[Question] Reccomendation about readness probe

### ISSUE THREAD

**Issue by tsyrfa** [strimzi/strimzi-kafka-operator#2941]
Hello!

I have a 3 kafka brockers with 3 partitions in topic and 10 producers in this topic. I make a load test, and in during it, when I make rolling update kafka brockers (for example by command `kubectl annotate statefulset kafka-cluster-kafka strimzi.io/manual-rolling-update=true`). I see that kafka lost part of messages. When I added 120 seconds initDelay in readness probe it been good.

I tested it with `min.insync.replicas: 2` on brocker  and `(acks=all)` on consumer. I think that data lost becouse it is underreplicated partition - maybe it looks like:
"we alredy recreate first brocker,k8s think thatall OK, but brocker not actualizeted his replica yet. Ater k8s delete second brocker and we have only one actual replica and can't write data to "

I don't like that I use constant value 120 second in readness probe. Maybe you can reccomend me somethink different like workaround? And maybe in your plains add to readness probe checking for underreplicated replicas?

**Comment by scholzj** [comment]
Not sure what version of Strimzi you use, but if it is not completely old it should be checking the replicas. One way or another, if you have properly configured producer, the producer should not publish the data when the partition is under replicated regardless of what Strimzi does. So this is a weird.

For the record, the `acks=all` option needs to be set on producer - not sure if this is just a typo in the issue or if that could be part of the problem.

**Comment by tsyrfa** [comment]
Of course - `acks = all` in the producer, sorry. I am using version 0.16.0.
And yes - maybe we misconfigured our producer. You mean it have to wait a few seconds and send the messages again? But I think there is no need to wait in the producer - if it is a system with a high load (for example, I tested at 5k rps), it can be difficult for the producer to keep the flowing stream for 30 seconds while updating kafka.

**Comment by scholzj** [comment]
I'm not really 100% sure how this works in Kafka. If you have producer configured to send the messages reliably, it should:
* Not be able to sucessfully produce any messages when your topic has less than two ISR replicas
* And either try to resend such messages later or give you an error

I do not think your code of the the producer has to intentionally wait for something. But the KafkaProducer should be able to handle it by resending the messages and giving you an error callback when the resending fails.

Strimzi tries to make sure in the rolling update that it will cause as small disruption as possible - for example by not taking down another replica before the previous one recovered. And of course it is always possbile there is some bug in this. But it should not cause any message loss with reliable producers since the producer and broker need to take care of this. This is at the end not different from a situatin when you hit a bad luck and two broker pods crash at the same time from unrelated reasons. In such case you also need the producer to be reliable.

**Comment by tsyrfa** [comment]
Thanks for your answer! I will discuss about it with team.

"This is at the end not different from a situatin when you hit a bad luck and two broker pods crash at the same time from unrelated reasons." - it good argument, and we need to think about it

**Comment by tsyrfa** [comment]
Sorry for long answer.
I had incorrect information about  this issue.
Our producer tried to resend data.

When it is a rolling update in kafka without 120 seconds delay happend about 40 seconds lost data. But if data is too many, produsers destroyed. Of cource, if we lost 2 kafkas from 3 we will  have the same problem. But it lower chance than kafka rolling update.

So I think this questuions is actual
Maybe you can reccomend me somethink different like workaround? And maybe in your plans add to readness probe checking for underreplicated replicas?

**Comment by scholzj** [comment]
I still don't exactly understand what the problem in Kafka is TBH and how we can fix it properly. But you can maybe use the initial delay configuration in the readiness probe to simulate this? It will make the readiness probe wait before it starts checking the pod and marks it as ready. And that should cause the delay in the rolling update you want.

**Comment by tsyrfa** [comment]
I undersand your point, thanks!
I think we can close this issue
