### ISSUE TITLE
[Question] Token is not getting refreshed

### ISSUE THREAD

**Issue by klalafaryan** [strimzi/strimzi-kafka-operator#3021]
Hi all,

We have noticed weird behavior after upgrade (to 0.17.0), and we are getting following in the broker logs:

```
2020-05-14 13:42:05,385 WARN The cached public key with id '9bmWbs6ogiWPRxEwXAH3qsrBEz8oa4YUNd347y1nz9o' is expired! (io.strimzi.kafka.oauth.validator.JWTSignatureValidator) [data-plane-kafka-network-thread-2-ListenerName(TLS-9093)-SASL_SSL-4]
2020-05-14 13:42:05,387 INFO [SocketServer brokerId=2] Failed authentication with 10-112-11-46.beb-cluster-connect-api.kafka.svc.cluster.local/10.112.11.46 ({"status":"invalid_token"}) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-2-ListenerName(TLS-9093)-SASL_SSL-4]
```

I have seen that `strimzi-kafka-oauth` new version has been released (0.5.0) which has the following bug fix:
```
Fixed JWKS keys refresh bug
```

How this change should be reflected on `kafka-connect` and `brokers`, I don't see any new versions for `strimzi-kafka-operator` ?

Any ideas ?

Thanks!

**Comment by klalafaryan** [comment]
Seems like we are having this problem:
https://github.com/strimzi/strimzi-kafka-oauth/issues/41
and it is a bug.

**Comment by scholzj** [comment]
@mstruk can maybe say if this is related to 0.5.0 and fixed there or not. The 0.5.0 will be used in Strimzi 0.18.0.

**Comment by klalafaryan** [comment]
@scholzj  So it means 0.17.0 is broken. Do you have a release date for 0.18.0 ? 
If it is not going to happen very soon, can we maybe patch the 0.17.0 version ?

**Comment by scholzj** [comment]
I don't think a single bug makes a release broken. We hope to have 0.18.0-RC1 soon. either end of this week or early next week.

**Comment by mstruk** [comment]
@klalafaryan The bug should be fixed in oauth-0.5.0 and in Strimzi 0.18.0.
In the mean time - the underlying cause of the problem is either temporary network issue, or temporary authorization server unavailability. I would suggest to try use `introspectionEndpointUri` approach as an alternative to `jwksEndpointUri`. With that you would still experience occasional issues (due to inability to get response from authorization server) but they would be limited to each client session initiation rather than a complete loss of service.

**Comment by mstruk** [comment]
Another option, if you're not really rotating the signing keys used for JWT signatures, you can simply set `jwksExpirySeconds` to a really big value - e.g. 31536000 (one year worth of seconds).

**Comment by klalafaryan** [comment]
@scholzj  Sorry maybe the "broken" was not the right word, but imho the bug itself it's quite critical.
 
@mstruk Thanks for your suggestions.
Currently, we have deployed the `keyclock` with `deployment`. Another option would be to have it deployed with `statefulset` (rather than a `deployment`). Is that correct ?

**Comment by mstruk** [comment]
@klalafaryan Keycloak uses a database to store its internal state. By default that's an in-memory instance of H2. That means of course that if Keycloak is restarted it generates new signing keys, and you will encounter the problem of invalid keys. It's not enough that the filesystem of the pod survives (which statefulset ensures) - for the default Keycloak container configuration every restart will wipe out the Keycloak internal state. What you have to do is set up a separate stateful pod running one of the supported databases (e.g. Postgres), and you need to configure Keycloak docker container to use that database.

Maybe you don't have to deploy Keycloak with `statefulset`, and the `deployment` will work just fine as long as the database is persistent.

**Comment by klalafaryan** [comment]
@mstruk Thanks for the clarification.
Currently, we have a Keycloak configured with `deployment` and `postgres` database behind, so it means we don't need to change this part.

Ok, so for now one of the workarounds which will cover all cases would be to increase `jwksExpirySeconds` to a really big value, because even if we use `introspectionEndpointUri` we will still have the same problem (when temporary authorization server is not available) for some clients, right ?

**Comment by mstruk** [comment]
If currently the restart of Keycloak pod causes the signing keys to be regenerated, then increasing `jwksExpirySeconds` may keep the old tokens working, but won't help with the new tokens if broker doesn't manage to refresh them (due to the refresh bug). If it manages to refresh the new tokens, then the old tokens won't work any more because they are not present any more in the restarted Keycloak pod. If transient Keycloak pod + stateful Postgres doesn't work for you now, `jwksExpirySeconds` by itself won't solve the problem. In that case I would try deploy Keycloak as a statefulset, and see if that helps.

When authorization server is not available, you will have problems with the clients in any case. The client has to connect to authorization server from its pod to obtain the access token before establishing the session with the Kafka Broker. If authorization server isn't available that step will fail. If it succeeds, the Kafka Broker will have to contact authorization server's introspection endpoint to validate the token, and if authorization server isn't available that will fail.

Actually the client caches the access token for about the lifetime of the token, and reuses it for subsequent sessions. If Keycloak is restarted in between and the old token signing keys no longer work, the client will still keep trying with the old access token that isn't valid any more, resulting in 'expired token' error. Thus, even if you configure introspectionEndpointUri on the Kafka Broker side to bypass the refresh issue, you still have to force the client to refresh the access token. The only reliable immediate way to do that is to restart the client process. There settings through which you can control the refresh period on the client but those don't react to authentication error, but are fixed, so if you shorted the refresh period, that means that the client will refresh the token more often all the time.

For a stable, smoothly running system you really have to retain the signing keys between Keycloak restarts.

**Comment by klalafaryan** [comment]
@mstruk  thanks a lot for detailed clarification. 

For sure we can try to deploy `Keycloak` with `statefulset`, but from your previous comment I understood that if I use keycloak (with `deployment` mode) + postgres, signing keys will be retained between `Keycloak` restart. Right ? 
If yes, I am not sure how `statefulset` will help.

**Comment by mstruk** [comment]
Well, I used the word 'maybe' because I'm not sure - just making an educated guess :)
But, if the signing keys are in fact retained between Keycloak restarts, then increasing `jwksExpirySeconds` should help.

**Comment by klalafaryan** [comment]
@mstruk  I have just verified, that `keycloak` with `deployment` +  `postgres` (without `statefulset`) retains the same `signing keys` between restarts.

So as you suggested, having following configuration should workaround the bug.
```
    jwksExpirySeconds: 31536000
    jwksRefreshSeconds: 31535940 #The interval must be at least 60 seconds shorter than the expiry interval.
```

**Comment by klalafaryan** [comment]
@mstruk @scholzj  I think we close this ticket
