### ISSUE TITLE
[Question] Memory usage 100% in kafka

### ISSUE THREAD

**Issue by tsyrfa** [strimzi/strimzi-kafka-operator#3175]
Hello!

We have a kafka-cluster in k8s.
We have alert when pod use above 70% of it memory.
And when kafka under load it using memory increase to 100% (I think that it use pagecache) and alert running.
We can disable alert for kafka pods, but I think that it bad idea - OOM can destroy node in few cases.
So I need to configure memory usage on kafka.
Now I think about configure pagecache using on "strimzi" or "kafka" level. Maybe you have ideas about it?

**Comment by scholzj** [comment]
I do not think the pagecache will count into this limit since it is handled by kernel directly and AFAIK you cannot easily assign it to different processes. So I think this will be only the Java memory. You can use some options such as `-Xmx` etc. to tell Kafka how much heap memory should be used for example - that might be something to look into: https://strimzi.io/docs/operators/latest/full/using.html#assembly-jvm-options-deployment-configuration-kafka

**Comment by tsyrfa** [comment]
It looks like, we will disable alert on metric `container_memory_working_set_bytes`.
As I knew it include 

> It is the total usage - inactive file. It is an estimate of how much memory cannot be evicted.

And in our case it include page cache. And in all our test kafka memory was never bigger then limit. So, It incorrect metrics for kafka (but k8s use this metric for OOM kill pods)

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks.

**Comment by tsyrfa** [comment]
We can close it. Thanks

**Comment by scholzj** [comment]
Thanks.
