### ISSUE TITLE
Question :  Configuring only bootstrap service for kafka as External LoadBalancer

### ISSUE THREAD

**Issue by shantpschauhan** [strimzi/strimzi-kafka-operator#3223]
Hi
We are using Srimzi Operator Version 0.17.0 . We need to expose only Kafka bootstrap service as External Load Balancer. At the same time we do not want to expose kafka brokers exposed as External Load balancer.
Is this possible and How we can achieve this.
With existing external listener configuration if we can configure listener on port 9094 as Load Balancer in this case this also exposes all your kafka brokers as External Load Balancer. We want to reduce no of Load-balancer and want to keep 1 Load-Balancer for external Bootstrap Service.

**Comment by scholzj** [comment]
Keeping only the loadbalancer for the bootstrap service would not be enough. To connect a Kafka client, it needs the bootstrap service as well as the per-broker services. Without them you would not be able to produce and consume messages since the bootstrap loadbalancer is used only for getting the metadata.

**Comment by shantpschauhan** [comment]
Thanks.... so in this case can I go ahead with creating a new service as type Loadbalancer manually to expose the broker pods for port 9094.... so only 1 LB can be used to connect to brokers....
Please let me know If this makes sense...….. or this have some dependency with Strimzi operator code...

**Comment by scholzj** [comment]
As I said, it doesn't make sense for 99% of use case because of how Kafka and its clients work. What do you want to use it for? If for sending and receiving messages it will not work.

**Comment by shantpschauhan** [comment]
Thanks scholzj... will look to use ingress in this case....

**Comment by scholzj** [comment]
Ok. I will close this than. Feel free to reopne it or open a new issue if you have some more questions.

**Comment by w3blogfr** [comment]
Hello,

I have a similar needs @scholzj . we are on premise and our kubernetes cluster could change VMs where Kafka is running (consequently changing also IP). We use MetalLB to manage virtual IPs.  

Actually, 
We don't use external bootstrap server because it's exposing one single VM with nodePort, so we lost kafka on first IP changing.
We communicate to our client 3 VM IP and their node port. VM ips are reacheable in our networks by kafka client.
With that configuration n that way we are tolerant for the first 2 VMs changing. if the last IP change, our client can't connect anymore.

The load balancer option expose one virtual IP for each broker + bootstrap one (I found the option to disable bootstrap one).

I would have an option to do the opposite : continue to expose broker with nodeport and expose boostrap with load balancer to use only one IP. For me it should works, let me explains why.

Client will connect first to bootstrap IP first, then client retrieve the node port IPs of each brokers and can connect to all of them.
If  all VM IP changed, client will be always able to contact bootstrap virtual IP (constant), and get new list of broker nodeports with their new IP.

What do you think?

**Comment by scholzj** [comment]
@w3blogfr So you use NodePort listener now? Did I got it right? I think the best think you can do is to create manually a `type: Loadbalancer` service pointing to the broker pods and using the right port from the listener configuration. And then you can use that for bootstrapping in the clients. You do not need any special support for it from the operator. If you use TLS, you can add additional SAN names to the certificate to match your new loadbalancer bootstrap IP / name in the listener configuration as well.
