### ISSUE TITLE
Namespace Monitoring

### ISSUE THREAD

**Issue by vikneshgs** [strimzi/strimzi-kafka-operator#3261]
Hello,

We are running a kubernetes cluster with multiple applications (Including Kafka). So my question are : 

1) If i make the operator to monitor whole k8 cluster and running namespaces, will it make huge load for kafka operator as it monitors?
2) is it possible to monitor the namespaces of kafka alone, lets say, specifying the namespaces as kafka-projectname-*. So that all the namespace which are build for kafka alone with above mentioned format will alone be monitored?

**Comment by scholzj** [comment]
Re 1) It is not. The Kubernetes watches can work in two mode -> watching a single namespace or watching the whole cluster. So having the operator watch the whole cluster is really easy and should not cause any performance issues.

Re 2) It is not supported to use wildcards. You would need to list all the namespaces (e.g. `kafk-projectname-1,kafka-projectname-2,...`). This actually puts bit more load on the operator since it needs to open watch per namespace. But unless you specify really a lot of namespaces, it should be fine.

**Comment by vikneshgs** [comment]
@scholzj : Thank you for clarifying.
