### ISSUE TITLE
[Enhancement] Add load before and after information to rebalance optimization proposal

### ISSUE THREAD

**Issue by tomncooper** [strimzi/strimzi-kafka-operator#3279]
## Optimization Summary

Currently the status of the `KafkaRebalance` CR shows the `Summary` field of the json returned from Cruise Control rebalance endpoint. This provides an overview of what the rebalance would entail:

```
{
  "numIntraBrokerReplicaMovements": 0,
  "excludedBrokersForLeadership": [],
  "numReplicaMovements": 30,
  "onDemandBalancednessScoreAfter": 74.54047494896054,
  "onDemandBalancednessScoreBefore": 74.54047494896054,
  "intraBrokerDataToMoveMB": 0,
  "recentWindows": 1,
  "dataToMoveMB": 0,
  "monitoredPartitionsPercentage": 100,
  "excludedTopics": [],
  "numLeaderMovements": 12,
  "excludedBrokersForReplicaMove": []
}
```
This lets a user judge the size of the changes involved in this proposed rebalance. However, the only comparison between the cluster before and after are the `onDemandBalancednessScore`s. Due to how these are calculated, they may not actually show a difference despite the fact that cluster will actually change. Therefore a user cannot always tell from the summary what changes are involved in a proposed rebalance.

## Broker Load Before/After

The json returned by the rebalance endpoint also contains details of the load on each broker before and after the proposed rebalance. 

### Before Optimization

```
curl -X POST 'localhost:9090/kafkacruisecontrol/rebalance?json=true&verbose=true' | jq .loadBeforeOptimization.brokers
[
  {
    "FollowerNwInRate": 0.013525374233722687,
    "BrokerState": "ALIVE",
    "Broker": 0,
    "NwOutRate": 0.09418795816600323,
    "NumCore": 1,
    "Host": "my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc",
    "CpuPct": 0.7460259795188904,
    "Replicas": 52,
    "NetworkInCapacity": 10000,
    "Rack": "my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc",
    "Leaders": 24,
    "DiskCapacityMB": 100000,
    "DiskMB": 1.9566116333007812,
    "PnwOutRate": 0.10786869935691357,
    "NetworkOutCapacity": 10000,
    "LeaderNwInRate": 0.07638948410749435,
    "DiskPct": 0.001956611633300781
  },
  {
    "FollowerNwInRate": 0.011713990941643715,
    "BrokerState": "ALIVE",
    "Broker": 1,
    "NwOutRate": 0.015959708020091057,
    "NumCore": 1,
    "Host": "my-cluster-kafka-1.my-cluster-kafka-brokers.myproject.svc",
    "CpuPct": 0.06810824573040009,
    "Replicas": 52,
    "NetworkInCapacity": 10000,
    "Rack": "my-cluster-kafka-1.my-cluster-kafka-brokers.myproject.svc",
    "Leaders": 25,
    "DiskCapacityMB": 100000,
    "DiskMB": 0.3304891586303711,
    "PnwOutRate": 0.02809318821527995,
    "NetworkOutCapacity": 10000,
    "LeaderNwInRate": 0.015959708020091057,
    "DiskPct": 0.0003304891586303711
  },
  {
    "FollowerNwInRate": 0.013921923004090786,
    "BrokerState": "ALIVE",
    "Broker": 2,
    "NwOutRate": 0.01159792093676515,
    "NumCore": 1,
    "Host": "my-cluster-kafka-2.my-cluster-kafka-brokers.myproject.svc",
    "CpuPct": 0.6790064573287964,
    "Replicas": 52,
    "NetworkInCapacity": 10000,
    "Rack": "my-cluster-kafka-2.my-cluster-kafka-brokers.myproject.svc",
    "Leaders": 25,
    "DiskCapacityMB": 100000,
    "DiskMB": 0.3147859573364258,
    "PnwOutRate": 0.02577289438340813,
    "NetworkOutCapacity": 10000,
    "LeaderNwInRate": 0.011276115663349628,
    "DiskPct": 0.0003147859573364258
  }
]
```

### After Optimization
```
curl -X POST 'localhost:9090/kafkacruisecontrol/rebalance?json=true&verbose=true' | jq .loadAfterOptimization.brokers
[
  {
    "FollowerNwInRate": 0.02308002859354019,
    "BrokerState": "ALIVE",
    "Broker": 0,
    "NwOutRate": 0.08175639063119888,
    "NumCore": 1,
    "Host": "my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc",
    "CpuPct": 0.6811699867248535,
    "Replicas": 47,
    "NetworkInCapacity": 10000,
    "Rack": "my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc",
    "Leaders": 4,
    "DiskCapacityMB": 100000,
    "DiskMB": 1.7660455703735352,
    "PnwOutRate": 0.10537855140864849,
    "NetworkOutCapacity": 10000,
    "LeaderNwInRate": 0.0644640177488327,
    "DiskPct": 0.0017660455703735352
  },
  {
    "FollowerNwInRate": 0.006483083590865135,
    "BrokerState": "ALIVE",
    "Broker": 1,
    "NwOutRate": 0.02104378430522047,
    "NumCore": 1,
    "Host": "my-cluster-kafka-1.my-cluster-kafka-brokers.myproject.svc",
    "CpuPct": 0.11976181715726852,
    "Replicas": 53,
    "NetworkInCapacity": 10000,
    "Rack": "my-cluster-kafka-1.my-cluster-kafka-brokers.myproject.svc",
    "Leaders": 34,
    "DiskCapacityMB": 100000,
    "DiskMB": 0.4177122116088867,
    "PnwOutRate": 0.027711416769307107,
    "NetworkOutCapacity": 10000,
    "LeaderNwInRate": 0.020740840584039688,
    "DiskPct": 0.0004177122116088867
  },
  {
    "FollowerNwInRate": 0.009598176926374435,
    "BrokerState": "ALIVE",
    "Broker": 2,
    "NwOutRate": 0.018945411022286862,
    "NumCore": 1,
    "Host": "my-cluster-kafka-2.my-cluster-kafka-brokers.myproject.svc",
    "CpuPct": 0.6922088861465454,
    "Replicas": 56,
    "NetworkInCapacity": 10000,
    "Rack": "my-cluster-kafka-2.my-cluster-kafka-brokers.myproject.svc",
    "Leaders": 36,
    "DiskCapacityMB": 100000,
    "DiskMB": 0.41812896728515625,
    "PnwOutRate": 0.02864480816060677,
    "NetworkOutCapacity": 10000,
    "LeaderNwInRate": 0.018420448526740074,
    "DiskPct": 0.00041812896728515625
  }
]
```

This clearly contains a lot more information and you can see from the examples above how the balancedness scores hide the change in replicas and leaders between the brokers before and after. 

## Proposal

To add this information we could just add the broker before and after information to the status field. However, as you can see above, there is a lot of information (some fields can be ignored but most are useful) and the more brokers in the cluster the bigger this gets. There are a few ways we could go:

1) The CC command line client (and non-json response) puts this data in a table and we could try and do this, although I am not sure how to do this with K8s yaml. 
2) We could put this information somewhere other than the `KafkaRebalance` status, such as a ConfigMap?
3) We could limit the output by providing a difference between the before and after.

I would be interested to know peoples opinions. I think adding this information would be useful.

**Comment by tombentley** [comment]
* YAML is, to a first approximation, just less disgusting JSON. So you can't do tables.
* I think the UX with creating a ConfigMap containing some YAML or JSON which the user has to get separately from the status and then having the operator or them delete it after the proposal has been executed is pretty horrid.


Let's break it down.

I assume the following won't change due to the rebalance, although some of them, such as DiskCapacity, provide context to the quantities which _do_ change
* "NumCore": 
* "NetworkInCapacity": 
* "Host": I don't think we need this at all
* "Rack": I don't think we need this at all
* "DiskCapacityMB": 
* "NetworkOutCapacity": 

Then there's
* "BrokerState": I'm intrigued by this... presumably CC can tell us that a broker(s) is no longer needed. But presumably there's nothing which constrains it to only suggest the highest numbered broker is the one removed. In any case, I think we could leave this out for now.

Which leaves:
* "Broker": 0,
* "Replicas": 47,
* "Leaders": 4,
* "LeaderNwInRate": 0.0644640177488327,
* "FollowerNwInRate": 0.02308002859354019,
* "NwOutRate": 0.08175639063119888,
* "PnwOutRate": 0.10537855140864849, // what _is_ this? Percentage out rate?
* "CpuPct": 0.6811699867248535,
* "DiskMB": 1.7660455703735352,
* "DiskPct": 0.0017660455703735352

Which is still quite a lot, but perhaps it's manageable... So I'd like to offer a 4th option: If we used arrays to contain the before and after pairs we could make it look like this:

```yaml
common:
    numCore: 
    networkInCapacity:
    networkOutCapacity:
    diskCapacity: 
changes:
  - broker: 0
    replicas: [47, 49]
    leaders: [32, 30]
    leaderNetworkInRate: [0.0644640177488327, 0.0644640177488327]
    followerNetworkInRate: [0.0644640177488327, 0.0644640177488327]
    networkOutRate: [0.0644640177488327, 0.0644640177488327]
    cpuPercentage: [0.0644640177488327, 0.0644640177488327]
    diskMB: [1.7660455703735352, 1.7660455703735352]
    diskPercent: [0.0644640177488327, 0.0644640177488327]
  ...
```

Pros:

1. It's easier for a human to read the YAML and compare before and after because they're closer together (same array), rather than being in a different object (bear in mind too that the apiserver will generally return properties in arbitrary order).
2. It's still easily machine readable.
3. While I'm loath to change the names, things like "CpuPct" are not consistent with our other CRs which avoid abbreviations.

The big con is that changing the format _at all_ makes it harder for anyone who's already got anything which parses the CC output to present it differently. I guess they can always make requests to CC directly though, so I don't think that's really a huge problem.

**Comment by ppatierno** [comment]
In the end you are building a table in this way :-) ... where columns are implicit.
Not having a self-describing status fields always means that users have to read the documentation in order to understand what are the values in the arrays. Anyway, it's the most compacted representation I can think.
To make it simpler, I was wondering if we could start to "round" these values coming from CC. Does it really make sense having all these decimal digits?

**Comment by tombentley** [comment]
@ppatierno I considered that, but I don't think it's doable because those are JSON number (i.e. double) type, so you can't easily be truncated at, say 3 decimal places. You could convert them to strings, but then you're just making it harder for parsing.

**Comment by ppatierno** [comment]
@tombentley our CC API client gets these values in JSON format from the CC REST API. Why we can't convert them to double numbers, for example, truncate them and then writing the new value in the status?

**Comment by tombentley** [comment]
Because that's not [how floating point works](https://www.exploringbinary.com/why-0-point-1-does-not-exist-in-floating-point/).

**Comment by tombentley** [comment]
I suppose you _could_ round to a number that did have an exact binary representation, but TBH I'm not sure it's worth it.

**Comment by tomncooper** [comment]
Yes this can be closed
