### ISSUE TITLE
[Enhancement] Add list of used topics to KafkaConnector statuses

### ISSUE THREAD

**Issue by saranyaeu2987** [strimzi/strimzi-kafka-operator#3318]
I have deployed few kafkaconnector custom resources to my strimzi kafkaconnect cluster.

```
$ kubectl get kctr
NAME                                   AGE
emd-ck-coll-cntl-connector         3d19h
emd-cmptr-typ-connector            3d19h
emd-company-connector              3d19h
emd-dist-connector                 3d19h
emd-ecomm-mkt-area-connector       3d19h
emd-financial-div-connector        3d19h

```
Is there a command/way to find the topic consumption status of a given connector? i.e how many messages consumed so far for a given connector, when was the last message consumed etc

**Comment by scholzj** [comment]
You can check the Prometheus metrics for Kafka Connect. But I'm not sure it provides this information.

**Comment by scholzj** [comment]
Apparently, the KIP-558 (https://cwiki.apache.org/confluence/display/KAFKA/KIP-558%3A+Track+the+set+of+actively+used+topics+by+connectors+in+Kafka+Connect) adds a new REST endpoint for this. I think we can use it to populate the connector status maybe? If you think this would be useful, we can change this issue to enhancement to keep track of it.

It should be supported since Kafka 2.5.0 - so we will need to eait until we drop support for KAfka 2.4.x before implementing it.

**Comment by OuesFa** [comment]
@saranyaeu2987 FYI using [this dashboard](https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/metrics/grafana-dashboards/strimzi-kafka-exporter.json) you can filter on your connector consumer.id and see what's going on regarding consumption (which topic(s), how many messages consumed so far for a given connector, the consumer lag etc.) 

Here is a screenshot when filtering on one specific consumer id (a connector)
<img width="1705" alt="Capture d’écran 2020-10-08 à 00 49 07" src="https://user-images.githubusercontent.com/10348298/95396102-72774080-0900-11eb-95d9-1617e4493aec.png">
