### ISSUE TITLE
[Kafka OAuth Implementation Process] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3319]
Hi Team,

I have a requirement to enable the user authentication as OAuth in Kafka, I started going through the strimzi documentation. However, i am reaching out a little early to understand do we have any simple example kind which I can deploy to try how it works which will help me to understand the functionality behind.

Need some info on this to start with.

**Comment by scholzj** [comment]
I do not think we have any OAuth examples. Such examples are a bit hard because you need to make some expectation what kind of OAuth server will be used, where it will be running etc. SO unlike the current examples you cannot just write some YAML and deploy it everywhere and have it working.

I have somewhere my private examples for using Keycloak as the OAuth server using their operator. If Kaycloak works for you, I can share them here with you.

**Comment by vperi1730** [comment]
Sure, Please share them across and i will look into them. Thanks Scholzj.

**Comment by scholzj** [comment]
Ok ... it all expects to run from a namespace `myproject`:
1) Install the Keycloak Operator (for example from here: https://operatorhub.io/operator/keycloak-operator)
2) Deploy and configure Keycloak and its realms: [keycloak-yamls.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4923716/keycloak-yamls.zip)
3) Install Strimzi operator
4) Deploy the Kafka components: [kafka-yamls.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4923715/kafka-yamls.zip)

**Comment by vperi1730** [comment]
OK sure, Let me go through this. I am referring to strimzi documentation for OAuth, somehow a little confused about which area to refer to there. 

Could you please assist me on which portion I have to read through to develop some understanding.

**Comment by scholzj** [comment]
I'm not sure there is any single specific area. The authentication docs are around with the components docs etc.
