### ISSUE TITLE
Removing Zookeeper dependency from topic operator 

### ISSUE THREAD

**Issue by colemast** [strimzi/strimzi-kafka-operator#3450]
I appreciate this has been asked in [issue 2873](https://github.com/strimzi/strimzi-kafka-operator/issues/2873), but is there any hard reason for the dependency on Zookeeper for the topic operator. Managed Kafka services such as Confluent Cloud don't expose Zookeeper, meaning we can't use the operator. Would it not be possible to use the KafkaAdmin client to get topic configuration if that is the primary use of Zookeeper?

**Comment by scholzj** [comment]
The Topic Operator is using Zookeeper for two different things:
* Storing its own information about topics for a three-way-diff which is needed for the bi-directional synchronisation. This is currently as part of the preparation for Zookeeper removal being rewritten to use Kafka in #3405 
* Getting watch information when topics are created, changed or removed from Kafka. AFAIK there is currently no replacement for this functionality. You could of course poll periodically with Admin API for topics. But that would be more complicated to implement since you would not so easily detect which changes were done first and cannot diff it so easily for example. It would also put more load on Kafka etc.

I know there are users using the Topic Operator with some managed services - for example with Amazon MSK. But to be honest, it is not our main focus. Our main focus is to use Strimzi to run Kafka on Kubernetes and the Topic Operator is just a small part of it. It is great if some of the sub-components work also with other Kafka installations but it is basically a side-effect and not the main intention.
