### ISSUE TITLE
[Question] Invalid custom resource configuration causes locks to be held until timeout, any way around this?

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#3478]
During development an invalid custom resource which causes a set of pods to never go ready can cause the operator to hang waiting till the readiness check timeout for various components. 
If I then fix this, the reconcile will be triggered but the lock will be fail to be acquired as the other reconcile is still running.
Normally I fix this by deleting the operator and this triggers a fresh reconcile on the corrected resource. Is there however a way to force all locks to be dropped outside of a pod delete, and if not is this a good enhancement?

**Comment by scholzj** [comment]
The locks will timeout. All you need to do is to wait. Forcing the logs to be released would not be trivial because it is not about releasing the logs. It is about stopping the ongoing reconciliations. Doing that could also cause disruption when it is terminated in a wrong place. So I do not think it is a good idea. If you want, you can also for development change the default 5 minute timeout to something shorter.

**Comment by samuel-hawker** [comment]
Thanks Jakub, I assumed the answer would be something like this..
Thanks for answering.
