### ISSUE TITLE
[Question] ...  with Kafka/Entity operator Strimzi 0.17.0 amd kafka version 2.4.0 

### ISSUE THREAD

**Issue by shantpschauhan** [strimzi/strimzi-kafka-operator#3506]
We are using Strimzi 0.17.0 amd kafka version 2.4.0 [Question] ...  1: Use case: To run multiple kafka cluster in same namespace. Is there any issue to do it or if any precaution is required.                                                                                                                   2: if we need user and topic through entity operator with kafka cluster deployment.  Is this mandatory to have entity operator for each kafka cluster deployed in the same namespace (i,e 3 kafka cluster deployment is having 3 entity operators.). as the entity operator scope is to watch all user/topic Custom resources in a namespace.                                                                                   3: Is this possible to run only 1 Entity operator that can take care for all user/topic custom resource for different kafka cluster deployed in same namespace.

**Comment by shantpschauhan** [comment]
I have updated my question. I would appreciate if i can get answer for the 3 questions asked.

**Comment by scholzj** [comment]
> To run multiple kafka cluster in same namespace. Is there any issue to do it or if any precaution is required.

Running 2 Kafka clusters is ok. But if you plan to have also topics and users in the same namespace, you will be unable to use them with both cluster. For example, if you create KafkaUser named `joe` for Cluster A, you will not be able to create user `joe` for Cluster B because the KAfkaUser resource with the name `joe` will already exist. The same problem will be with Kafka topics.

Normally, unless you really have some strong reason for it, I would recommend you to use separate namespaces.

> if we need user and topic through entity operator with kafka cluster deployment. Is this mandatory to have entity operator for each kafka cluster deployed in the same namespace (i,e 3 kafka cluster deployment is having 3 entity operators.). as the entity operator scope is to watch all user/topic Custom resources in a namespace.

Using the Entity Operator is not mandatory in general. But the Topic and User Operator are always configured to work only with one cluster. So if you want you can disable them - but the ones from other cluster will not be able to replace them. The Topic and User Operators are using a special label to watch for and will not watch all KafkaTopic or KafkaUser resources. The resource needs to have the cluster label to be handled by the operator:
* https://strimzi.io/docs/operators/latest/full/using.html#identifying_a_kafka_cluster_for_user_handling
* https://strimzi.io/docs/operators/latest/full/using.html#identifying_a_kafka_cluster_for_topic_handling

And this is why you need entity operator per cluster.

> Is this possible to run only 1 Entity operator that can take care for all user/topic custom resource for different kafka cluster deployed in same namespace.

As answered above, not, it is not possible.

**Comment by shantpschauhan** [comment]
Thanks scholzj  to provide clarity on my raised question.

**Comment by shantpschauhan** [comment]
One more quick question... is this possible to configure the replicas of any partition on a specific brokers by using the topic custom resource while creating the topics using entity operator.

**Comment by scholzj** [comment]
No, that is not possible.

**Comment by shantpschauhan** [comment]
Thanks @scholzj , appreciate your prompt response.

**Comment by shantpschauhan** [comment]
Hello @scholzj  i know this thread is already closed. and as you mentioned that its not possible as of now.
But just wants to quick check if there is any plan to release below ask in any future release of the strimzi ?
Feature ask is :
"is this possible to configure the replicas of any partition on a specific brokers by using the topic custom resource while creating the topics using entity operator. In kafka i think we can do this but can we do this while using topic CR using operatores..?"

**Comment by scholzj** [comment]
You can do this in Kafka ... but I do not think it fits well into the declarative model. In the imperative model (i.e. calling the _create topic_command) you specify it once, it is created and that is it. In the declarative model, you specify it in the KafkaTopic CR and it stays there and probably should be followed even after the topic is created (i.e. you should be able to edit it etc.). But it IMHO does not fit well with well with the Cruise Control (which might want to move it differently) and even with Cruise Control switched off, any changes would be hard to do.

So I think you need to think through the whole lifecycle of the KafkaTopic CR and how would it be used during it since the topic creation is just one small part of it.
