### ISSUE TITLE
Tests with invalid cluster CMs

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#353]
The should have tests for the AssemblyOperators where they try to reconcile with an invalid CM (e.g. absent storage key, or storage lacking a type). In each case we at least need a meaningful log message at ERROR level. Optionally we might want to publish a K8s `Event`.

**Comment by samuel-hawker** [comment]
I _think_ for the most part this has been implemented. We have warnings for invalid configurations, as well as a variety of assertions at run time and at the CRD level to ensure that a custom resource is valid.
Is there anything left outstanding on this?

I suggest due to the age of this issue if there is any outstanding pieces we create new issues for each specific potential mis-configuration scenario.

**Comment by stanlyDoge** [comment]
Yes, I believe the main piece of this is implemented in `io/strimzi/api/kafka/model/KafkaCrdIT.java`

**Comment by tombentley** [comment]
I think we have adequate coverage of this now.
