### ISSUE TITLE
[Question] Following the quick start guide, cannot connect to Kafka Broker

### ISSUE THREAD

**Issue by Velektron** [strimzi/strimzi-kafka-operator#3576]
Hey guys !

I'm trying to get everything up and running following the Quick Start Guide and I've notived two things

1) There's a typo in steps 2.3.5 
Edit the install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml file and set the STRIMZI_NAMESPACE environment variable to the namespace my-kafka-project.

The file should be 050-Deployment-strimzi-cluster-operator.yaml

2) I'm at the step trying to connect with the produce/consumer console and I kept on getting the following error:
[2020-09-01 05:46:19,703] WARN [Producer clientId=console-producer] Connection to node -1 (/172.17.0.2:32332) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2020-09-01 05:46:19,704] WARN [Producer clientId=console-producer] Bootstrap broker 172.17.0.2:32332 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)

This is what I'm getting when running the kubectl command to get the information:

λ kubectl get service my-cluster-kafka-external-bootstrap -n my-kafka-project -o=jsonpath='{.spec.ports[0].nodePort}{\"\n\"}'
32332

λ kubectl get node -o json
"status": {
                "addresses": [
                    {
                        "address": "172.17.0.2",
                        "type": "InternalIP"
                    },
                    {
                        "address": "minikube",
                        "type": "Hostname"
                    }
                ]

Same thing if i try localhost, am i missing something?

Thanks :)

**Comment by scholzj** [comment]
> There's a typo in steps 2.3.5
Edit the install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml file and set the STRIMZI_NAMESPACE environment variable to the namespace my-kafka-project.

Are you reading the right doc for the right version? The 0.19 docs (last stable release - https://strimzi.io/docs/operators/latest/quickstart.html#proc-install-product-str) have 050-.... The master docs have 060-... because it is changed in master (but not yet released).

> I'm at the step trying to connect with the produce/consumer console and I kept on getting the following error

Can you do something like `telnet 172.17.0.2 32332`? To connect to the node port, the worker node needs to be accessible. MAybe yours for some reason isn't. If it isn't available, can you share some more details about your environment? OR, Minikube version, virtualization type etc.?

**Comment by Velektron** [comment]
Hello, I was reading the master and not the current sorry about that. 

Here's some more information, this is the minikube version:

```
minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5-dirty
```

I'm on Windows 10 also

```
λ minikube ip
127.0.0.1

λ ssh 127.0.0.1 -p 30372
ssh_exchange_identification: Connection closed by remote host
```

Which seems to indicate that I can connect to it and the following WARN pops up in the log:
```
2020-09-01 17:42:37,705 WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(EXTERNAL-9094)-PLAINTEXT-10]
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1397966893 larger than 104857600)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:448)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:398)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
        at kafka.network.Processor.poll(SocketServer.scala:861)
        at kafka.network.Processor.run(SocketServer.scala:760)
        at java.base/java.lang.Thread.run(Thread.java:834)```

If there's anything else you'd like to know let me know :) 

Thanks again!

**Comment by Velektron** [comment]
Forgot to mention, using docker hyper-v as driver.

**Comment by scholzj** [comment]
Hmm, I do not have Windows to try it. It seems a bit weird to me that 127.0.0.1 works. But if it does, you can try something like this (https://strimzi.io/docs/operators/latest/full/using.html#con-kafka-broker-external-listeners-addresses-deployment-configuration-kafka):

```yaml
  external:
    type: nodeport
    tls: false
    overrides:
      brokers:
      - broker: 0
        advertisedHost: 127.0.0.1
```

and then try to connect with the Kafka client to `127.0.0.1:<nodeport>`.

**Comment by Velektron** [comment]
Hey guys, just to let you know, I've deployed the whole thing on a real kubernetes cluster and it works without any problem. I'm guessing the issue came from my minikube setup.

**Comment by Cshanmukh80** [comment]
**I AM TRYING TO SET UP SSL CONNECTION TO STRIMZI KAFKA WITH SUPPORTING OF THE STRIMZI OPERATOR**

The below is the yaml file of the kafka cluster
[kafka-persistent-yaml-file.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6129712/kafka-persistent-yaml-file.zip)

**my server.properties**

security.protocol=SSL
ssl.truststore.location=/tmp/kafka/kafka.truststore.jks
ssl.truststore.password=kafka123
ssl.keystore.location=/tmp/kafka/kafka.keystore.jks
ssl.keystore.password=kafka123
ssl.enabled.protocols=TLSv1.2
ssl.endpoint.identification.algorithm=
ssl.cipher.suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
ssl.protocol=TLSv1.2

**my service pod details**

![Screenshot from 2021-03-12 12-37-07](https://user-images.githubusercontent.com/80450247/110935652-ba8a0b80-8355-11eb-97cd-6ea37ac07b9a.png)

Even i have tried to edit the service port number of kafka with 9093 but it is not updating

**i am getting below error**

![Screenshot from 2021-03-12 12-34-22](https://user-images.githubusercontent.com/80450247/110935733-d392bc80-8355-11eb-82df-84991d7c80c8.png)

can anyone please help me early since i need this for my project

**Comment by scholzj** [comment]
@Cshanmukh80 Please stop commenting on other non-related issues and open a new discussion as I already suggested yesterday
