### ISSUE TITLE
[Question] What do you mean by "support for scale subresource" in v0.19.0?

### ISSUE THREAD

**Issue by mikekamornikov** [strimzi/strimzi-kafka-operator#3646]
From v0.19.0 changelog:
```
Add support for scale subresource to make scaling of following resources easier:
- KafkaConnect
- KafkaConnectS2I
- KafkaBridge
- KafkaMirrorMaker
- KafkaMirrorMaker2
- KafkaConnector
```
I wonder how exactly scaling for `KafkaConnect` kind differs in v0.19.0. What in general "scaling" means for `KafkaConnector` kind?
Could you point me to exact PRs or commits? Whatever I found myself doesn't answer to questions above.

**Comment by scholzj** [comment]
The means that we implemented support for the Kubernetes `scale` subresource in our CRDs: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource

Thanks to that you can use the `.../scale` endpoint on the Kube API server or do `kubectl scale kafkaconnect --replicas=3`. For Kafka Connect, Bridge, Mirror Maker etc. it changes the number of replicas. For KafkaConnector, it changes the number of tasks.

FYI: IIRC there were some bugs in it in 0.19 which will be fixed in 0.20.
