### ISSUE TITLE
[Question] Update of package maven/dependencies

### ISSUE THREAD

**Issue by reinaldo-pinto** [strimzi/strimzi-kafka-operator#3669]
Hi, we use the version strimzi/operator:0.19.0 (and latest), we need to update (for questions of security) these libs:

```
snakeyaml-1.24  - path /opt/strimzi/lib/org.yaml.snakeyaml-1.24.jar
keycloak-core-10.0.0 - path /opt/strimzi/lib/org.keycloak.keycloak-core-10.0.0.jar

```
To version:
```
>= snakeyaml-1.26
>= keycloak-core-11.0.0
```
Is there any way to update these dependencies?
Thank you.

**Comment by scholzj** [comment]
If you need to fix them privately in 0.19.0, you would need to get the source, update the dependencies and rebuild the project.

For updating them in master, I would need to find out what is using them. I'm quite sure the Keycloak would be a transitive dependency for the [OAuth library](https://github.com/strimzi/strimzi-kafka-oauth). So we should fix it there first and do 0.6.1 release. For SnakeYAML I would need to find out first how do we pull it in.

**Comment by reinaldo-pinto** [comment]
@scholzj, exactly, will need build. But I did not find this dependencies in some file pom.
Do you have a procedure/readme for that ??
I think these are dependencies of dependencies. 

Here the Strimzi, not have integration with other services Auth/Keycloak.

**Comment by scholzj** [comment]
Yes, the pom.xml in the root repo is the main pom file with the dependencies for the operator. The dependencies you listed will be transitive (i.e. dependency of another dependency). For example Keycloak will be dependency of the strimzi-kafka-oauth library (https://github.com/strimzi/strimzi-kafka-operator/blob/030f7b8946b1598b830783002ec2396a98b1dc4a/pom.xml#L639). Not completely sure what pulls in SnakeYAML - probably Jackson of Fabric8 Kube client. So you would need to exclude the transitive dependency (just search for `exclusions` - there are already some other examples in the pom.xml) and include it separately in the new version. In general, there is no guarantee that this would workout of the box without any code changes, but you can try it. The main pom.xml has all the dependencies for the operator image.

The Kafka images contain Kafka as downloaded from Kafka website + some additional libraries. The pom.xml files defining these libraries are here: https://github.com/strimzi/strimzi-kafka-operator/tree/master/docker-images/kafka/kafka-thirdparty-libs ... the OAuth / Keycloak JARs are there for sure as well. So you would need to do the same here.

The developer docs are here: https://github.com/strimzi/strimzi-kafka-operator/tree/master/development-docs ... I do not think they tell exactly how to update some dependnecy since it is more or less standard Java stuff. But they for sure should help with building the project.

**Comment by reinaldo-pinto** [comment]
Hi @scholzj, thanks for your help.

I see that some versions, have been updated.
For example:
```<keycloak.version>11.0.2</keycloak.version>``` https://github.com/strimzi/strimzi-kafka-oauth/blob/master/pom.xml#L88

Exist an issue [CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18640) in 4.10.3.
This version resolved ```<snakeyaml.version>1.26</snakeyaml.version>``` https://github.com/fabric8io/kubernetes-client/blob/master/pom.xml#L116
I see that need change paths and route of somes classes in Java [Note](https://github.com/fabric8io/kubernetes-client/releases/tag/v4.11.0#Note). 
Already have some preview to integration this version kubernetes-client to latest (4.11.1)?? 

Other [CVE ](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15824) this  version  kotlin-stdlib_kotlin-stdlib (1.3.50), do you know which lib uses this package ?? And if exist plan to update ??

Thank you.

**Comment by scholzj** [comment]
You can use `mvn dependency:tree` to find out where do the different dependencies come from. Please keep also in mind that it is not always possible to override the transitive dependencies easily.

**Comment by reinaldo-pinto** [comment]
Hi @scholzj , I will close it is question. 
Thank you for all help.
