### ISSUE TITLE
[Enhancement] Show LastKafka Offset and Current Processing Offset in "kubectl get kt"

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3670]
**Is your feature request related to a problem? Please describe.**
Problem is I want to use kubectl to see the current status of the topic.

**Describe the solution you'd like**
Solution is Kafka Status Resource having the LastKafkaOffset and CurrentProcessing Offset infos

**Describe alternatives you've considered**
Alernatives is use some other tool.

**Additional context**
```bash
$ kubectl get kt
```
| NAME             | PARTITIONS | REPLICATION FACTOR | LAST KAFKAOFFSET       |CURRENT KAFKAOFFSET|
| ------------- | ------------- |------------- |------------- |------------- |
| topic  | 50 | 3 | 9619 | 2045

**Comment by scholzj** [comment]
In general, I'm not sure this is such a good idea. First of all, the offset is _per partition_ and not _per topic_. So even if we add it to the status, it would not fit in as in your description because it would be a map or array. So you would be able to get it with `kubectl get kt my-topic -o yaml` but not with `kubectl get kt`. Second, the offset is changing for many topics all the time so the operator would be basically constantly updating the resources and putting a lot of load on the Kube APIs. I think this is much better handled by the existing Prometheus metrics where these are already available.

**Comment by alok87** [comment]
Prometheus metrics seems the right way then. Thanks.
