### ISSUE TITLE
Can we trace a message using the Kafka message key from Jaeger

### ISSUE THREAD

**Issue by eazhilan-nagarajan** [strimzi/strimzi-kafka-operator#3673]
Hi there,

I'm reaching out to you guys again for some more help.

We have setup data pipelines using Kafka, Kafka Connect and for disaster recovery we copy data to a different cluster using MirrorMaker 2. This is all good but there comes a need to trace the data from SOURCE -> KAFKA -> TARGET, read the article [strimzi-apache-kafka-and-tracing](https://strimzi.io/blog/2019/10/08/strimzi-apache-kafka-and-tracing/) which was helpful in setting up trace for Kafka Connect and tried querying from Jaeger UI. I was able to see all the messages as Spans in the UI but I'm wondering if there is a mechanism to trace a specific message right from the source till target! May be can we use the message key to trace?

Found in some other article that we can setup custom tags (like transaction ID) and then we query using these tags but this was for a Producer/ Consumer example. Kindly let me if we can set custom tags from either Kafka message headers or from Kafka message key for the data that flows through Connectors and MirrorMaker?

Similar to the below one:
![image](https://user-images.githubusercontent.com/16080277/93571070-39e4e680-f994-11ea-9cbc-042aecdcbce8.png)
![image](https://user-images.githubusercontent.com/16080277/93571111-4a955c80-f994-11ea-9d6e-7f88f712b344.png)

Thanks,
Eazhilan

**Comment by scholzj** [comment]
I do not think you can add tags to the traces when using the interceptors which is how the tracing is done in Kafka Connect. So that would probably not help. Querying the message based on trace ID should IMHO be possible - you can find out the trace id from the message headers. But it would depend a lot on your sampling configuration. In many cases you configure the sampling to send just every Nth message or something like that to Jaeger. So with that, it will have just small part of your messages and you cannot take any random trace ID and find it. You would need to use the sampling of all messages, but tht can get very expensive in some high throughput system.

**Comment by eazhilan-nagarajan** [comment]
Hey, thanks for the explanation. Sorry, couldn't follow up, last week had been bit hectic. We have pipelines sending around 200 - 300 per second and I believe sampling every single message can be very expensive, not very sure though.

I was hoping to use Jager to trace messages from source till target system with message key, now that I know Jager may not be an option can you suggest any tool or framework which could help us with tracing every single message that goes through the connect framework (i.e. through the pipelines)?

Thanks.

**Comment by scholzj** [comment]
I'm not aware of any such tool I'm afraid. The tracing is indeed more design for following message flows than to trace every message individually.

**Comment by eazhilan-nagarajan** [comment]
Thanks @scholzj, that makes sense. I looked at Jaeger with a different perspective. I really appreciate your help.

Thanks again.
