### ISSUE TITLE
Log levels in CC and TC should be configurable through environment variables

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#368]
Currently, the log level of both controllers is configurable only in the file before building the Docker image. It should be possible to change the log level using environment variable.

**Comment by tombentley** [comment]
AFAICS this is really awkward to achieve using log4j 1.2, because is only supports property substitution using system properties, not environment variables. So we would end up jumping through hoops to set `JAVA_OPTS` (consumed by `launch_java.sh`) with a `-D` option. I think it might just be cleaner to switch to a logging implementation that supported env var interpolation OOTB (both logback and log4j 2 can do this). Also log4j 1.2 is no longer maintained.

**Comment by scholzj** [comment]
Most of the work has been already done. The only missing thing is to add support for configuring Topic Operator log level from the Kafka cluster CRD.

**Comment by scholzj** [comment]
This should be now done for both Topic and User Operators. I will close this issue.
