### ISSUE TITLE
[Question] Support for multiple cluster operators

### ISSUE THREAD

**Issue by g30rg3-stoica** [strimzi/strimzi-kafka-operator#3702]
Hi,

At the company i work with we are facing the problem of maintaining multiple kafka clusters that are not using a common broker version.
We are planning to migrate to Strimzi managed clusters however we do not want to restrict the broker version and we would also like increased flexibility when it comes to upgrading broker versions.

Given that the supported Kafka version is currently bound to the operator version i'd like to know if a multi-operator deployment will be on the roadmap.

Concretely i was thinking of a model where multiple cluster operator versions would coexist in the same k8s cluster and manage different kafka clusters ( one or more per operator). This would allow decoupling operations on kafka clusters that serve different parts of the business.

**Comment by scholzj** [comment]
There is IMHO nothing in Strimzi it self what prevents you to use multiple operators in single cluster. The main limitations are in Kubernetes which can have for example only one version of CRD installed. Until there is proper multi-tenancy support this will always cause complications. 

Today you can deal with it by installing multiple versions of the operator for different namespaces while keeping always the cluster roles and CRDs of the newest version you use. Through there is no guarantee that this will work in the future (or to be more precise, it might depend on how many different versions an how old you need to run).

**Comment by g30rg3-stoica** [comment]
Thank you. This answers my question.

**Comment by rk3rn3r** [comment]
@scholzj does #3845 help with that now?

**Comment by scholzj** [comment]
@rk3rn3r Only partially I'm afraid. 

It can remove the contention around ClusterRoles, but at the price of disabling some features (rack awareness, access to the cluster using node ports, storage resizing). So that might help for some development use-cases, but probably not for production clusters where for example rack-awareness is important and cannot be achieved without ClusterRoles / ClusterRoleBindings.

Also, the CRDs are cluster scoped on Kubernetes level and there is nothing we can do about it. So that remains as another issue.

**Comment by rk3rn3r** [comment]
I see. Yes, as long as CRDs aren't versioned there are issues with it. Thx for the clarification!

**Comment by scholzj** [comment]
The CRDs are way more complicated than just versioning.
