### ISSUE TITLE
[Enhancement] kafka-agent option: wait for underreplicatedpartitions to be 0 for safer rolling restarts

### ISSUE THREAD

**Issue by gutmensch** [strimzi/strimzi-kafka-operator#3749]
**Is your feature request related to a problem? Please describe.**
After looking deeper into the readiness probing mechanism provided by the kafka-agent snippet I am almost 100% sure that pod restarts still _can_ be disruptive for clusters, since the BrokerState==3 alone does not guarantee fully (re)replicated partitions, when a pod is marked ready for traffic and the next one will be killed. As far as I can see in the kafka source code the ReplicaManager is started, but it is unclear at which point it will have succeeded to be "up-to-date" again. In turn this can cause offline partitions and potential data loss (we have observed offline partitions today while upgrading strimzi last release clusters indeed). If this estimation is wrong I'd be happy to hear explanations, how ReplicaManager and BrokerState are possibly correlated. 

**Describe the solution you'd like**
I am proposing a solution to let kafka-agent additionally optionally check for the underReplicatedPartitions metric from the ReplicaManager to be 0 before it renders the pod as ready for kubernetes and before the next pod is killed. From my experience with kafka this should work very well with well-setup topic parameters (rf=2+). This could also be wrapped in a sensible timeout, so that it waits e.g. max. 15 mins to re-replicate until 0, because there might be use-cases, when the cluster is in general broken or topics with rf=1 are not allowing 100% re-replication.

**Describe alternatives you've considered**
Alternatives are to my knowledge e.g. to increase the initialDelaySeconds on the readiness probe, which is at best a guesswork solution and looks pretty error-prone. Also one could think about very high broker numbers and very high replication factors to circumvent this issue, but this does not seem to be very efficient either. We are for instance running pretty small clusters for simple messaging use-cases (5 brokers, rf=3).

**Additional context**
Please see attached example of the idea, which is just an untested draft to demonstrate what I mean with this feature request. 
[kafka-agent-wait-for-isr.patch.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5329742/kafka-agent-wait-for-isr.patch.txt)

**Comment by scholzj** [comment]
You are right that the kafka-agent does not guarantee this. But we do not expect it to guarantee it. Any rolling updates are driven by the cluster operator which has additional checks for things like ISR, under-replicated topics etc. I think implementing this in the readiness probe goes a bit against its semantic since for example the fact whether all partitions are in sync etc. does not necessarily mean that the pod is not ready to handle clients (partitions not in sync will not be leaders anyway).

**Comment by gutmensch** [comment]
Thank you for the promptly feedback @scholzj !

I do agree that the semantics of the kubernetes readiness probe pretty much match BrokerState==3 and not necessarily any further "status checks" and in general I would also keep it like it currently works, because most people probably have messaging fan-in/fan-out pipelines, large clusters or high replication factors, however, I would also argue the following:

The main purpose for running a Kafka _cluster_ is IMO to achieve a level of disruption-free service and HA/failoverability. If I'm OTOH willing to accept that partitions go offline and producer/consumers are disrupted during miscellaneous processes or data is potentially lost I would wonder why I would ever bother running a complete cluster, because it does not give any benefit over a single node which I manually restart and cause a short downtime. So, while the semantics of the readiness probe are matching better what you described, the behaviour here somehow violates POLA for me in a sense that my cluster is not really high available during system operations.

Also partitions being offline for the time until a pod restarted in kubernetes (depending on your resources and it's a jvm service...) causes quite some delay in the worst case, which is not suitable for some event driven architecture, where you want to minimize the leader election and possible unavailability of a partition, no?

Either way, good discussion, thanks again. @scholzj : Could you please point me to the mentioned code of "cluster operator which has additional checks for things like ISR"? I'm curious if I might have missed some basic piece of understanding here, how the updates are run.

**Comment by scholzj** [comment]
> The main purpose for running a Kafka cluster is IMO to achieve a level of disruption-free service and HA/failoverability ...

I do not argue against that. But there are different ways to achieve that.

> Could you please point me to the mentioned code of "cluster operator which has additional checks for things like ISR"? I'm curious if I might have missed some basic piece of understanding here, how the updates are run.

This is probably the best start: https://github.com/strimzi/strimzi-kafka-operator/blob/758ec643ad2c99d7b532302a70916ad713b219ed/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java

**Comment by gutmensch** [comment]
@scholzj Thanks for the valuable input! I think we found our problem by not configuring `min.insync.replicas` per topic correctly, which is still the default 1 (and which caused the KafkaAvailability to not being able to kick in as it would have probably done otherwise!

Only a minor suggestion - maybe it would warrant to throw a WARN here https://github.com/strimzi/strimzi-kafka-operator/blob/4374ba545435e54fde2bc63718f2ded574d0f90b/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailability.java#L125 in case minIsr=1 and replicas=1, because as far as I understand this is the moment when the partition is not only underreplicated but even offline when the resp. broker pod restarts.

Thanks for your support, issue can be closed as far as I'm concerned!

**Comment by PaulLiang1** [comment]
Hi @scholzj ,

Sorry for replying on a closed issue. 

We run into something similar to this issue, where the difference is that when the restart is not initialized by Operator, but rather by k8s when the underlying nodes are being replaced/restarted.
Even with a PDB of max 1 unavailable, we still sometimes observed offline partitions, where our best understand on what happened is that:

- Our config is: Brokers -> 5, Replicas -> 3, mISR -> 2, ack = all;
- Node replacement caused STS is perform rolling restart, resulting a pod being stop / started ;
- New pod is reported to be ready;
- Without knowing/waiting for replicas on newly restarted pod to be in sync ; STS takes down a new pod (as from its POV everything is ready), this essentially takes down 2 Pods, and could violates the mISR/replicas settings in some cases and causes offline partitions;
- ...

----
There were a few mitigations we could think of:
- Increase the numbers of brokers/replicas to make it less likely to happen;
- Increase the initDelay on the probes to give new started broker more chance to sync up;

- (Something with much bigger change) Potentially a custom STS controller that would only continue rolling upgrade if a certain stable state is reached (all partitions synced up in this case)? 


Like to hear your thoughts, 

Regards, 
Paul

**Comment by scholzj** [comment]
I wrote a little utility to help with node draining which should allow ou to set the `maxUnavailable` in PDB to `0` and use the utility and the Strimzi operator to trigger the movements of the brokers more cleanly. You can find it here right now: https://github.com/scholzj/strimzi-cistic-odpadu ... you can help to test this. (If we manage to test this and see that it works well we can move it under the main Strimzi project)

**Comment by davidballano** [comment]
Hi guys,

Sorry to post on this closed ticket.

As mentioned, when the operator drives a rolling restart, the rolling restart is done in a controlled manner via the operator algorithms taking into account under replicated partitions (URP) and  "min.insync.replicas".

The problem is when the rolling restart is driven by something other than the operator, like k8s upgrades or rolling restarts.

As stated above, depending on the configuration of the producers and topics, you could end up in a situation where producers cannot produce to a Kafka cluster.

Drain cleaner is the workaround recommended for this situation. 
Could the operator manage this situation instead of having a separate deployment?

Maybe the operator could: 

- dynamically change podDisruptionBudget maxUnavailable to 0 when there is an unavailable Kafka broker, and there are URP.

Ceph is doing something similar with their operator: https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md

Looking forward to your reply; thanks.

**Comment by scholzj** [comment]
The operator does not constantly watch the Kafka brokers - to switch the PDB on and off it would need to set there and constantly poll the Kafka brokers for the state. I wonder what the load of that will be.

And I don't think any changes to the Kafka Agent really solve this:
* You cannot base it on the state of the other pods because that completely breaks the semantics, but without that, you actually don't know whether the next broker can be rolled.
* Even if you base it only on the local state of given broker, there are so many situations when replicas are for a long time not in sync that the operator would in many cases become completely useless.

That is why the [Drain Cleaner project[(https://github.com/strimzi/drain-cleaner) exists to capture the evictions and roll the pods safely without breaking the availability.
