### ISSUE TITLE
do Prometheus operator PodMonitors deploy automatically through strimzi-kafka-operator? (0.20.0-rc1)

### ISSUE THREAD

**Issue by azhang** [strimzi/strimzi-kafka-operator#3810]
currently using 0.20.0-rc1

I've enabled metrics in my Kafka resource file but it seems no podmonitors or servicemonitors are created. Is that the intended behavior? If so, what is the reasoning?

Side note about 0.20.0-rc1: strimzi CRDs weren't created either upon helm deploy, unlike in 0.19.0.

**Comment by scholzj** [comment]
This in the expected behaviour. You have to create the PodMonitors and ServiceMonitors your self.

TBH, most of the Helm Chart work was always contributed by users and we have only little expertise in it. So I don't know why it does not deploy the CRDs. I don't know whether you tried the Helm2 Chart or the Helm3 Chart but I do not think there were any major changes to them since 0.19.0.

**Comment by azhang** [comment]
Gotcha, thanks! If 0.20.0 final is ultimately released without the CRDs I will make another issue/PR.

**Comment by scholzj** [comment]
0.20 will for sure still use the non-structural schemas as it will be the last version to support Kube 1.11. But afterwards we will move to it.
