### ISSUE TITLE
[Question] CRD on top of strimzi's CRD

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3916]
We want to embed the Strimzi's Kafka connect and kafka connector CRD in the another CRD we are writing.

We are writing the other CRD in golang. Is it possible to embed Strimzi spec in Golang?

**Comment by scholzj** [comment]
I think that you would need some Golang structures for the CRDs. Since Strimzi is written in Java, we do not have any right now. So I guess you would need to extend the `crd-generator` to generate not just the Java stuff, CRDs and docs but also the Go files.

I guess other alternative would be to use the dynamic Kube client (https://github.com/kubernetes/client-go/blob/master/examples/dynamic-create-update-delete-deployment/main.go) where you don't need any structures.

**Comment by alok87** [comment]
Thank you for the suggestions. Can the spec for golang be released, it would help many as most of the CRD are written in Golang.

**Comment by scholzj** [comment]
Well, as I said above, someone would need to contribute it first. And then I guess I would need to understand what released means. Does that mean a ZIP file on the release page? Or some special _Golang release process_?

**Comment by alok87** [comment]
Just a GitHub repo from where we can import the specs

**Comment by scholzj** [comment]
Yeah, that should be feasible I think.

**Comment by alok87** [comment]
If you can let me know where, I can try pushing the init code.

**Comment by scholzj** [comment]
Well, as I said, it needs to be implemented in the crd-generator: https://github.com/strimzi/strimzi-kafka-operator/tree/master/crd-generator

Then we can just figure out the right way to publish it to the other repos -> either from CI or manually at release time etc. ... but that should be the easier step.
