### ISSUE TITLE
Use third-party management tools

### ISSUE THREAD

**Issue by lanzhiwang** [strimzi/strimzi-kafka-operator#3973]
I want test third-party management tools, [CMAK, previously known as Kafka Manager](https://github.com/yahoo/CMAK)，
These tools are directly connected to zookeeper. I understand that zookeeper cannot be connected directly. 
Is my idea wrong？Or do you have suggestions on how to use these tools？

**Comment by scholzj** [comment]
ZooKeeper is not accessible. And given it will be removed from Kafka soon, any tool needing to access it will stop working s well. So you should make sure you really want to use it. 

If you want, you can use this project (not part of Strimzi, use at your own risk) to make Zookeeper accessible (and insecure): https://github.com/scholzj/zoo-entrance ... but of course even that stops working when Zoo is removed.

**Comment by lanzhiwang** [comment]
this is a problem. Most tools need to be connected to zookeeper. What tools do you use？

**Comment by scholzj** [comment]
Well, as I said - you should be careful about anything what needs connection to Zookeeper and find out what the project is doing to be ready for Kafka without Zookeeper. Otherwise you risk that you will invest into the tool and then need to find anyway something else. The plan to remove Zookeeper is known in the Kafka community for quite some time now.
