### ISSUE TITLE
[Question] ...

### ISSUE THREAD

**Issue by jadalo** [strimzi/strimzi-kafka-operator#4017]
Hello,

I would like to use an ephemeral volume mounted on  **tmpfs** to store kafka messages ( **/var/lib /kafka /data** of kafka broker). I accept to lose data in case of broker crash or restart.

K8S APIs offer the possibility to choose the medium type of our emptyDir( "Memory" for RAM). 
Is the creation of such a cluster supported by the strimzi cluster operator? If so, can you share an example please?

Version Strimzi Cluster Operator: strimzi/operator:0.20.0

Thank you!

**Comment by scholzj** [comment]
We do not support to use the emptyDir storage with Memory type. It seems like a slightly impractical choice given that Kafka has normally fairly big storage requirements. You can use the ephemeral storage which is a regular emptyDir volume.

**Comment by plachta11b** [comment]
@scholzj Could be this a practical choice when combined with the use of compacted topics? I would like to test if performance issues could be caused by PVC, that are stored on slow network storage. The whole OS is stored on the NAS too, so I expect that emptyDir does not help in this case.

**Comment by plachta11b** [comment]
Thank you. I expect that I could implement it this way: [sizeLimit](https://github.com/strimzi/strimzi-kafka-operator/commit/45998ee4cf1451f9ba7fac9bda3166a1dfb64199). In case that I would need this.

**Comment by scholzj** [comment]
If you would want to just do it for yourself and your test, it is probably easiest to hardcode it here: https://github.com/strimzi/strimzi-kafka-operator/blob/05d0c948c19ab48843b9ae42706442835547751a/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/VolumeUtils.java#L304-L310. Just keep in mind that the memory volume comes from the container memory, so you might need to configure the memory request accordingly. If you would want to contribute it, it would probably look similar to the PR. But I think it would need a proposal to figure out how the API should look like.

**Comment by sebady** [comment]
@scholzj We have another use case now for using ephemeral storage with a medium of `Memory`.  I realize this is a bit of an "exotic" and unusual volume setup but is it possible to support this in Strimzi?  I'd be glad to try to contribute the changes if this would be supported.

**Comment by scholzj** [comment]
It would be surely an API change. So it would need a proposal (https://github.com/strimzi/proposals). I do not know if it would be accepted or not. I would expect it to be pretty small change. But as I said here earlier, I do not understand the value. So quite curious what your use case is (and you might need to convince people in the proposal that it makes some sense).

**Comment by sebady** [comment]
The use case for "Memory" backed volume here is for the highly secure use case.  Basically we have some customer that has a blanket "no disk persistence" on some topic.  A proposal to set the topic retention very low (<10s) still was not acceptable to them from a security point of view.   

I agree this is an unusual (odd?) set up but is there some technical reason this can't (or shouldn't) be supported in Strimzi?

**Comment by scholzj** [comment]
> The use case for "Memory" backed volume here is for the highly secure use case. Basically we have some customer that has a blanket "no disk persistence" on some topic. A proposal to set the topic retention very low (<10s) still was not acceptable to them from a security point of view.

Yeah, the retention does not really delete the messages after 10s. So that was likely a good decision to reject it.

But TBH, I think my advice is _do not use Kafka for such data_. I do not know if there was any messaging platform designed specifically for a use-case like this. But I know that some _traditional messaging_ brokers for example have concepts of in-memory queues. Using something like that would help you avoid all the issues where you lose everything every time a pod restarts. Given you do not seem to care about reliability, you could probably also use some peer-to-peer technology which would be even more secure by leaving out the broker in the middle.

If you absolutely need to use Kafka, you can probably consider using record encryption. Either using some proxy such as Kroxylicious or using some (de)serializer in your clients to encrypt and decrypt the records. That way you get proper Kafka with its availability and reliability while the records on the broker's disk is unreadable.

> I agree this is an unusual (odd?) set up but is there some technical reason this can't (or shouldn't) be supported in Strimzi?

Well, as I said earlier, you can open a proposal and it would be voted upon.

I do not think there are any major technical issues. But every single thing like this needs to be tested, it needs to be taken care of in the next refactoring, redesign, next new feature etc. So there is a cost associated with it. Every feature also affects the user experience, number of questions and requests for help we need to deal with etc. So it is important that every feature has its use-case and is useful to significant chunk of our users. In your case, I think the technical perspective is pretty simple. But - quite frankly - the use case is in my opinion not a good idea.

But as I said, if you want, feel free to open a proposal for it. You can check the existing proposals in https://github.com/strimzi/proposals to get an idea how it should look like. The whole community can comment on it and it will be voted upon by all maintainers (i.e. it is not just about my own opinion 😉).
