### ISSUE TITLE
[Question] Why does the operator filter the labels start with 'app.kubernetes.io'? 

### ISSUE THREAD

**Issue by liu0x54** [strimzi/strimzi-kafka-operator#4039]
In the Labels class, the additionalLabels method filter the labels start with 'app.kubernetes.io', except the 'app.kubernetes.io/part-of'. Therefore user can not set the 'app.kubernetes.io/*' labels as they wish.  
In some implementations, the 'app.kubernetes.io/*' labels need to be set special value for monitor  or other purpose.
So, could the label filtering be disabled? If not, for what consideration?

**Comment by scholzj** [comment]
> In some implementations, the 'app.kubernetes.io/' labels need to be set special value for monitor or other purpose.
So, could the label filtering be disabled? If not, for what consideration?

I'm afraid this is motivated by _other implementations_ where mirroring the labels breaks things. The filtering out of them comes from requests of other users. 🤷🏻‍♂️

**Comment by maxbrunet** [comment]
Piggy backing on this question, could we make this filter customizable?

We use Argo CD which tracks resources it manages by injecting a label:
https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing
The operator forward the labels from the Kafka resource to the `kafka-init` ClusterRoleBinding, which Argo CD wants to delete since it does not manage it.  

In our case this Argo CD label is customized to `app.argoproj.io/instance` (instead of `app.kubernetes.io/instance` which we already use in our manifests).

Making the `KUBERNETES_DOMAIN` configurable could solve that:
https://github.com/strimzi/strimzi-kafka-operator/blob/192ec6a495212d3daaad31af167b5c771786648b/operator-common/src/main/java/io/strimzi/operator/common/model/Labels.java#L144

Or more flexible take a label pattern, or have a label whitelist/blacklist mechanism.

But overall, I think propagating labels is not something operators do as it creates more issues than it solves.
Maybe supporting `somethingLabels` fields would be a simpler approach, like `podLabels`, `initClusterRoleBindingLabels`...?

**Comment by scholzj** [comment]
I'm not sure I completely understand what are you asking for ... if I get it right, you would like to have `app.argoproj.io` labels filtered out as well?

**Comment by maxbrunet** [comment]
In short, yes

**Comment by scholzj** [comment]
Ok, I think that could be possible. Do you want to open a PR for it? If not, could you please open an _enhancement_ issue for it to have it tracked and we will try to get to it.

**Comment by maxbrunet** [comment]
I have created an enhancement issue #4394 as I'm not totally sure what the solution would look like yet, nor if I would have time to implement it. Thank you for your quick replies, really appreciate.

**Comment by scholzj** [comment]
Thanks for opening the issue. No worries if you cannot make a PR. We can get someone to look into it.
