### ISSUE TITLE
[Bug] ... SSL Error

### ISSUE THREAD

**Issue by yangvipguang** [strimzi/strimzi-kafka-operator#4083]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11416887/101760074-56b53400-3b15-11eb-97bb-55b96f0da231.png)
Is it a bug ?

Version: 1.20

**Comment by scholzj** [comment]
I'm sorry, but what is this?

**Comment by yangvipguang** [comment]
@scholzj     zookeeper error：
![image](https://user-images.githubusercontent.com/11416887/101854705-01bd0080-3b9d-11eb-9d0f-ac352653d750.png)

**Comment by scholzj** [comment]
I'm sorry, but from a screenshot containing 14 lines of some exception which is not even Strimzi exceptions I absolutely cannot say what the problem is. You have to share the complete log from the Zookeeper pod + ideally logs from the other components and the Kafka custom resource as well (but the full Zookeeper pod would be a start).
