### ISSUE TITLE
How to completely disable TLS, my cluster does not want to use TLS, I don't know how to configure it.

### ISSUE THREAD

**Issue by goudai** [strimzi/strimzi-kafka-operator#4235]
How to completely disable TLS, my cluster does not want to use TLS, I don't know how to configure it.

**Comment by ppatierno** [comment]
Currently, it's not possible to disable TLS between Kafka brokers and ZooKeeper nodes. You can just tune and configure TLS for accessing the cluster from clients.

**Comment by goudai** [comment]
Does my external client need a certificate to access the Kafka cluster?

**Comment by goudai** [comment]
I would like to ask what should I do after the generated CA certificate expires.

**Comment by scholzj** [comment]
This is not a bug - you should open a discussion about it instead of opening an issue: https://github.com/strimzi/strimzi-kafka-operator/discussions.

As explained by Paolo, TLs is always used for the inter-cluster communication. But you do not have to use it in the listeners for your clients - you can just set `tls: false` in the listener configuration. The CAs are automatically renewed by the operator when they expire.
