### ISSUE TITLE
Example command(s) to grant RBAC permissions to a user

### ISSUE THREAD

**Issue by kunallimaye** [strimzi/strimzi-kafka-operator#474]
# Overview
Last paragraph of _2.2 Prerequisites_ mentions highlights that user should have appropriate rights.

> In order to execute the commands in this guide, your OpenShift or Kubernetes user needs to have the rights to create and manage RBAC resources (Roles and Role Bindings).

It would be good to update the documentation to outline sample commands to grant user appropriate rights.

Hopefully the user trying to deploy `strimzi` doesn't require `cluster-admin` rights?

**Comment by scholzj** [comment]
I'm not sure there is only _one way_ how to do it. The way how to get the required rights might be very different for different clusters.

On OpenShift, you normally require cluster admin rights to deploy the Roles, because this cannot be done by the namespace / project admin. In the future this will be also needed to deploy the CRDs into the cluster.

Once these things are set up by the cluster admin, the Kafka cluster can be deployed by less privileged users. Of course - depending on your cluster setup - the rights to create Roles, ClusterRoles and Custom Resource Definitions might have been delegated by the cluster-admin also to other users. Strimzi it self doesn't need to run under cluster admin account. The privileges in our Roles are set on the "need to have" basis.

**Comment by ppatierno** [comment]
@kunallimaye Maybe that sentence can be misleading?
As @scholzj already said, the admin rights are needed for manage RBAC resources so during the "first" step which is deploying role and rolebinding related to service account(s). Then the cluster operator deployment doesn't need admin rights and the same for templates.
Of course the user without any admin rights is able to deploy the cluster ConfigMap in order to have the cluster operator deploying the related Kafka cluster.

**Comment by kunallimaye** [comment]
> I'm not sure there is only one way how to do it. The way how to get the required rights might be very different for different clusters.

Don't disagree, but a sample set to get started for a _standard_ installation would allow users to get on with it.  Instead of fishing around to see how to get the required rights.  And I agree there is no _standard_ K8S/OpenShift install, but aim should be to get the user started as quickly as possible.  Even a simple `oc adm policy add-cluster-role-to-user cluster-admin <user>` is better than hoping the user is patient enough to search around.

> On OpenShift, you normally require cluster admin rights to deploy the Roles, because this cannot be done by the namespace / project admin.

It would make sense that you need cluster admin rights to create roles at cluster level.  But I thought project owner can create project level roles - happy to be told otherwise.
I would have thought minimising dependency on cluster-admin rights should be a priority.  How would this work in a _managed_ service scenario?
Imagine multiple projects requesting various non standard requirements on cluster-admin - *admin* team becomes the bottleneck.

**Comment by scholzj** [comment]
> Don't disagree, but a sample set to get started for a standard installation would allow users to get on with it. Instead of fishing around to see how to get the required rights. And I agree there is no standard K8S/OpenShift install, but aim should be to get the user started as quickly as possible. Even a simple oc adm policy add-cluster-role-to-user cluster-admin <user> is better than hoping the user is patient enough to search around.

I agree there is a lot to improve. And PRs are always welcome ;-). We can probably list few of these in the docu.

> It would make sense that you need cluster admin rights to create roles at cluster level. But I thought project owner can create project level roles - happy to be told otherwise.

At least on OpenShift, you cannot create Roles as project admin. You need to be cluster admin. I'm not sure it is the same on Kubernetes.

> I would have thought minimising dependency on cluster-admin rights should be a priority. How would this work in a managed service scenario?

Well, you are completely right. But we do not needs these right just for fun. I'm not aware of any rights which we need for which we do not have an exact reason why we need them. This is more or less related to the Kubernetes / OpenShift design which simply doesn't allow to do everything on namespace level (CRDs are one of the examples). While namespaces are often presented as multi-tenancy feature, they do not go far enough.

> Imagine multiple projects placing various non standard requirements on cluster-admin - admin team becomes the bottleneck.

Yes, other users are facing this as well. But as I said above, there is nothing we can do about this, since we really need all these rights for some reason.

**Comment by kunallimaye** [comment]
Thanks - appreciate your feedback.

> I agree there is a lot to improve. And PRs are always welcome ;-). We can
probably list few of these in the docu.

Happy to submit `oc adm policy add-cluster-role-to-user cluster-admin
<user-id>` if that is the right one.

> Well, you are completely right. But we do not needs these right just for
fun.

Am not suggesting you do.
Is it worth considering splitting creation of roles (operators) into a
separate task so that it can be performed by _cluster-admin_?

**Comment by PaulRMellor** [comment]
Deploying Guide has a procedure for [_Designating Strimzi administrators_](https://strimzi.io/docs/operators/in-development/deploying.html#adding-users-the-strimzi-admin-role-str)
