### ISSUE TITLE
Add new external type "ClusterIP"

### ISSUE THREAD

**Issue by techmunk** [strimzi/strimzi-kafka-operator#4753]
**Is your feature request related to a problem? Please describe.**
We're running a "bare metal" kubernetes currently that does not have any loadbalancers. For most applications we use a service type of "ClusterIP", the range for which we have made routable inside our  network. The POD  network however is not routable.

It would be nice to be able to avoid the use of Nodeport/ingress and use a service type of cluster ip.

**Describe the solution you'd like**
Provide another external listener type of clusterip

**Describe alternatives you've considered**
We've considered running up metallb rather than using nodeport or an ingress, but we're unsure about doing that vs being able to just use the clusterIP.

**Comment by scholzj** [comment]
Just some sidenotes:
* I use MetalLB on my home cluster on bare-metal and it works great
* I do not think it would be an external listener per-se since ClusterIP services are internal only

I'm personally not sure we should go for this. I understand your use case. But there is you who shares the IP range, than there are other people with some special linked DNS setups, then there are people who want to use Pod IPs for similar usecases. The main concern is that if we do a special listener for everyone it will very quickly become unmaintainable.

Also, you can work around this manually I think:
* Create your own per-broker services with your own names (so that they do not conflict with the services created by the operator) - each pointing to one broker
* Deploy Kafka cluster with an internal listener and use the `advertisedHost` configuration option (see https://strimzi.io/docs/operators/latest/full/using.html#type-GenericKafkaListenerConfigurationBroker-reference) to set the IP address of the services as the advertised hostname for each broker manually.

**Comment by techmunk** [comment]
@scholzj Thanks for the reply. The more I've been looking into this the last hour or so, the more I think metalLB will the be the best path forward anyway. You're suggestion of manual services is also interesting though. I had been looking at the `advertisedHost` but had not quite connected that I could setup a manual service to work with it.

I'll close this request as I think you're correct. The listeners that you have right now serve most use cases, and should allow something "acceptable" for most people with a bit of extra thought and domain knowledge.
