### ISSUE TITLE
Avoid rolling updates for scale down and scale up operations 

### ISSUE THREAD

**Issue by igorcalabria** [strimzi/strimzi-kafka-operator#4913]
**Is your feature request related to a problem? Please describe.**
It would be nice if it was possible to scale the cluster up and down without also having to endure a rolling upgrade. Rolling upgrades are not the end of the world, but they are disruptive to clients and causes latency spikes(loses jit, caches are flushed, etc).  

**Describe the solution you'd like**
Scaling the cluster does not trigger a rolling upgrade 

**Additional context**
Some situations where this behavior can be dangerous:
- A cluster that needs a "urgent" scale up because it's overloaded. An unnecessary rolling upgrade can aggravate the situation 
- Big clusters with many partitions. Cleanly shutting down kafka may take some time when there are many partitions, multiply this time by the number of brokers and the rolling operation will be really long. This means that the disruption of the rolling restart will also persist for some time.

It seems that the root cause of the rolling is caused by the change in `advertised-hostnames.config`. The brokers are added or removed from this entry which changes the hash in `strimzi.io/broker-configuration-hash`. 

In https://github.com/strimzi/strimzi-kafka-operator/issues/4090 it was mentioned that there's "long story" regarding the motivation behind this. Can you guys give more context on why the brokers need to be statically added to that config? Couldn't `advertised.listeneners` be configured on a per broker basis using a dynamic script with something like `hostname -A` ?

**Comment by scholzj** [comment]
> In #4090 it was mentioned that there's "long story" regarding the motivation behind this. Can you guys give more context on why the brokers need to be statically added to that config? Couldn't advertised.listeneners be configured on a per broker basis using a dynamic script with something like hostname -A ?

There is a long story of why it works as it works today. But there is no specific motivation which would explain that it is better to do the rolling update.

To try to explain it at least a little bit:
* No, it is not enough to do `hostname -A`. There are many usecases where this is much more complicated because in many cases the advertised address has not much to do with the pod.
* Strimzi is currently using stateful set to run the broker pods. That has some advantages. But also some advantages as all the pods look the same. So it is not easy to change configuration in just one of them. There might be ways how to implement this even with statefulsets, but they will not be trivial. But we plan to look into getting rid of statefulsets which might make this a lot easier. 

Overall, this is a valid enhancement ... just not easy to implement.

**Comment by scholzj** [comment]
This is now fixed when used with the `UseStrimziPodSets` feature gate enabled.
