### ISSUE TITLE
ServiceAccount gets periodically deleted/created if CruiseControl CM metrics are used

### ISSUE THREAD

**Issue by steadyk** [strimzi/strimzi-kafka-operator#5126]
We currently use the inline metrics from the examples in our Kafka setup, which works fine. The setup uses Istio as service mesh. Since these metrics are deprecated, we want to switch to the CM metrics instead. This seems to work fine for all resources except of CruiseControl.
After we use the new `metricsConfig` there, we observed connection issues in the Istio proxy and deamon after some time of execution. This leads to a memory leakage in the Istio proxy.

If I look into the operator logs (in DEBUG mode), I can see that the operator deletes the CruiseControl ServiceAccount and recreates it in one of the following reconciliation periods. This also leads to a new created token which belongs to the SA.
The process occurs from time to time. I've noticed no fix interval, but it seems to occur at least once per hour.
I cannot see any detail on the log why the SA was deleted by the operator.

I can reproduce the behavior with the current Helm chart release and the sample CruiseControl metrics config.

So far I only have noticed this issue on CruiseControl.

**How To Reproduce**
1. Install the Helm chart with debug log level: `helm install my-release strimzi/strimzi-kafka-operator --set logLevel=DEBUG`
2. Install [CruiseControl metrics example](https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/kafka-cruise-control-metrics.yaml)
3. Watch SA of CruiseControl
4. If the SA was deleted/recreated see operator logs

**Expected behavior**
The CruiseControl ServiceAccount should be stable to avoid recreations of the SA token.

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1, 0.23.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.19.7
 - Infrastructure: Kind

**YAML files and logs**
ServiceAccountOperator logs:
```
2021-06-15 10:09:02 DEBUG ServiceAccountOperator:111 - ServiceAccount strimzi2/my-cluster-cruise-control already exists, patching it
2021-06-15 10:11:02 DEBUG ServiceAccountOperator:111 - ServiceAccount strimzi2/my-cluster-cruise-control already exists, patching it
2021-06-15 10:13:02 DEBUG ServiceAccountOperator:111 - ServiceAccount strimzi2/my-cluster-cruise-control already exists, patching it
2021-06-15 10:15:02 DEBUG ServiceAccountOperator:117 - ServiceAccount strimzi2/my-cluster-cruise-control exist, deleting it
2021-06-15 10:15:02 DEBUG ResourceSupport:148 - Opened watch io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@18071fc for evaluation of observe deletion of ServiceAccount strimzi2/my-cluster-cruise-control
2021-06-15 10:15:02 DEBUG ResourceSupport:165 - Not yet satisfied: observe deletion of ServiceAccount strimzi2/my-cluster-cruise-control
2021-06-15 10:15:02 DEBUG ResourceSupport:165 - Not yet satisfied: observe deletion of ServiceAccount strimzi2/my-cluster-cruise-control
2021-06-15 10:15:02 DEBUG ServiceAccountOperator:166 - ServiceAccount strimzi2/my-cluster-cruise-control has been deleted
2021-06-15 10:17:02 DEBUG ServiceAccountOperator:108 - ServiceAccount strimzi2/my-cluster-cruise-control does not exist, creating it
2021-06-15 10:19:02 DEBUG ServiceAccountOperator:111 - ServiceAccount strimzi2/my-cluster-cruise-control already exists, patching it
```
Full operator and CruiseControl log attached.
[strimzi-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/6654898/strimzi-operator.log)
[cruise-control.log](https://github.com/strimzi/strimzi-kafka-operator/files/6654899/cruise-control.log)

I can't find anything suspicious in the [ServiceAccountOperator](https://github.com/strimzi/strimzi-kafka-operator/blob/3b3a419dd17cac0458b2a96d3d2b6f9d47683ebe/operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceAccountOperator.java) or the [AbstractResourceOperator](https://github.com/strimzi/strimzi-kafka-operator/blob/3b3a419dd17cac0458b2a96d3d2b6f9d47683ebe/operator-common/src/main/java/io/strimzi/operator/common/operator/resource/AbstractResourceOperator.java#L81).

Does this behavior also exists on the current main branch, or was this fixed by the [SA patching changes](https://github.com/strimzi/strimzi-kafka-operator/pull/4974)?

Thanks for the help!

**Comment by scholzj** [comment]
It seems it is deleting the network policy as well (it doesn't even exist, so it is not deleted => but the operator sees that as expected). 

This seems to be because of a bug in the `getCruiseControlDescription` in `KafkaAssemblyOperator`. It returns before creating the description due to a missing return statement and the description is created asynchronously only later. So when the network policy and service account is reconciled, the description is still missing and the operator things they should be deleted because Cruise Control is not yet deployed. Later, when reconciling the deployment etc. the description is already created and they are patched. This seems to happen only sometimes for the SA and more often for the network policy which is reconciled before the SA.

I will open a PR to fix this => 0.24 release should start hopefully this week.

**Comment by steadyk** [comment]
Thanks @scholzj  for the quick analysis and explanation! 
As far as I've noticed this, it happens again and again. It there a reason why this happens for a ServiceAccount which might be available since several minutes?

**Comment by scholzj** [comment]
The reason why this relates to the new and old metrics configuration is that when using the metrics configuration from the config map, it takes more time since we need to get the Config Map content. So while the bug exists in both cases, it is much more likely to impact the service account or network policy with the config map than without it.

And at the end it is a race condition ... sometimes, the description is already available and the SA is created (or kept if it already exists). Sometimes the description is not yet ready and it results in the deletion. I guess it depends with how long the query to the Kube API server to get the config map takes.

I opened #5128 to fix this.
