### ISSUE TITLE
Upgrade kafka version from 1.1.0 to 2.0.0

### ISSUE THREAD

**Issue by moadqassem** [strimzi/strimzi-kafka-operator#514]
Is there any clear plan for upgrading the current Kafka version from 1.1.0 to 2.0.0?  
http://kafka.apache.org/20/documentation.html#upgrade

Thanks in progress.

**Comment by scholzj** [comment]
I don't think that for 2.0.0 we will provide and automatic update mechanism for running clusters. Although this is of course also on our backlog, we have right now bigger priorities around security. But Strimzi will of course add support for Kafka 2.0.0 once it is released (the documentation has been published on the site, but currently Kafka 2.0 is only in Release Candidate stage).

While and automatic upgrade might not be available at this point, it should be possible to follow the process described in Kafka docu manually. Since 0.4.0, the configuration fields are available in the ConfigMap.

**Comment by moadqassem** [comment]
Alright thank you very much, I would then close this issue now.
