### ISSUE TITLE
Cleaning useless test in KafkaAssemblyOperatorMockTest

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#516]
There is the `testResumePartialRoll` which seems to be useless. Maybe it was started and not developed anymore?

**Comment by scholzj** [comment]
This suggests that our review standards are poor :-(.

@tombentley Git blames you for it :-o. Could you advice what to do about it? Should it be completed? Or just deleted because it is tested else where? It loooks to me as if you are testing this in `PartialRollingUpdateTest` and this test can be simply removed.

**Comment by tombentley** [comment]
When it comes to reviewing tests we *do* need to improve. We need to treat test code as first-class code, which should be improved and refactored for its own sake. It would also be good if we had a test coverage report.

I think I started on `testResumePartialRoll()` and then decided the dedicated `PartialRollingUpdateTest` was necessary. If you both agree that `PartialRollingUpdateTest` has sufficient coverage then we can delete `testResumePartialRoll()`.

**Comment by scholzj** [comment]
We do not seem to have any `testResumePartialRoll` test anymore. I think this issue can be closed.
