### ISSUE TITLE
[Feature] Offline volume expansion support

### ISSUE THREAD

**Issue by almorgv** [strimzi/strimzi-kafka-operator#5234]
**Is your feature request related to a problem? Please describe.**
We use [Longhorn](https://github.com/longhorn/) as storage provider but it supports only offline volume expansion.

PVC stuck in `Resizing` state and Longhorn waits for pod shutdown and volume detachment. But strimzi waits for `FileSystemResizePending` that should come after `Resizing` and pvc can't be expanded. One way of doing it manually scale to 0 kafka brokers, wait for expansion and scale it back up.

Related issue in longhorn https://github.com/longhorn/longhorn/issues/2749

**Describe the solution you'd like**
We would like to offline expansion support feature be implemented in strimzi

**Describe alternatives you've considered**
One way of doing it manually scale to 0 kafka brokers, wait for expansion and scale it back up.

**Comment by scholzj** [comment]
My understanding from how it should work is that `FileSystemResizePending` state means basically _restart the pod to allow resizing the file system_. But AFAIK the `Resizing` state means that the volume is being resized and does not necessarily indicate that there is any action needed. That was also so far the experience I had when working with other platforms / infra. So I guess the question is how do we recognize in the operator code that the volume needs resizing? We cannot use the `Resizing` state for it because it is not what it means with most other storage types. So it sounds to me like there is some `ResizePending` state missing to indicate that the resizing needs a pod restart. So to implement this, we would need to have some reliable and simple way to detect this.

**Comment by almorgv** [comment]
Thanks for the answer. Looks fair enough. Closing and looking forward to changes in storage provider
