### ISSUE TITLE
Discrepancy Between Grafana and OpenShift Memory Metrics

### ISSUE THREAD

**Issue by sherl0cks** [strimzi/strimzi-kafka-operator#534]
I'm seeing wildly different memory metrics between OpenShift console and Grafana. The grafana dashboard was created from https://github.com/strimzi/strimzi-kafka-operator/blob/0.4.0/metrics/examples/grafana/kafka-dashboard.json. Both screenshots below are at 1 hr. I'm inclined to view the OpenShift ones as accurate, as they reflect usage (or lack there of in this case, the cluster is idle).

![screenshot from 2018-07-03 10-16-25](https://user-images.githubusercontent.com/1335137/42232020-6ddcc9b0-7eaa-11e8-8e54-91223555e788.png)
![screenshot from 2018-07-03 10-16-03](https://user-images.githubusercontent.com/1335137/42232022-6f40dfd0-7eaa-11e8-8607-506ac58f9105.png)

**Comment by sherl0cks** [comment]
I'm new to grafan, but perhaps `sum` isn't the operation we are looking for here: https://github.com/strimzi/strimzi-kafka-operator/blob/0.4.0/metrics/examples/grafana/kafka-dashboard.json#L166

**Comment by scholzj** [comment]
@ppatierno Do you have any idea?

**Comment by tombentley** [comment]
One reason is that I think the grafana graph is showing used memory rather than committed memory (see https://docs.oracle.com/javase/9/docs/api/java/lang/management/MemoryUsage.html). I assume the openshift graph is showing how much memory the container is using, which will include the committed memory of the JVM.
