### ISSUE TITLE
BYO externally signed client certificate for TLS authentication with user operator

### ISSUE THREAD

**Issue by urton** [strimzi/strimzi-kafka-operator#5347]
**Is your feature request related to a problem? Please describe.**
We have a security requirement to use customer CA issued certificates for client authentication. We will not be granted signing privileges in our customer's CA. Therefore, we currently have no way to authenticate our Kafka users via TLS. We've tried several work arounds, mainly disabling generateCertificateAuthority, setting the ca.key in our <CLUSTER>-clients-ca to an empty value, and creating/labeling a secret for our Kafka users. This gets us passed authentication, but authorization fails because the user fails to reconcile and the ACLs are never loaded. The reconiliation fails due to OpenSslCertManager errors (ie it is trying to generate certs).

**Describe the solution you'd like**
We would like to keep the user-operator enabled and BYO externally signed client certificate for TLS authentication (e.g. disable clients-ca cert gen either globally or on a per user basis)

**Describe alternatives you've considered**
We are currently falling back to scram-sha-512, but mTLS is what our CISO requires long term. We are also exploring the feasibility of disabling the user operator.

**Comment by scholzj** [comment]
TBH, I'm not sure it is wise to use mTLS authentication if you don't control the CA. You will basically have absolutely no control over who can connect to your cluster. But that is just a sidenote ... I leave that to your CISO ;-).

In 0.25 (the next release), you will be able to use `type: tls-external` authentication in the `KafkaUser` resource. That is designed exactly for this use-case, where you want to set the ACLs or quotas but generate the certificates on your own. So that might help you. (you still need to have the certificates follow the same subject as the regular certificates generated by Strimzi uses - i.e. `CN=<KafkaUserResourceName>`).

Another option you can use is to disable the User Operator completely and manage ACLs using the KAfka Admin API yourself.

**Comment by urton** [comment]
Thanks @scholzj! The tls-external sounds like what we want. Is there an eta on 0.25?

Re no control over authentication, I’m not sure I follow. The public key from the client, or the CA chain and a valid CN, would still need to be loaded in the cluster’s “trust store” regardless if the cluster was a signing CA or not correct? Granted it would be easier if our customer let us become a sub-CA, but if we did use the cluster generated certs, then our clients would also have to update their trust stores, which opens another can of worms.

I can post our broken hack if you’re interested, but I was able to authenticate with a customer issued cert matching a secret. Either way, I appreciate the quick response and I look forward to 0.25.

**Comment by scholzj** [comment]
> Re no control over authentication, I’m not sure I follow. The public key from the client, or the CA chain and a valid CN, would still need to be loaded in the cluster’s “trust store” regardless if the cluster was a signing CA or not correct? Granted it would be easier if our customer let us become a sub-CA, but if we did use the cluster generated certs, then our clients would also have to update their trust stores, which opens another can of worms.

Well, the certificate from `-clients-ca-cert` secret will be loaded into the broker truststore as _trusted CA_. That means that any certificate signed by this CA will be successfully authenticated - it does not need to be added anywhere, it will be trusted because it is signed by the trusted CA from the moment it is signed. If you don't control the CA, you do not know what certificates will be signed by it and who will use them. Also, for example in case the CA will be compromised, are you sure you will be informed about it quickly enough to remove the CA from the broker? It is not impossible, but it requires a very high trust into whoever manages the CA that they will do it securely.

**Comment by urton** [comment]
@scholzj I'm closing this issue as we got tls-external working with 0.25. We did run into #5439 however.

Cheers
