### ISSUE TITLE
[Topic Operator] Override the default topic store name

### ISSUE THREAD

**Issue by palson** [strimzi/strimzi-kafka-operator#5557]
**Is your feature request related to a problem? Please describe.**
In our company, we want to try the standalone Topic Operator to manage our topics configuration with an external Kafka server.
In our case, it is possible that several teams run their own operator against the same cluster
Then it turns out that each new operator sees existing topics in Kafka and the topic store, but does not find the corresponding CRDs and decides to remove existing topics from Kafka.

**Describe the solution you'd like**
Perhaps if it were possible to change the default topic store - `__strimzi_store_topic`, then each operator would have its own topic to store metadata.

**Describe alternatives you've considered**

**Additional context**

**Comment by scholzj** [comment]
@alesj @tombentley @sknot-rh please confirm, but I think you can already do this by setting the environment variable `STRIMZI_STORE_TOPIC` in the Topic Operator deployment. That said, I'm not sure if running multiple of them is a good idea / if it will work well.

**Comment by palson** [comment]
@scholzj 
  I agree that running multiple operators is a bad idea
  We just want to protect ourselves against the sudden removal of topics. This is too risky.
  Because anyone who has access to the cluster and wants to run their own operator can clean up the cluster.
  
  As for your suggestion - yes, with this env var the operator creates a topic with a new name. But unfortunately, this does not save topics from being deleted.
  Perhaps because of the `__strimzi-topic-operator-kstreams-topic-store-changelog` topic.
  
 It looks like my decision to override the `__strimzi_store_topic` topic name was not correct or complete

**Comment by scholzj** [comment]
There are some more options: `STRIMZI_STORE_NAME` and `STRIMZI_APPLICATION_ID` ... I guess those might change also the changelog topic.

However ... with multiple TOs each TO instance will create its own set of KafkaTopic CRs and sync it bi-directionally against Kafka. So if one of them decides to delete topic A in Kafka, the others will just follow it by design and delete the topic as well. So I do not think they protect you ... exactly the opposite ... you will have more places where something can go wrong and result in topic deletion.

If you are really afraid of deleted topics, you can also disable the deletion in Kafka (and for example temporarily enable it only from time to time when you really want to delete something).

**Comment by scholzj** [comment]
@palson Did it helped?

**Comment by palson** [comment]
@scholzj yes, it helped.
Thank you!
