### ISSUE TITLE
Bug in Pod Affinity Documentation

### ISSUE THREAD

**Issue by PhilippB21** [strimzi/strimzi-kafka-operator#5598]
**Suggestion / Problem**
When implementing AntiAffinity using the documentation, I noticed that a properties is missing there. According to the Kafka CRD definition, "podAffinityTerm" is missing there.

Incorrect documentation
```bash
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - CLUSTER-NAME-kafka
                topologyKey: "kubernetes.io/hostname"
```

This is how I think the documentation should look like:
```bash
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: strimzi.io/name
                        operator: In
                        values:
                          - CLUSTER-NAME-kafka
                  topologyKey: "kubernetes.io/hostname"
```

**Documentation Link**
Provide a link to the documentation where the bug / suggestion should be applied
https://github.com/strimzi/strimzi-kafka-operator/blob/5de178f1846fbcbd88cc77d5900248fa0e52d687/documentation/modules/configuring/proc-scheduling-brokers-on-different-worker-nodes.adoc

**Comment by scholzj** [comment]
I don't think this is the case. You can look for example here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity or directly into the spec: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#podantiaffinity-v1-core

This is a bit confusing, but the API differs for `requiredDuringSchedulingIgnoredDuringExecution` and `preferredDuringSchedulingIgnoredDuringExecution`:
* `preferredDuringSchedulingIgnoredDuringExecution` has the `podAffinityTerm`
* `requiredDuringSchedulingIgnoredDuringExecution` does not have it

So I think our docs are right because they use `requiredDuringSchedulingIgnoredDuringExecution`. I think I got confused myself once or twice by this in the past.

**Comment by PhilippB21** [comment]
Hey @scholzj,
thanks for our fast response. Learned something again :-) 

We chose `preferredDuringSchedulingIgnoredDuringExecution` and then expected it to be defined exactly the same as `requiredDuringSchedulingIgnoredDuringExecution`. 

It's really confusing, but then of course your doc is correct
