### ISSUE TITLE
Container image isn't rebuilt on repository change

### ISSUE THREAD

**Issue by gferon** [strimzi/strimzi-kafka-operator#5636]
**Describe the bug**

When updating the container image repository (`spec.build.output.image`) in a `KafkaConnect` resource, the operator reports ["Build configuration did not changed. Nothing new to build."](https://github.com/strimzi/strimzi-kafka-operator/blob/d7161c6db23d384a4e8f5ec810dbc53418ed4122/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java#L253). While reading the source code, I stumbled over the `strimzi.io/force-rebuild` annotation, which seems to be undocumented - the image rebuilt successfully afterwards.

**To Reproduce**
1. Change the build output image repository in `spec.build.output.image`
2. The operator will not trigger a rebuild (and push) of the image to the new repository

**Expected behavior**
The operator should trigger a rebuild of the image and a rolling upgrade of the connectors.

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.21
 - Infrastructure: Amazon EKS

**Comment by scholzj** [comment]
Changing the target repository does not change anything on the image. So why should it rebuild?

**Comment by gferon** [comment]
Because if it's not rebuilt, it won't be pushed to the new repository - as they're both part of the same process if I understand correctly.

**Comment by juniorz** [comment]
Another reason for rebuilding is that after removing all references to the repo from the `KafkaConnector` resource, the user expects to be able to destroy the ECR repo.

Not forcing a rebuild in order to create the image in the new ECR repo breaks that expectation, because destroying the repo would cause any scheduling of replicas in nodes that don't have the image cached to fail.

**Comment by scholzj** [comment]
Ok, that is good point. Thanks.

**Comment by gferon** [comment]
I forgot to mention that I'd be happy to (try and) contribute a fix if you'd accept it.

**Comment by scholzj** [comment]
We are always happy to accept contributions. I think the best way to fix this would be to append the information about the output to the existing build revision.

We plan to start working on the 0.26.0 release some time early next week. Is it important for you to have the fix in it? If yes, do you think you will have time for the PR to get it into it? If it is important for you and you are not sure you will be able to make it I can have a look at it as well. Otherwise I think we are fine to wait and just get it into some later release.

**Comment by gferon** [comment]
Great, I'll give it a go, then! This is not really time sensitive, as we know what to do to avoid this particular problem.
