### ISSUE TITLE
Auto-configure default replication factor in Kafka brokers

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#5681]
As discussed on the Strimzi Community call on 7th October, maybe we want to set the default replication factor in Apache Kafka clusters based on the number of replicas (e.g. using a function of `min(3, replicaCount)`).

Pros:
* Better out of the box experience?
* Might be more in sync with different Kafka settings defaulting now to `-1` (which means follow the default RF from the Kafka cluster)

Cons:
* Users might be used to the default Kafka value (1)
* Changes the behaviour for existing users

Open Points:
* Do we want this? Or is this too much of a breaking change?
* Should we then set also default minimal number of in-sync replicas to for example default RF - 1?

Side ideas:
* Having some kind of profiles which would configure different options for reliability etc. - for example "development" profile (no need for super tight reliability), "production" profile (full replication and reliability), etc.

**Comment by ppatierno** [comment]
The profile idea could be a good idea and I would assume that it's going to be a new property in the `kafka` specification. 
But because `default.replication.factor` and `min.insync.replicas` can be specified in the `spec.kafka.config` as well, we should make clear the precedence and/or logging a warning when user set them in the config while specifying a profile as well.

**Comment by scholzj** [comment]
After some follow up discussion on the community calls, this is addressed by #5916.
