### ISSUE TITLE
Unable to successfully run unit tests on Windows (excluding IT tests)

### ISSUE THREAD

**Issue by ppietruch** [strimzi/strimzi-kafka-operator#605]
Unable to successfully run basic unit tests (excluding IT tests) on Windows development environment.

Please see attached build logs for details.

Command executed was: `mvn -q clean install -DskipITs` (-X added for api module)

[crd-generator.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2205617/crd-generator.txt)
[api.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2205622/api.txt)
[topic-operator.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2205627/topic-operator.txt)
[certificate-manager.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2205636/certificate-manager.txt)
[cluster-operator.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2205662/cluster-operator.txt)

**Comment by tombentley** [comment]
The crd-generator.txt test failures might be due, in part to differing line endings between the expected and actual output of the `CrdGenerator` tool. The expected output is stored in a classpath resource in `/src/test/java`. We can probably just replace windows line endings with unix prior to making the assertion.

The api failure looks like it's a problem with running the crd generator from the maven build. Most likely this is due to file separator issues. I don't have access to a windows machine to fix these myself, but I should think appropriate use of the `File` class would likely fix it.

The certificate manager executes `openssl` as an external process, so this fails if that executable file does not exist. You can probably just disable those tests using an `Assume` on the existence of `openssl` in the `$PATH`.

At least some of the topic operator tests are failing for a similar reason: Trying to execute an external shell script. Again this test can be skipped on windows via assume.

Finally, cluster operator problem might also be a line separator problem.

**Comment by ppietruch** [comment]
Opened a PR which addresses issues in `crd-generator` and `api` modules: https://github.com/strimzi/strimzi-kafka-operator/pull/615

Once that modifications are applied TopicOperator fails in a new way. It depends on execution of reassign.sh script which obviously fails on Windows.

Attached new logs from TopicOperator's build.

[topic-operator2.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2209045/topic-operator2.txt)

**Comment by tombentley** [comment]
@ppietruch thanks for the PR (now merged).

The tests using `reassign.sh` are about checking we handle correctly all the error cases when running an external command (which will be done by the TO, which we expect to be running in a pod running linux). Thus there's no point having an equivalent test for windows. And therefore I think those tests can be ignored when running on anything that's not linux using something like `Assume.assumeTrue(System.getProperty("os.name").toLowerCase().indexOf("nux") > 0);` as the first statement in the test. But you should probably factor out that predicate into a method on `TestUtils`.

**Comment by scholzj** [comment]
Closing as suggested in #628
