### ISSUE TITLE
Cannot specify custom logging configmap

### ISSUE THREAD

**Issue by Oliver-Sellwood** [strimzi/strimzi-kafka-operator#6254]
**Describe the bug**
I am using helm to deploy the operator and trying to set a custom logging properties for the operator deployment. 

In the helm values their is a key named `logConfigMap`. I expected that by creating a configmap with my custom configuration, and then setting the value of `logConfigMap` to match that value that the default log config would be overwritten by my custom configuration.

Instead the `logConfigMap` key simply defines the name of the configmap that the helm release creates.

You can see [here](https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/templates/050-ConfigMap-strimzi-cluster-operator.yaml#L4) that the configmap name is set by the value of `logConfigMap`

This current implementation seems redundant and doesn't allow for customization of logging configuration without further manual modifications to the created configmap

**Comment by sknot-rh** [comment]
Hi.
As a workaround, you can specify name of your custom ConfigMap here: https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml#L48

**Comment by scholzj** [comment]
I'm not sure how did it looked in 2022 when this was originally raised. But today, one can use `logConfiguration` to provide a custom `log4j2.properties` file: https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/templates/050-ConfigMap-strimzi-cluster-operator.yaml#L15

@Oliver-Sellwood I know it is a long time ago since you opened this ... but do you still need this? If yes, does the above address this?

**Comment by im-konge** [comment]
Triaged on 31.10.2024: It is now 2 years since the issue was opened and Standa provided some workaround. Now with the comment from Jakub it seems that there is another way how to workaround this. So I'm closing the issue, in case that you'll find that the workaround is not working for you, please feel free to re-open this issue. Thanks.
