### ISSUE TITLE
Kafka Connector CR while describing the status should also take into account the status of Connector tasks

### ISSUE THREAD

**Issue by anand-zscaler** [strimzi/strimzi-kafka-operator#6624]
**Feature Request**
So I had created tools that check the status of the CR and if not healthy it would alert me. However, it turned out that in our case we had a Kafka Snowflake Connector which got issues with one of the tasks and I could see the Task in the Failed state however this was only caught after one of our Engineers reported it as a functional issue at their end.

**Probable/Suggested Solution**
The State of the connector should also reflect the tasks state. If one of the connector tasks reports it as a FAILED state then we should put this in the WARNINGS section with READY as True and this will allow Ops to react faster by building tools using this status.

**Workaround**
As a workaround, I am doing a `kubectl get` for the Connector CR and checking the state of each Connector task.

**Connect Logs**
`[SF_KAFKA_CONNECTOR] pipe SNOWFLAKE_KAFKA_CONNECTOR_sf_asset_hierarchy_processor_155673181_PIPE_vapaka_asset_hierarchyprocessor_1: service closed (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1) [task-thread-sf-asset-hierarchy-processor-1]
2022-03-06 17:43:52,088 INFO 
[SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:1]:close. Time: 0 seconds (com.snowflake.kafka.connector.SnowflakeSinkTask) [task-thread-sf-asset-hierarchy-processor-1]
2022-03-06 17:43:52,089 ERROR WorkerSinkTask{id=sf-asset-hierarchy-processor-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-sf-asset-hierarchy-processor-1]
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:609)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException: 
[SF_KAFKA_CONNECTOR] Exception: Failed to create table
[SF_KAFKA_CONNECTOR] Error Code: 2007
[SF_KAFKA_CONNECTOR] Detail: Failed to create table on Snowflake, please check that you have permission to do so.
[SF_KAFKA_CONNECTOR] Message: Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.`

**Status of Kafka Connector Tasks**
`aniyer@Anands-MacBook-Pro ~ % k get kctr
NAME                           CLUSTER             CONNECTOR CLASS                                        MAX TASKS   READY
sf-asset-graph-processor       snowflake-connect   com.snowflake.kafka.connector.SnowflakeSinkConnector   2           True
sf-asset-hierarchy-processor   snowflake-connect   com.snowflake.kafka.connector.SnowflakeSinkConnector   2           True`

**Status of Kafka Connector Tasks**
`connectorStatus:
    connector:
      state: RUNNING
      worker_id: 10.13.16.68:8083
    name: sf-asset-graph-processor
    tasks:
    - id: 0
      state: FAILED
      trace: "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask
        due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:609)\n\tat
        org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)\n\tat
        org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)\n\tat
        org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)\n\tat
        org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)\n\tat
        org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)\n\tat`

**Comment by katheris** [comment]
Looking into fixing this issue it seems to me that currently the Ready condition is set based on whether the reconciliation of the connector succeeded, not on whether the connector or tasks are actually running or failed.

I've got a change in a branch (https://github.com/strimzi/strimzi-kafka-operator/compare/main...katheris:strimzi-kafka-operator:6624-connector-status?expand=1) that changes this (please note it's a first draft so definitely needs cleaning up and writing tests etc). I had a couple of thoughts/questions about the potential change to make.

The change means that if a task failed you would see something like the below in the KafkaConnector status:
```
  conditions:
  - lastTransitionTime: "2022-09-06T16:40:56.044799Z"
    message: 'The following tasks have failed: 0, see connectorStatus for more details.'
    reason: Throwable
    status: "True"
    type: NotReady
  connectorStatus:
    connector:
      ...
    name: my-sink-connector
    tasks:
    - id: 0
      state: FAILED
      trace: "org.apache.kafka.connect.errors.ConnectException
     ...
```

My thoughts were:
 - Is the AbstractConnectOperator the right place to be parsing the status? Should it be in the ConnectClientImpl instead?
 - Is the above the best user experience, e.g. what happens if someone pauses the connector, does it then move from NotReady to Ready?
 - Would a better solution be to keep the Ready condition tied to replication and then add a Warning condition that indicates a task or connector has failed?

**Comment by katheris** [comment]
To implement the last suggestion of adding Warning conditions I could update this ConnectorStatusAndConditions inner class to parse the statusResult and pick out failing connector and topics and add conditions based on that https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java#L685

**Comment by scholzj** [comment]
No strong opinions from my side TBH. 

The original author suggested this: `If one of the connector tasks reports it as a FAILED state then we should put this in the WARNINGS section with READY as True and this will allow Ops to react faster by building tools using this status.` => I guess that suggests adding new Warning condition. But I'm not sure I like it. Is it really a big change over current state where we already have the state anyway in the status, just not in conditions?

In the Kafka CR, the reconciliation fails and the status is not ready when any part of the Kafka cluster is not working. The design is a bit different. But that seems like something what makes a bit more sense to me maybe?

**Comment by katheris** [comment]
I guess the main difference is that currently as the user/ops team you have to write logic to parse the status, rather than relying on the known Kubernetes mechanism of checking the conditions. I think the complication is with the pause/resume and what should happen to the status then, is the connector "Ready" if it is paused?

> In the Kafka CR, the reconciliation fails and the status is not ready when any part of the Kafka cluster is not working. 
That is what I have in my current branch atm. Although I'm not actually failing the reconcile loop, I'm checking the status after the reconcile completes. I could instead have the status method in the ConnectApiClientImpl return an error if the status indicates a connector or task has failed. That would mean a change in behaviour because it would mean you couldn't pause a failed connector as the reconcile loop would fail before it got to the pause/resume step.

**Comment by scholzj** [comment]
I don't think you absolutely need to fail the reconciliation. That is a bit different in Kafka reconciliation -> if ZooKeeper cluster fails, it makes no sense to continue with Kafka. But here it is different. But it would make sense to log the error and set the state to NotReady, that is what I meant.
