### ISSUE TITLE
Pod disruption budget should be set to 0 when a rebalance is running

### ISSUE THREAD

**Issue by Sam-Kramer** [strimzi/strimzi-kafka-operator#6626]
**Is your feature request related to a problem? Please describe.**
Potentially, if a rebalance has been approved and starts running, a pod could restart as PDB is not set to 0. As result, the rebalance will fail if the pod being restarted is needed. 

**Describe the solution you'd like**
Set `maxUnavailable` to 0 for the PDB for a given Kafka cluster when we start a rebalance.

**Describe alternatives you've considered**
Current alternative is set this manually yourself in config, but would be nice if this was handled automatically.

**Comment by scholzj** [comment]
This could possibly disrupt many other things outside of Strimzi. So I don't think this should be done automatically. If this is what you want to use, I think you should configure it manually through the Kafka CR.

**Comment by Sam-Kramer** [comment]
Hey @scholzj  thanks for the quick reply. Out of curiosity, what are you thinking that this could potentially disrupt?

**Comment by scholzj** [comment]
It would for example mean that while running the rebalance, nodes cannot be drained, the pods cannot be re-scheduled etc. This would also in many cases impact completely different teams who have no idea about some Kafka rebalance. The impact of the blocked operations such as node draining is not necessarily clear - it could be for example just something simple such as some cost optimization, but also something more serious such as removing nodes with critical security issues during upgrade.

Just to be clear, I'm not necessarily saying that your Kubernetes cluster will crash and burn just because you set the PDB unavailability to 0. But I do not think it is so clearcut that the rebalance has a precedence for everyone and there might be a good reasons why you might not want it. So I think not having this done automatically would be a better way to go. 

The rebalancing is anyway currently driven through some additional process since it requires the approval of the proposal etc. So I think it might not be such a big deal to add it to this process for those who want it to behave that way.

**Comment by scholzj** [comment]
Triaged on 21st June: Setting the PDB to 0 might block some cluster wide actions as upgrades etc. We do not think this should happen automatically. If the user wants, they can set it to 0 manually as part of the rebalance, but it should not be done automatically for everyone.

In the future, when automatic rebalances are supported, we should think about how to make them resilient / recover from situations like this automatically.
