### ISSUE TITLE
Istio Ingress support

### ISSUE THREAD

**Issue by rforberger** [strimzi/strimzi-kafka-operator#6661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Istio support for the Strimzi Kafka operator.
Currently, only nginx ingress is supported. In order to expose the brokers with Istio, a service per broker pod is needed for the Istio VirtualService to forward traffic to.
When using the `cluster-name-kafka-brokers` service, Kubernetes will loadbalance between the broker pods resulting in partitions not available on certain brokers.

**Describe alternatives you've considered**
Loadbalancer type or Nginx ingress

**Additional context**
Is Istio support for Strimzi Kafka a planned feature?

**Comment by scholzj** [comment]
The Ingress API doesn't offer good compatibility between different controllers. We test with the Kubernetes Nginx Ingress controller as the de-facto standard. We cannot guarantee compatibility with other controllers since we do not test with them. But that does not mean it doesn't work with them. There were people in the past who got it working with Istio Ingress. Did you searched through GitHub / Slack about it? 

In general, I'm not sure we will do anything about this. Supporting/testing all the different Ingress controllers is not something we have resources for. And the Ingress API is anyway being replaced witht he Gateway API which hopefully offers better compatibility in the future.

**Comment by rforberger** [comment]
@scholzj OK, thanks for your comment. Well, Istio is more powerful than Nginx, but I can understand you don't have the resources to make Strimzi Kafka running with Istio. I searched through Github / Google, but only got it working partially. I have the problem, that Strimzi only deploys one Kubernetes service for the brokers when using the internal listener type and that my Kafka client then cannot directly connect to one specific broker, which hold a partition. I would need to expose the brokers one by one for exposing each one of them with Istio. This should be scaleable as well. I didn't get Strimzi Kafka with the ingress listener type working with Istio. 
OK, maybe with the Gateway API, compatibility will become better.
