### ISSUE TITLE
Cruise Control defaults to latest Kafka version image instead of using the `version` field

### ISSUE THREAD

**Issue by xsreality** [strimzi/strimzi-kafka-operator#6677]
**Describe the bug**
When Cruise Control is enabled, it uses the Strimzi Kafka image of latest version supported by the operator. The `version` field of Kafka spec is ignored. This is not a significant issue but it would be appropriate to use the image that is set by the `version` field to not have surprises.

**To Reproduce**
1. Deploy a Kafka resource with `version` field set to an older version (should not be latest).
2. Enable Cruise Control by adding `cruiseControl: {}`.
3. Note that the Cluster Operator starts Cruise Control with latest version of Kafka image instead of the one specified in `version` field.

**Expected behavior**
Cruise Control starts with the Kafka image of version specified in the `version` field.

**Environment (please complete the following information):**
 - Strimzi version: 0.27.1
 - Installation method: Helm Charts
 - Kubernetes cluster: Kubernetes 1.21
 - Infrastructure: Azure AKS

**Comment by scholzj** [comment]
This is not a bug, this is intentional. The Cruise Control version is the same for all Kafka versions. It has also its own independent configuration for the container image: https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L54-L55 ... the only reason why the Cruise Control shares the image with the Kafka is to make the build more efficient.

**Comment by xsreality** [comment]
Ah okay so components that are same across Kafka versions (like Cruise Control, Kafka exporter etc) default to the latest version of Kafka. That's clear!

**Comment by scholzj** [comment]
To be honest, ideally, they (Cruise Control and Exporter) should probably have their own container images and then they would have a tag without the Kafka version. But having too many container images is a bit impractical. The builds take muhc longer when you build and push more images. User who mirror the images into their own repositories will have more work etc. So we share the Kafka image also with CC and KE. But the CC and KE basically use only the image for the latest Kafka version (the CC and KE binaries are exactly the same in every one of the Kafka images, so there is no practical difference). It is probably not perfect, but it is not an error, it is intentional.

**Comment by xsreality** [comment]
I prefer having all these components in the same image! We are using CC and MM2 and it makes things simpler not having to deal with different images. It also helps with deploying at customer premises behind proxy not having to deal with too many images.

**Comment by scholzj** [comment]
Yeah, that is exactly one part of the logic why it is a single image - t make these things easier.
