### ISSUE TITLE
Improve Cruise Control chapter introduction

### ISSUE THREAD

**Issue by tomncooper** [strimzi/strimzi-kafka-operator#6810]
After #6800 is merged and the documentation in #6807 is added, we could do with a more comprehensive introduction to the CC chapter that includes a high level overview of the different rebalance modes.

**Comment by scholzj** [comment]
@ashutosh0022 There is a guide for contributong to the documentation: https://strimzi.io/contributing/guide/ ... so that might be the best start and if you have any questions afterwards, let us know. @PaulRMellor is our documentation guru, so I'm sure he will be able to help with most of the things as well.

**Comment by PaulRMellor** [comment]
Hi @tomncooper - What do you think we need on top of the [Rebalancing modes](https://strimzi.io/docs/operators/in-development/configuring.html#con-optimization-proposals-modes-str) overview?
