### ISSUE TITLE
kafka connect zip artifact

### ISSUE THREAD

**Issue by sirvio** [strimzi/strimzi-kafka-operator#7453]
run unzip with '-o' flag for kafka connect zip artifacts.

https://github.com/strimzi/strimzi-kafka-operator/blob/a0bacf022b53d1fe62c1d753b08742636d14def4/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java#L385

without the flag, consecutive deployments will fail because prompting user actions of already existing folder?

**Comment by scholzj** [comment]
Sorry, but can you please provide more details about the issue you run into instead of just saying what you think should be done? I don't really understand what _consecutive deployments_. The build starts every time with a clean image without any plugins. So there should be no _already existing_ folder.
