### ISSUE TITLE
Redesign the Config classes of User and Cluster operators

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7593]
The `UserOperatorConfig` and `ClusterOperatorConfig` classes become quite messy over time. They have a static method which parses the configuration input (Map with environment variables) to create a local variables. And then passes them to a constructor which covers all of these values. Later, getters are used to get the different configuration values from the config object.

Getting the values from the config through getters seems to work relatively well and should be probably kept. But the way how this is constructed is quite messy:
* A very large constructor with over 20 different fields
* Adding new values is messy
* In tests, it is fairly common that you want to change one particular value for a given test. But the config class is final and the constructor with 20 fields is a mess because you cannot configure just a single value. You have to configure all of them.

We should try to improve how the config instances are created and how can they be flexibly modified. For example using some _builder_ pattern or something similar. Maybe we can look for inspiration somewhere? The Topic Operator is using different logic => does that work any better? The Fabric8 Kubernetes client uses a builder pattern. Does that work well?

**Comment by ppatierno** [comment]
In this cases I usually use a builder pattern as you mentioned, with `withXXXX` methods to build the instance and final `build` one.
I am for it.

**Comment by scholzj** [comment]
Triaged on 12.1.2023: Makes sense to improve this. Proposal should not be needed.

**Comment by ShubhamRwt** [comment]
@scholzj Hi, Can I start to work on this issue?

**Comment by scholzj** [comment]
Sure, but I think it would be good to have an idea of what the plan is first.

**Comment by ShubhamRwt** [comment]
Great, Let me get up on how I am going to implement this and I will share my idea here

**Comment by ShubhamRwt** [comment]
@scholzj Hi, I went through the complete code today in the UserOperatorConfig. I also think that the best way to make it flexible would be to use the `builder` pattern. I am planning to add two classes named `UserOperatorConfigBuilder` and `UserOperatorConfigUtils`which will be used to build our `UserConfigOperator` to make things flexible. We can move the  logic used in `fromMap` method which is currently getting and setting all the values to `UserOperatorConfigUtils` class  so we can move the configs setting and getting work to their associated `withXxyyzz()` method. We can move the `getXXYYZZ()` methods in the `UserOperatorConfigUtils` class since it keeps the utilities that are being used in the Builder and leave the rest of the simple part for `UserOperatorConfig` class.

**Comment by ShubhamRwt** [comment]
@scholzj should I close this since both the bits are done in #8329 and #7975 ?
