### ISSUE TITLE
Refactor Connect and MM2 Assembly operators

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8158]
The `KafkaConnectAssemblyOperator` and `KafkaMirrorMaker2AssemblyOperator` are very similar with only a few differences:
* `KafkaConnectAssemblyOperator` has the Build feature which has to be integrated into it
* `KafkaMirrorMaker2AssemblyOperator` has the MM2 connectors which it manages

But there are many similar parts. We should try to bring more unification to these two and share the code better between them to make our life easier.

**Comment by scholzj** [comment]
Triaged on 9.3.2023: Makes sense to implement.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by katheris** [comment]
I had a look at this and proposed some improvements as part of #9955. There are two areas I think more improvements could be made:

1. Unifying the `createOrUpdate` methods by having the common parts represented in `AbstractConnectOperator` so the `KafkaConnectAssemblyOperator` and `KafkaMirrorMaker2AssemblyOperator` classes just contain the parts relating to the Build and MM2 connectors
2. Refactoring the connector reconciliation in `KafkaConnectAssemblyOperator` to make the code easier to follow and abstract out the similar parts to `KafkaMirrorMaker2AssemblyOperator` into `KafkaConnectAssemblyOperator`.

For the first one I think although it would make things look cleaner, but actually there are some subtle differences even in the steps that are similar, for example in `KafkaConnectAssemblyOperator` some steps are only executed if `useConnectorResources` is true. So I think it would end up almost being more confusing than just keeping them separate.

For the second one I started some of this refactoring, however because of the way the methods all return futures I found some subtleties in how the different futures are composed in `KafkaConnectAssemblyOperator`. So for now I don't think the risk of introducing bugs is worth the benefit we would get from the readability. If we needed to make other changes to these methods, for example to remove vert.x or make some wider change to how the reconciliation works then we could revisit this. I have kept the branch where I started the refactor so if anyone did want to look at this they could start there, but I think it will also be hard to review effectively.

So overall unless @haanhvu has some changes they had already started and want to contribute I would suggest we close this issue as partially done.

@scholzj what do you think?

**Comment by scholzj** [comment]
Thanks @katheris. I agree with your anaylsis, let's close this.
