### ISSUE TITLE
Add ability to add annotations to deployed resources

### ISSUE THREAD

**Issue by jrefi** [strimzi/strimzi-kafka-operator#817]
First of all, thank you for this project. It is exactly what I have been searching for. 

In order to fully integrate Strimzi into our cluster, we need the ability to append custom annotations to deployed resources. 

Some use cases include:
- Adding annotation to service to enable external dns.
- Adding annotation to KafkaConnect deployment to allow kiam roles.

I am interested in contributing to this project, so let me know if this would be a good starting issue.

Looking forward to what this project has in store. Thanks!

**Comment by scholzj** [comment]
@strimzi/developers I think we have two similar and related requests for adding metadata to the resources we create. This one for annotations and #810 for labels. We had also similar discussion in relation to Istio. We should probably think about the best way to fit this into the CRDs so that we don't have to change it later.

**Comment by scholzj** [comment]
@jrefi I think this is a reasonable request which we had already few times in some discussions. 

The kiam annotation sounds reasonable - this is actually one of the problems we have been thinking about as well ... how to pass things such as AWS credentials securely. 

I'm a bit curious what is your plan for annotation. Exposing Kafka outside of Kubernetes is currently not supported (see #128 for more details) and even once it is, Kafka configuration contains the broker addresses which it advertises to the clients. So I'm not sure about the value of adding specific DNS record to the service it self.

**Comment by ppatierno** [comment]
My 2 cents...not ad CRD guru...
I don't have a different solution right now and I have to think about that but with this proposal I think that we are exposing Kubernetes concepts too much: StatefulSets, Pods, Services and so on.
Having a Kafka resource means hiding "implementation" details to me where "implementation" details means what kind of Kubernetes native resources we are using. Of corse, the good thing of this solution is that  this is the more powerful solution.

**Comment by tombentley** [comment]
Since the StatefulSets, Services and Pods are there for all to see, there's very little hiding that can be done. And the fact is that to handle these use cases we need to end up with labels & annotations on Pods and Services, so it seems to me that this has to be expressed in the CR somehow and the only question then is how to do that. 

Are there any use cases which require labelling the StatefulSets?

If we're saying there's a `template` for the `kafka` (and `zookeeper`) resources, then that would provide an alternative home for other things which we set on the pod template – tolerations, affinity, resources and health probes – but which currently live directly on `kafka` (and `zookeeper`). It would look very arbitrary to a new user what was specified where within the CR, and it would be less intuity to anyone who knew the PodTemplate from k8s. So I think if this is the direction we go in, we need to consider moving these other things.

Rather than `service` and `headlessService` I would have expected it to be `bootstrapService` and `brokerService`.

**Comment by scholzj** [comment]
> Rather than service and headlessService I would have expected it to be bootstrapService and brokerService.

That would be fine for me.

> If we're saying there's a template for the kafka (and zookeeper) resources, then that would provide an alternative home for other things which we set on the pod template – tolerations, affinity, resources and health probes – but which currently live directly on kafka (and zookeeper). It would look very arbitrary to a new user what was specified where within the CR, and it would be less intuity to anyone who knew the PodTemplate from k8s. So I think if this is the direction we go in, we need to consider moving these other things.

Might be. But I think especially resources should be something everyone configures. It is not a niche option for few use cases. So this would make it more hidden and complicated to configure. It would also mean compatibility change.

> Are there any use cases which require labelling the StatefulSets?

I'm not sure I heard anything. But if we do it we can do it all.

**Comment by jrefi** [comment]
@scholzj Yeah I discovered that limitation about exposing Kafka after I put the issue in. I might still want to expose other components of the cluster though, specifically KafkaConnect. Our K8 cluster requires annotations on services for our Ingress controller to correctly configure everything.

**Comment by scholzj** [comment]
> > Rather than service and headlessService I would have expected it to be bootstrapService and brokerService.
> 
> That would be fine for me.

This would require us to have a separate objects for ZK and Kafka ... as ZK has no bootstrap and brokers service. Are we fine with it?

**Comment by tombentley** [comment]
Yes, I'm fine with that. I wish this wasn't quite so verbose though, but I can't think of anything better.

**Comment by scholzj** [comment]
This should be implemented in PR #1039 and will be release in 0.9.0. I will close this issue now. If you have any issues or problems, feel free to re-open it or open a new issue.
