### ISSUE TITLE
Operator service account requires permissions to create/delete ClusterRoleBindings

### ISSUE THREAD

**Issue by grecuionut** [strimzi/strimzi-kafka-operator#827]
Hi all,

In the current version, the Operator service account requires permissions to create/delete/update ClusterRoleBindings. The `strimzi-cluster-operator` cluster role includes the above permissions along side others. 

This raises security concerns, because the service account the Operator is running as, can modify/delete existing ClusterRoleBindings (including the system ones). 

Is it possible to remove the rule for the `clusterrolebindings` from 

> examples/install/cluster-operator/02-ClusterRole-strimzi-cluster-operator-role.yaml

manifest and create a separate role for the kafka cluster namespace? 

Is there any plan to change from ClusterRoleBinding to RoleBinding where you can have more controll?

Thank you

**Comment by scholzj** [comment]
I actually just opened a PR which does some of this - #828. However, I'm afraid that we cannot get rid of the `ClusterRoleBindings` completely. We need access to the nodes for the Kafka rack awareness feature. And because the nodes are cluster-wide resource, it needs `ClusterRoleBinding` to grant the access. And therefore we need to keep the possibility to create the `ClusterRoleBindings`.

We might add some option top disable this feature, but it is quite important, so you normally should skip it only for development purposes.

**Comment by grecuionut** [comment]
That's great. Do you have an estimated date for the 0.7.0 release?

**Comment by scholzj** [comment]
To be honest, there is not so much new features so far. Do you want a new release because of the RBAC changes? If that is the reason, you can also have a look at [this branch](https://github.com/strimzi/strimzi-kafka-operator/tree/role-bindings-instead-of-cluster-bindings/examples/install/cluster-operator), where the change from the PR #828 is also available for the 0.6.0 release RBACs.
