### ISSUE TITLE
[Enhancement]: unmanaged storage type configuration

### ISSUE THREAD

**Issue by MantasMiksys** [strimzi/strimzi-kafka-operator#8333]
### Related problem

Currently, `strimzi-kafka-operator` manages volume claims for Kafka and Zookeeper pods. It might be useful to have configuration which would disable that and instead delegate this functionality to an external system. An external system managing volumes could provide additional functionality such as scaling down of PVCs (which is currently not supported by `strimzi-kafka-operator`).

### Suggested solution

A new storage type e.g. `unmanaged` could be introduced.  If such storage type was configured, `strimzi-kafka-operator` would not specify `volumeClaimTemplate` for the respective StatefulSets/PodSets of Kafka or Zookeeper and instead an external system would take care of provisioning and attaching the necessary volumes.

**Comment by scholzj** [comment]
Sorry, but I don't think this makes any sense. The operator has to configure the storage because it needs to add it to the pods, mount it into the right part and configure the broker to use it. You will not be able to inject those.

Also, Strimzi does not manage the storage. Kubernetes actually does and we interact with it only. And Kubernetes already manages it through a pluggable system -> you can have you own storage drivers and storage classes.

**Comment by scholzj** [comment]
TBH, I think that is a complete edge-case which:
* Is not supported by most storage providers anyway (reason Strimzi does not support shrinking of storage is Kubernetes do not support it and most infrastructures do not support it)
* It is something you can work around manually if needed

This would likely cause way more maintenance effort than actual value for users.

In any case, I guess we will triage it on the next call.

**Comment by scholzj** [comment]
Triaged on 6.4.2023: Some of this might be possible by just creating the PVCs using the name Strimzi expects. Could be closed for the time being.
