### ISSUE TITLE
[Enhancement]: Support using "external" serviceAccounts 

### ISSUE THREAD

**Issue by azelezni** [strimzi/strimzi-kafka-operator#8391]
### Related problem

Currently when creating a `KafkaConnect` CRD, the operator creates a ServiceAccount with the format `<KafkaConenct-Name>-connect` to be used by said `KafkaConnect`.

To be able to add/update labels/annotations from the ServiceAccount we must use the `template` field in `KafkaConnect`.
Also RBAC is left to the user to manage.

Why can't I simply create the ServiceAccount myself tell KafkaConnect which ServiceAccount to use? I don't understand the logic behind this decision.
Having to create RBAC myself, and basically guess what the ServiceAccount name will be, is very strange, compared to just letting me create both the SA and RBAC.

I tried creating the ServiceAccount with the same name the controller would have used, and proving my own labels/annotations in the `KafkaConnect` CRD, but it just seems very strange, since I still have to configure RBAC outside the CRD.

As a "fix" I'm using `externalConfiguration` 

### Suggested solution

Allow specifying ServiceAccount name to use in `KafkaConnect` (and other relevant resources), otherwise let the controller create the ServiceAccount.

**Comment by scholzj** [comment]
The operator needs to make sure the resources exist and have a proper configuration. Having users create them on their own would just lead to issues, problems, support questions etc. Maybe if you want to create the resources your self, you should consider using some Helm Chart or YAMLs instead of an operator?

I do not understand what kind of RBAC you need to create your self and where you have to guess the name of the service account. The name of the service account is well documented and the only place where you need to create your own RBAC resource is when using the Config Map / Secret Config Provider -> in which case you have to do it because it is you who knows what config maps or secrets they need to have access to.

**Comment by azelezni** [comment]
Thanks for the response, we decide to write our own Helm chart.

**Comment by scholzj** [comment]
Triaged on 20.4.2023: This would add complexity as the operator and the deployments need to use the service account. Should be closed.
