### ISSUE TITLE
Certificate key replacement fails when Cluster Operator crashes before the trust is established

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8402]
When a Cluster CA private key is replaced, the operator needs to follow through a series of three different rolling updates:

1. First rolling update establishes the trust to the new CA while still using the old server certificates and trusting the old CA as well
2. Second rolling update issues and rolls out the new server certificates signed by the new CA (while still trusting the old CA as well)
3. Third rolling update removes the trust in the old CA

When the operator crashes before the first step is completed, it can happen that the operands will not trust the new CA. however, the operator will not detect it and recover from it and instead proceed with phase 2 and roll out the new certificates. This will not work, because trust will not be established and the operands will not sync during the rolling updates. If the trust is not rolled only to EO, KE or CC, it might still recover later. But if it fails before trust is rolled out to Zoo or Kafka, the clusters might not get back online anymore.

Note: This bug is present in the code already for some time :-/

Note 2: The description above describes the ideal state. But right now, due to #8401, phase 2 will actually pass successfully as it does not renew the certificates and everything will fall apart only in phase 3 when the trust is removed.

**Comment by scholzj** [comment]
Triaged on 20.4.2023: This is a bug. @ppatierno and @scholzj are already looking at the best way to fix it.

**Comment by ppatierno** [comment]
So looking into this, it seems that a good way to solve this problem as discussed with @scholzj as well is about storing the CA key generation (together with the CA cert generation we already have) on the resources, mainly on the ZooKeeper and Kafka (and other components) pods. So having something like:

```yaml
strimzi.io/cluster-ca-cert-generation: "0"
strimzi.io/cluster-ca-key-generation: "0"
```

This way, when the CO restarts (because it crashed during the step 1, what we can call the "trusting" phase), it's able to check that not all pods have the new trusted CA certificate (because of the old CA key generation), so the step 1 has to be completed.
I have got a draft solution doing that but, after restarting, the CO is not able to connect to the ZK or K pods where "trusting" didn't happen yet.
For example, assuming a cluster with 3 ZK and 3 K ...

1. Force the CA key replacement, new CA key is generated, new CA cert is created
2. Start phase 1 "trusting" new CA cert which is added to the first ZK pod-0 truststore
3. CO stops/crashes ... so "trusting" was not done for ZK pod-0 and pod-1, as well as for all the K pods
4. ... CO restarts

On restart, the reconcile by CA component logs the following 

```shell
2023-05-29 10:38:55 INFO  CaReconciler:428 - Reconciliation #1(watch) Kafka(default/my-cluster): Pod my-cluster-zookeeper-1 has key gen 0 compared to CA key 1
2023-05-29 10:38:55 INFO  CaReconciler:377 - Reconciliation #1(watch) Kafka(default/my-cluster): Need to continue trusting new CA ....
2023-05-29 10:38:55 WARN  ZookeeperLeaderFinder:248 - Reconciliation #1(watch) Kafka(default/my-cluster): ZK my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.default.svc.cluster.local:2181: failed to connect to zookeeper:
2023-05-29 10:38:55 INFO  ZookeeperLeaderFinder:220 - Reconciliation #1(watch) Kafka(default/my-cluster): Pod my-cluster-zookeeper-2 is not a leader
2023-05-29 10:38:55 WARN  ZookeeperLeaderFinder:248 - Reconciliation #1(watch) Kafka(default/my-cluster): ZK my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.default.svc.cluster.local:2181: failed to connect to zookeeper:
2023-05-29 10:38:55 INFO  ZookeeperLeaderFinder:220 - Reconciliation #1(watch) Kafka(default/my-cluster): Pod my-cluster-zookeeper-1 is not a leader
2023-05-29 10:38:56 INFO  ZookeeperLeaderFinder:220 - Reconciliation #1(watch) Kafka(default/my-cluster): Pod my-cluster-zookeeper-0 is not a leader
```

It's able to detect that "trusting" phase didn't finish properly.
You can also notice that it's able to connect to ZK pod-0 (it was the only one to "trust" the new CA cert) but not ZK pod-1 and pod-2.
The reason is the following.
When CO restarts, in order to do ZK rolling and before finding the ZK leader, the ZK client on the CO is configured for TLS handshake and TLS client authentication.
From a TLS handshake perspective, everything works fine because with all ZK pods because they are still trusting old CA cert (with ZK pod-0 trusting the new one as well). The ZK client is configured with all the CA certs (old and new) from the corresponding Secret.
What is failing is the TLS client authentication.
On restarting, within the CO certs Secrets, the cluster-operator crt and key are new and signed with the new CA certificate. Of course, ZK pod-0 is able to trust it, but not ZK pod-1 and pod-2.
After some retries failing, the CO forces the rolling so the step 1 ("trusting" new CA cert) is completed.

But then moving to the Kafka rolling, the same happens with the Kafka roller and the Kafka Admin client within the CO.

```shell
2023-05-29 10:41:59 WARN  AdminMetadataManager:232 - [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error
org.apache.kafka.common.errors.SslAuthenticationException: Failed to process post-handshake messages
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
```

This happens on more retries of course, until the CO decides to force rolling all Kafka pods and the step 1 ("trusting" new CA cert) is completed.
Finally, CO moves forward through step 2 and 3.

While after the above failures, the pods are "force" rolled and everything ends ok, I would assume that mainly for Kafka the force rolling is not acceptable. 
What I had in mind was postponing the creation of a new cluster-operator crt and key (signed by the new CA cert) until the "trusting" phase is completed.

Any thoughts?

**Comment by ppatierno** [comment]
> I think the problem is easy - not sure if the solution is easy too ... but the CO should not update its user certificate before rolling out the trust.

yeah, that's exactly what I described but need to investigate about the solution :-)

> Annotating the pods with strimzi.io/cluster-ca-key-generation is IMHO confusing since the pod will not be using this CA generation yet at that point which would be probably the expected way to read this -> it will only trust it. So I wonder if it should be a different annotation that makes it a bit more clear it is about trust.

let me think aloud ... when you have a new CA key generation "1" (in the CA secret) and you are still in the trusting phase, having `strimzi.io/cluster-ca-key-generation=0` makes still sense. That's the way I can detect that "trusting" is not done yet, because the two key generations are different (between the CA secret and pod). It happens the same for the `strimzi.io/cluster-ca-cluster-generation`. The generations are updated after the "trusting" phase is complete and phase 2 starts.

> Annotating the pods will likely create conflicts with the Node Pool work. So you should check if the code will be feasible also within the scope of that PR or not.

I will take a look. I sounds that if not feasible, I should not invest more time to fix the issue until your node-pool PR is merged.

**Comment by scholzj** [comment]
> let me think aloud ... when you have a new CA key generation "1" (in the CA secret) and you are still in the trusting phase, having strimzi.io/cluster-ca-key-generation=0 makes still sense. That's the way I can detect that "trusting" is not done yet, because the two key generations are different (between the CA secret and pod). It happens the same for the strimzi.io/cluster-ca-cluster-generation. The generations are updated after the "trusting" phase is complete and phase 2 starts.

The problem is that the annotation does not have a clear meaning. I would read `strimzi.io/cluster-ca-key-generation` as _uses certificates signed by this generation key_. But here you are suggesting that it means only _trusting this generation_ if I understand it correctly. I think that is confusing and might be a problem in the future if we need another annotation to indicate that this pod is actually using a server certs signed by this generation.

**Comment by ppatierno** [comment]
> The problem is that the annotation does not have a clear meaning. I would read strimzi.io/cluster-ca-key-generation as uses certificates signed by this generation key. 

Considering the corresponding `strimzi.io/cluster-ca-cert-generation` we already have, I think this has the meaning you are talking about. During the step 1 it stays as "0" but then on step 2 when new server certs are generated and signed by new CA cert, it moves to be "1".

> But here you are suggesting that it means only trusting this generation if I understand it correctly. I think that is confusing and might be a problem in the future if we need another annotation to indicate that this pod is actually using a server certs signed by this generation.

At this point what comes to my mind would be something like a `strimzi.io/cluster-ca-trusted-generations` as an array of cluster CA generations trusted by ZK and K pods. It should somehow reflects what is actually contained in the corresponding truststore. This way we could get the new cluster-ca-cert-generation (from the Secret) and verify that it's contained in that list. NOTE: I am now talking about CA cert generation, not CA key generation which could make more sense because talking about trusting (and anyway they always go together).
Wdyt?

**Comment by ppatierno** [comment]
> I don't think you really understand the generations which are trusted in our code. So you cannot make it an array -> you can just keep the last key generation for which you rolled the trust. Given we roll the trust for keys and not certs ...

Not sure I follow or agree with what you mean/say. We trust a CA cert which is put inside the truststore. Of course, a new CA cert to trust comes from a new CA key (they are generated together), so you are somehow trusting them together.

> I would say that strimzi.io/cluster-ca-key-trusted-generations would be more clear as it would be more obvious it should be compared against the key generation and not cert generation.

Now I am confused. The previous sentence you say `you cannot make it an array`  and now you are suggesting a name with plural "generations". I also don't get why it cannot be a list/array: in the end there is a period of time across the 3 steps where you are trusting a list of CA certs (in general 2 of them, both old and new).

**Comment by ppatierno** [comment]
I think now I see your point. Renewing a CA cert without a new CA key increases the CA cert generation (more and more if done multiple times) but the CA key generation stays the same, so they could diverge a lot.

So I would assume, the solution I was proposing still work, just changing the annotation name with your suggestion `strimzi.io/cluster-ca-key-trusted-generation`. Need to figure out how to delay the cluster-operator crt and key generation untile "trusting" is done.
