### ISSUE TITLE
[Enhancement]: Skip building own kafka connect image if exists in registry

### ISSUE THREAD

**Issue by tankim** [strimzi/strimzi-kafka-operator#8538]
### Suggested solution

As you know, the kafka connect custom resource provides the ability to build an image.
However, even though the image hasn't changed, the build operation is executed every time you create a kafka connect.
Why don't you add a feature to avoid building if the same image already exists in the output registry?

**Comment by scholzj** [comment]
I think this is very complicated given the value it adds. Strimzi would need to query the registry to find if the image exists and somehow test if the image has the same build configuration. I'm also sure there will be users asking for the opposite -> to rebuild it even if it exists since the old image might have some CVEs, might have pulled old plugins etc.

**Comment by tankim** [comment]
Thanks for the comment. 
It sounds like it could be worthwhile, but it could get very complicated.

**Comment by scholzj** [comment]
Triaged on 1.6.2023: This should be rejected:
* Implementing some functionality to query the different container registries with different API versions would be quite complicated.
* It is not obvious how to find out that the image is the same:
    * The same Dockerfile might use a newer base image with CVE fixes in the rebuild
    * The downloaded artifacts might have changed since last time
    * Etc.
    * As a result, it is not simple to find out if something changed or not. If nothing changed and the layers are identical to previous build, they should not be really pushed to the registry - that should be already part of Kaniko.
