### ISSUE TITLE
[Enhancement]: StrimziPodSet default behaviour enhanced to respect topology.kubernetes.io/zone label

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#8867]
### Related problem

Currently on a cluster with topology zone labels setup, but no affinities set, a Kafka/StrimziPodSet will spread evenly across nodes, but does not respect the topology label: `topology.kubernetes.io/zone`

as you can see here, I have labelled my nodes with the topology key:
```
samuelhawker at samuels-mbp in ~/github/strimzi-kafka-operator on 10443 [$]

$ oc get nodes -oyaml worker0.samten.cp.fyre.ibm.com | grep zone

    topology.kubernetes.io/zone: "0"



samuelhawker at samuels-mbp in ~/github/strimzi-kafka-operator on 10443 [$]

$ oc get nodes -oyaml worker1.samten.cp.fyre.ibm.com | grep zone

    topology.kubernetes.io/zone: "0"



samuelhawker at samuels-mbp in ~/github/strimzi-kafka-operator on 10443 [$]
$ oc get nodes -oyaml worker2.samten.cp.fyre.ibm.com | grep zone

    topology.kubernetes.io/zone: "1"
```
However, when provisioning it does not seem to be respecting this label on the nodes and is still splitting them equally:
```
prod-6-brokers-kafka-0                            1/1     Running   0          6m45s   10.254.22.211   worker0.samten.cp.fyre.ibm.com   <none>           <none>

prod-6-brokers-kafka-1                            1/1     Running   0          4m17s   10.254.22.215   worker0.samten.cp.fyre.ibm.com   <none>           <none>

prod-6-brokers-kafka-2                            1/1     Running   0          6m39s   10.254.17.41    worker2.samten.cp.fyre.ibm.com   <none>           <none>

prod-6-brokers-kafka-3                            1/1     Running   0          6m39s   10.254.13.131   worker1.samten.cp.fyre.ibm.com   <none>           <none>

prod-6-brokers-kafka-4                            1/1     Running   0          6m43s   10.254.17.40    worker2.samten.cp.fyre.ibm.com   <none>           <none>

prod-6-brokers-kafka-5                            1/1     Running   0          6m42s   10.254.13.130   worker1.samten.cp.fyre.ibm.com   <none>           <none>
```

In a situation where a user has no defined affinities this can be an issue for resiliency.

### Suggested solution

The obvious solution here is to blame the user, and insist that they set antiaffinity rules matching the zone labels.
However, since topology labels are well known https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone and used by Kubernetes controllers such as on the `ReplicaSet` object, I don't think it is unreasonable to suggest the StrimziPodSet controller should prioritise zone balancing, rather than node balancing, atleast on new installs.
To achieve this the StrimziPodSet controller would need to be enhanced to also factor in node labels when scheduling pods.

### Alternatives

User sets antiaffinity rules matching the zone labels.

**Comment by scholzj** [comment]
I'm not aware of any such built-in logic in the other controllers and such logic cannot be built into the StrimziPodSetController either. It does not schedule the pods. Kubernetes schedules the pods.

**Comment by scholzj** [comment]
But creating the pod is not the same as scheduling the pod - Kubernetes do the scheduling. 

You could in theory inject the affinity, but that does not make sense:
* It is a breaking change
* Many users will not have the labels at all and it will not work for them
* What affinity would you use? Preferred? Required? None of them works for everyone.
* There are also many implications with regards to the storage affinity

So this would IMHO just introduce problems to various types of users. Users have to tune the configuration to their environment, otherwise the operator will not work for many of them out of the box.

----

Also, you present it as something that worked before, but as I said, I'm not aware of that. StatefulSet not ReplicaSets do not inject any default affinities either. So I do not think this is a different behavior and there is no reason to introduce a difference.

**Comment by samuel-hawker** [comment]
These are all good points.
Thank you for taking the time to respond Jakub.
I think your questions definitely highlight some issues with this proposed enhancement.
The behaviour as-is works well, and custom affinities address all use cases.
Closing this issue.
