### ISSUE TITLE
[Enhancement]: Allows disabling leader election in Helm chart

### ISSUE THREAD

**Issue by SoerenHenning** [strimzi/strimzi-kafka-operator#8893]
### Related problem

Up until Strimzi 0.30 it was possible to disable `createGlobalResources` in the Helm chart and still get the basic functionality of Strimzi. (While I understand that this basic functionality might not be sufficient for production, we use it a lot in benchmarking scenarios, where users do not have full cluster permissions.)

Since the leader election introduced with Strimzi 0.31, this is no longer possible as the cluster operator fails without having the necessary permissions.

### Suggested solution

Leader election seems to be an optional feature, which might not be required as long as you know what you are doing. Leader election can be disabled by setting `STRIMZI_LEADER_ELECTION_ENABLED=false`. However, there is currently no way to set this configuration in the Helm installation. Hence, I propose to add an option to the Helm chart, which disables the leader election by setting the environment variable to false.

### Additional context

I will create a corresponding pull request.

**Comment by scholzj** [comment]
The `createGlobalResources` flag expects you to create the global resources manually out of band (for example have some admin do it for you). It is not expected to work without the global resources installed. 

So I think your situation is different from how you present it:
* Someone installed for you the global resources some time ago based on a Strimzi version prior to 0.31.
* You are now installing new versions of Strimzi while using the old resources.

So the leader election breaks it for you because it is one of the many things missing in the RBAC resources someone created for you some time ago. Disabling it might fix it - but it also might fix it only till the next version which adds something else or it might just move to another error. 

So the real and proper solution is to update the cluster resources in your cluster and not and try to disable the features in the operator.

**Comment by SoerenHenning** [comment]
Indeed, you are right and I have confused it: We have custom roles/role bindings to grant the required permissions on a namespace-level (not cluster-wide). This limits some features and upgrades might break things (as in this case), but allows us to provide the core features without cluster-wide permissions. In short, I was able to grant to required permissions for the leader election by editing our custom role.

Thank you for detailed explanation and setting me on the right track!
