### ISSUE TITLE
kafka-cluster-zookeper  starts with networking issues

### ISSUE THREAD

**Issue by adnanitdev** [strimzi/strimzi-kafka-operator#9341]
### Bug Description

zookeeper logs indicates a networking issue where the zookeeper service is unable to resolve the address for kafka-cluster-zookeeper-0.kafka-cluster-zookeeper-nodes.test.svc on port 2888.

`zookeeper logs:  ERROR Couldn't bind to kafka-cluster-zookeeper-0.kafka-cluster-zookeeper-nodes.test.svc/<unresolved>:2888 (org.apache.zookeeper.server.quorum.Leader)`

The workaround is to restart the pod once or twice to start without any errors. Also, this happens less frequently probably because of slow dns 

### Steps to reproduce

Just create a new cluster 

### Expected behavior

Zookeper should start without any networking errors

### Strimzi version

0.38.0

### Kubernetes version

1.27

### Installation method

Helm Chart

### Infrastructure

EKS, Kind, k3s

**Comment by scholzj** [comment]
That is one of the issues new versions of ZooKeeper have with DNS. You can try to delete the pod and it might catch up. Sometimes it also helps to restart your DNS pods to get better responses from them. But I do not think there is much we can do about this in Strimzi. This would need to be fixed in ZooKeeper.

**Comment by adnanitdev** [comment]
> That is one of the issues new versions of ZooKeeper have with DNS. You can try to delete the pod and it might catch up. Sometimes it also helps to restart your DNS pods to get better responses from them. But I do not think there is much we can do about this in Strimzi. This would need to be fixed in ZooKeeper.

Is there a stable version of  zookeper which dont have this issue. I am currently on 3.8.2

**Comment by scholzj** [comment]
I don't know. We have to use the ZooKeeper version used by Kafka as it is part of Kafka binaries.

**Comment by Kyle-Cooley** [comment]
I run into this issue often on minikube. Deleting the pod is problematic because the new pod has a new ip and encounters the same problem. As a workaround, I run the below command to find the zookeeper process. I then kill it. I think this works reliably for me because a container restart does not result in a new ip address.

```bash
ps aux | grep /opt/kafka/bin/zookeeper-server-start.sh | grep -v grep | awk '{print $2}'
```
