### ISSUE TITLE
[Enhancement]: Make the reconcile loop order more resilient and change the order

### ISSUE THREAD

**Issue by arianitu** [strimzi/strimzi-kafka-operator#9402]
### Related problem

We ran into a bit of a crazy situation where we were on Kubernetes 1.25+ and we were using operator version 0.20.0 and there was NO way for us to upgrade the operator, OR get the operator running again OR get the Kafka cluster running again because the certs were expired.

You can see us go through the problem here: https://github.com/strimzi/strimzi-kafka-operator/issues/6136 and the solution.

### Suggested solution

We recommend you re-order the reconcile loop based on two factors:

1. Critical operations FIRST, such as cert generation AND secret generation. Any reconcile operation that may cause the Kafka cluster to break down should be first. 
2. Any use of v1beta/v1alpha, etc operations should be LAST (if possible.) In our case, our Kafka cluster would never have went down if the cert generation was first and v1beta API usage was done LATER.

If the order of these operations do not matter, I highly recommend you guys change it, especially something as critical as cert generation.

**Comment by scholzj** [comment]
It is great that you were able to change the code to solve your issue. That is what open source enables. However, that was your choice. Other users who ran into this issue did not require any source code modifications. And just because something works for you in one particular situation, it does not mean it works in all other cases and situations.

Also, Kubernetes 1.25 was released almost two years after Strimzi 0.20. If you want to future-proof a project for Kubernetes releases several years later, maybe we can do _all the steps only at the end_ to avoid any possible conflicts with new API versions. How many years ahead should we _plan_? Maybe the certificates should actually be done last because one day there might be a `v2` version of the Secret API.

**Comment by arianitu** [comment]
@scholzj 

I have a MySQL instance that's been running for 5+ years, as a StatefulSet, no issues.  I'm pretty confident that MySQL instance will continue to start, even 5+ years from now, perhaps even 10+ years.  I feel confident that StatefulSet will continue to work for me, indefinitely. My Go program's continue to compile for 10+ years now. 

**shrug**

Your comments joking about future-proofing for v2 of SecretAPI is actually a bit funny because Kubernetes has had its own share of incompatibilities and upgrade issues. You may want to do that =)

I think the upgrade path of Kubernetes and its operators are the worst part of Kubernetes (in terms of user experience), so anything to make that better is a great goal imo.

Anyway, thanks for all your work on the project, good luck! You can close this if you do not think its relevant to the project.

**Comment by scholzj** [comment]
We do not close issues based on individual opinions. It will be triaged on the community call where it will be decided what to do with it.
